Aiven-Open/klaw

ReleaseNotes.txt
src/main/resources/templates/browseAcls.html
src/main/resources/templates/execAcls.html
src/main/resources/templates/myAclRequests.html
src/main/resources/templates/requestAcls.html
src/main/resources/templates/syncBackAcls.html
src/main/resources/templates/synchronizeAcls.html

Incorrect spelling "principle" has been fixed wherever it would be visible on screen. For now I have left similar typos in variable names and other code usages alone to avoid breaking anything.

Fixed principal typos

---

src/main/java/io/aiven/klaw/config/ManageDatabase.java
src/main/java/io/aiven/klaw/service/AclControllerService.java
src/main/java/io/aiven/klaw/service/ClusterApiService.java
src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
src/main/java/io/aiven/klaw/service/KafkaConnectSyncControllerService.java
src/main/java/io/aiven/klaw/service/ServerConfigService.java
src/main/java/io/aiven/klaw/service/TopicControllerService.java
src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
src/test/java/io/aiven/klaw/TopicAclControllerIT.java
src/test/java/io/aiven/klaw/UsersTeamsControllerIT.java
src/test/java/io/aiven/klaw/controller/AclControllerTest.java
src/test/java/io/aiven/klaw/controller/SchemaRegstryControllerTest.java
src/test/java/io/aiven/klaw/controller/ServerConfigControllerTest.java
src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java
src/test/java/io/aiven/klaw/controller/UtilControllerTest.java

Since `ObjectMapper` is a threadsafe as stated in its javadoc
```
* Mapper instances are fully thread-safe provided that ALL configuration of the
* instance occurs before ANY read or write calls. If configuration of a mapper instance
* is modified after first usage, changes may or may not take effect, and configuration
* calls themselves may fail.
```
It does not make sense to create these objects each time
Why this way

Move ObjectMapper to static final

---

src/main/resources/templates/addCluster.html

Removed the notice about acceptable port ranges from the bootstrap servers section of Kafka clusters. 
This validation is not enforced anyway - it would not work with Aiven for Apache Kafka clusters whose service ports are always outside this range.

Removed allowed port range from label

---

src/main/resources/templates/addCluster.html
src/main/resources/templates/modifyCluster.html

Companion change of https://github.com/aiven/klaw-cluster-api/pull/10. Adds new option to protocol selection to allow SASL_SSL/SCRAM authentication.

Added support for SASL_SSL/SCRAM authentication

---

src/main/java/io/aiven/klaw/service/RolesPermissionsControllerService.java
src/main/resources/application.properties
src/test/java/io/aiven/klaw/MockMethods.java
src/test/java/io/aiven/klaw/RolesPermissionsControllerIT.java
src/test/resources/test-application-rdbms.properties
src/test/resources/test-application-rdbms1.properties

There was an issue when new role is created and adding new permissions. this change fixes it and permissions are saved.
Resolves: #73 #75 
Why this way
There was no tenant id set when saving permissions, and hence permissions are being added randomly to a unexisting tenantid. It's a bug, and fixed now.

Update permissions bugfix and acl command fix

---

coral/.eslintrc.cjs
coral/package.json
coral/pnpm-lock.yaml
coral/src/App.tsx
coral/src/main.tsx

Introduce the following commands:
- `pnpm run lint`
- Runs both [prettier](https://prettier.io/) check and [ESLint](https://eslint.org/)
- `pnpm run reformat`
- Runs [prettier](https://prettier.io/) with `--write` flag
The current configuration for Prettier and ESLint are minimal defaults.
Resolves: #110

coral: add static linting

---

.github/workflows/coral-pr-pipeline.yml

Run static checks (eslint + prettier) and unitests for every
PR that includes changes to `/coral/**`.
Resolves: #108, #109

feat[coral]: Introduce GH action for Coral PR check

---

coral/jest.config.ts
coral/package.json
coral/pnpm-lock.yaml
coral/src/App.module.css
coral/src/App.tsx

CSS Modules work by default. This PR will not include typescript-plugin-css-modules
as a dependency as it does not support React 18 and is not a must have.
Refers: #113

feat[coral]: Showcase css modules with example

---

.github/workflows/maven.yml

Signed-off-by: Josep Prat <josep.prat@klaw-project.io>

fix: put persist-credentials flag properly

---

coral/.eslintrc.cjs
coral/jest.config.ts
coral/package.json
coral/pnpm-lock.yaml
coral/src/main.tsx
coral/src/pages/hello/index.test.tsx
coral/src/pages/index.test.tsx
coral/src/router.tsx
coral/tsconfig.json
coral/vite.config.ts

Configures TS and vite to use absolut imports where  "@/" maps to `coral/src`. 
Adds a eslint rule to restrict imports using relative paths except from the same directory.
**Why this way**
Avoiding relative imports is making potential refactoring more smooth. It also adds readability for the imports.

Add alias for absolute imports in coral.

---

CONTRIBUTING.md

Adds more detail on how to contribute. 
The doc tries to answer following questions: 
- what are ways to contribute?
- how to I create an issue?
- how do I work on an issue?
- how should a pull request look like?
Resolves: #99 
**Why this way**
Since we don't have a more strict set of rules yet, I tried to keep it a bit more open while still providing a guideline for people who would want to contribute. I thought about adding some examples like I did with the commit messages, but decided we can do that later and than e.g. link a pull request as example etc. 
In general I tried to create a "voice" that is welcoming and makes it clear that every contribution is welcome! The text should provide a good entry point to contribute. I also wanted it to provide …

Extend CONTRIBUTING docs.

---

pom.xml
src/main/java/io/aiven/klaw/service/ClusterApiService.java
src/main/java/io/aiven/klaw/service/ServerConfigService.java
src/main/resources/application.properties
src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
src/test/java/io/aiven/klaw/service/ServerConfigServiceTest.java

Connects to Klaw ClusterApi with a jwt token
getServerConfig security issue fixed. normal users should not get any server configuration
Actuator endpoints to show fewer than wildcard
Resolves:
Why this way : token based authentication is better. getServerconfig restriction based on role.

Cluster Api security

---

coral/.eslintrc.cjs
coral/src/router.tsx

Page components should be only imported from a `router.tsx` file. In order to be able to enforce that,
we need to introduce `no-restricted-imports` rule that disallows all imports from `/src/pages` folder
with a single exception.
Currently the exception is implemented with a `overrides` and actual Javascript. It is not pretty, but it
seems to get the job done.
Resolves: #155

feat[coral]: no-restricted-imports for page components

---

CONTRIBUTING.md

Adds information about how we do merge requests (squash merge).
Resolves: #164

docs: add information about squash-merge method.

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/pages/Login.test.tsx
coral/src/app/pages/Login.tsx

- Adds styles (based on Aiven DS) and rudimentary behavior for `Login` page
- Adds tests for the current behavior
- Adds a new component `PasswordInput` to `Form`. The component is a 1:1 copy from `TextInput` with only difference being `type="password"`. This adds extra security for users when they type in their password, because it obscures what they type in.
Resolves: #142 
- tests are not 100% necessary right now, but I wanted to add them to see if we have all libs etc. in place

feat: Add rudimentary style and behavior for login page.

---

.gitignore
Makefile
coral/.env.springboot
coral/src/app/router.tsx
coral/src/vite-env.d.ts
src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java
src/main/java/io/aiven/klaw/controller/CoralController.java
src/main/resources/application.properties

Introduce a Makefile with a default target that builds `coral` project into Klaw springboot application. If the user has set `klaw.coral.enabled=true` in `application.properties` they are able to access the Coral application from `/coral` paths inside the springboot app.
Resolves: #157

feat: run coral inside Klaw springboot application

---

coral/docs/frontend-testing.md

- general rules
- usage of our libs
- goals for our testing approach
- how to structure and group tests
- how to write tests descriptions
This commit also adds a TOC for the file.
Resolves: #199 
I decided to move a few points out of scope for this PR until we have a few more tests in the code base and can add examples, if we still feel we want to make some things explicit (like not too much abstraction).

docs(coral): Add base for frontend testing approach in coral docs.

---

coral/jest.config.ts
coral/src/app/features/login/LoginForm.test.tsx
coral/src/app/pages/Hello.test.tsx
coral/src/app/pages/Login.test.tsx
coral/src/app/pages/index.test.tsx

- remove auto cleanup afterEach in jest config, see: https://testing-library.com/docs/react-testing-library/setup/#skipping-auto-cleanup
- update existing tests
Samuli and I discussed this yesterday:
- using custom setup and teardowns for rendered components instead of using a automated cleanup after each
-  reduces the time a component in a test needs to be rendered, e.g. when checking different things on an unchanging state of a rendered component
- in the last (professional) app we used that approach, we had in a still small number of tests ( ~ 150) a more then 30% reduced number of renders
- based on my experience, this will speed up tests, especially for CI when they run without cache 
- this setting _enables_ to do custom cleanup, but people can also use a `beforeEach(cleanup)` at …

refactor(coral): Enable custom setup and teardown in React tests.

---

openapi.yaml

The file is not yet used anywhere. However, it will provide us a meaningful artefact to facilitate our future discussion and it will be used as the source of truth for API in the future
Closes: #148

docs: introduce OpenAPI specification file

---

.gitignore
coral/README.md
coral/docs/development-with-remote-api.md
coral/vite.config.ts

Add support and instructions for providing self-signed certificates in order to run development server over HTTPS.
Introduce new $VITE_PROXY_TARGET configuration value to override default API location.
Resolves: #214

feat(coral): Enable running Coral against remote API over HTTPS [#214]

---

coral/src/app/features/topics/components/list/TopicCard.tsx

Fix simple import error introduced in https://github.com/aiven/klaw/pull/218.
CSS module import path before https://github.com/aiven/klaw/pull/218:
`src/app/features/topics/components/TopicCard.module.css`
CSS module import path after https://github.com/aiven/klaw/pull/218:
`src/app/features/topics/list/components/TopicCard.module.css`
CSS module path before https://github.com/aiven/klaw/pull/218:
`src/app/features/topics/components/TopicCard.module.css`
CSS module path after https://github.com/aiven/klaw/pull/218:
`src/app/features/topics/components/list/TopicCard.module.css`

fix(coral): Fix TopicCard css module import path

---

coral/src/app/features/topics/BrowseTopics.tsx
coral/src/app/features/topics/hooks/list/useGetTopics.ts
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-queries.ts
coral/src/services/api-client/index.ts

Switch `/getTopics` API call from manually created native fetch call to Coral API client.

refactor(coral): use API client with GET topics request 

---

coral/src/app/features/topics/BrowseTopics.test.tsx
coral/src/app/features/topics/hooks/list/useGetTopics.test.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/domain/topic/topic-api.msw.ts

The mocked API payload shape should defined closer where it is relevant. If we would use the scenario model, we would have ever growing list of hard coded mocks whereas we could have it more "dynamic".

refactor(coral): improve MSW response mocking

---

coral/src/app/features/topics/BrowseTopics.test.tsx
coral/src/app/features/topics/hooks/teams/useGetTeams.test.tsx
coral/src/app/features/topics/hooks/teams/useGetTeams.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/domain/team/team-api.msw.ts
coral/src/domain/topic/topic-api.msw.ts

Moves the mocked `getTeams` api response to the right directory.

refactor(coral): Move team api mocks.

---

.gitignore
coral/Makefile
core/src/main/java/io/aiven/klaw/config/ConfigUtils.java

- Fix .gitignore for embdeded Coral asset paths in Klaw core resources 
- Fix make targets to toggle embedded Coral with Klaw core.
- Require authentication for Coral application paths. 
Resolves: #185

feat: require authentication for Coral application paths

---

core/src/main/java/io/aiven/klaw/helpers/UtilMethods.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java

There are several same implementations of `getUserName` method
The PR extracts it into one place `io.aiven.klaw.helpers.UtilMethods#getUserName(java.lang.Object, java.lang.String)` and makes others using it

Move getUserName to one place

---

coral/src/app/features/browse-topics/hooks/teams/useGetTeams.tsx
coral/src/domain/team/team-api.msw.ts
coral/src/domain/team/team-api.ts
coral/src/domain/team/team-transformer.test.ts
coral/src/domain/team/team-transformer.ts
coral/src/domain/team/team-types.ts
coral/types/api.d.ts

Update generated API types to include teams and environment APIs. These
are needed required for browse topics filters.
Use Coral API client to fetch available team names instead of a custom
native fetch.
Add a simple transformation that omits "All teams" from response data.
It is better to define the  the empty state in component instead of
returning it as part of teams API response.
Refers: #196

feat(coral):  Connect teams API to real backend instead of mocked one

---

core/pom.xml

Currently there is a duplicated dependency in pom leading to warning in `mvn` output
```
[WARNING] Some problems were encountered while building the effective model for io.aiven:klaw:jar:1.1.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework.boot:spring-boot-starter-oauth2-client:jar -> duplicate declaration of version (?) @ line 71, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
This PR fixes this

Remove duplicated dependency

---

coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.ts
coral/src/domain/topic/topic-types.ts
coral/types/api.d.ts
openapi.yaml

- Fix openapi specification for Topic resource
- Set deprecated `clusterId` property nullable to Topic resource
- Add `sequence` property to Topic resource
- Use Topic types defined in OpenAPI specification in Coral
- Remove API mock usage from browser environment 
Resolves: #196

feat(coral): Connect topic API to real backend instead of mocked one

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/BrowseTopics.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.test.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.tsx
coral/src/app/features/browse-topics/hooks/environment/useGetEnvironments.test.tsx
coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.ts
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-test-helper.test.ts
coral/src/domain/environment/environment-test-helper.ts
coral/src/domain/environment/environment-transformer.test.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-test-helper.ts

Extend our domain model for environment from plain string into object with name and id.
Resolves: #268

fix(coral): Send environment id instead of name as topic filter parameter

---

coral/package.json

Pre-commit hook didn't check for `.css`, but we're using a few `.css` files now.

refactor(coral): Check css file format in pre-commit hook.

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/BrowseTopics.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.test.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.tsx
coral/src/app/features/browse-topics/components/select-team/SelectTeam.tsx
coral/src/app/features/browse-topics/hooks/topic-list/useGetTopics.ts
coral/src/app/pages/topics/index.test.tsx
coral/src/domain/environment/environment-types.ts
coral/src/domain/environment/index.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-queries.ts

- `SelectEnvironment` is responsible for fetching
environments, getting environment value from potential
search query and update query of needed
- `BrowseTopics` is responsible for holding
the environmentName state to handle api calls
- `getBrowseTopcis` query will only call api
when environmentName value is set by BrowseTopics
to prevent too much requests
Resolves: [#245](https://github.com/aiven/klaw/issues/245)
It's implemented following this PR: #262

Refactor(coral): Move responsibility for environment data. 

---

coral/README.md
coral/docs/README.md

This adds a `README` to the root of the `coral/docs` folder, linking to individual articles. It also has the Tip regarding the `alex` docs linting tool.
This `README` is linked under the `Documentation` section in the `README` at the `coral` root. Consequently, all individual links are removed from the root `README`.
As more `docs` articles are added, the root `README` will grow exponentially, which is undesirable. It is also easier to remember adding new articles to a list of link when it is located in the same folder.

docs(coral): Move documentation links to coral/docs/README.md

---

coral/src/app/components/AuthenticationRequiredBoundary.tsx
coral/src/app/main.tsx
coral/src/app/pages/topics/index.tsx
coral/src/app/router.tsx
coral/src/services/api.test.ts
coral/src/services/api.ts

In https://github.com/aiven/klaw/pull/243 we introduces a guard that forced users without active session to authenticate with AngularJS application before being able to view coral routes. That implementation works flawlessly with the initial load, but it does not offer any error handling after the start of the React application. This PR aims to fill the gaps by showing an error dialog for user if any API request returns `401`.  
After we have introduce the base layout, we should include that in the `ErrorBoundary`.
References: https://github.com/aiven/klaw/issues/185

feat(coral): handle 401 API responses with a dialog

---

core/src/main/resources/templates/execAcls.html
core/src/main/resources/templates/execConnectors.html
core/src/main/resources/templates/execSchemas.html
core/src/main/resources/templates/execTopics.html

When a user submits a request, he is not allowed to see the buttons of approving/declining, even though there are validations on the backend.
Resolves: https://github.com/aiven/klaw/issues/290
Why this way
It is only a FE issue, and backend validation is in place already.

Disable approval/declines for users on same reqs

---

coral/src/app/pages/topics/index.test.tsx
coral/src/app/pages/topics/index.tsx
coral/src/services/test-utils/tabbing.tsx

- Add a primary action `Request A New Topic` to the topics index page `PageHeader`
Resolves: #257

feat(coral): Add "Request A New Topic" action in Topics index header

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/components/search/SearchTopics.test.tsx
coral/src/app/features/browse-topics/components/search/SearchTopics.tsx
coral/src/app/pages/topics/index.test.tsx

`BrowseTopics.tsx` did not have test cases for when a user searches a topic through the search input. This PR adds cases for:
- entering a search and clicking the search button
- entering a search and pressing `enter`
- the above two but with keyboard navigation
Resolves: #292
The internal functionality of the search `SearchTopics` is already tested in `SearchTopics.test.tsx`, this is only testing that the correct API call is dispatched and that the table renders the correct data.
- updated the placeholder text which was ambiguous (as well as the visually hidden accessibility label)
- added a missing `await` in another test use `tabNavigateTo`

Add topics search tests

---

coral/src/app/accessibility.module.css
coral/src/app/components/AuthenticationRequiredBoundary.tsx
coral/src/app/components/Pagination.test.tsx
coral/src/app/components/Pagination.tsx
coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.module.css
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.module.css
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.tsx
coral/src/app/main.module.css
coral/src/app/main.tsx

- commit [Improve pagination.](https://github.com/aiven/klaw/pull/312/commits/35028c0a60f8af4ebb7dceb2d5e34a3890bba28f)
Improves usability for screenreader for pagination. Removes unneccessary handling of tabindex. Adds better tests. 
- commit [Fix main nav list.](https://github.com/aiven/klaw/pull/312/commits/ee6d2000fc9dcc0ab198000a1b2997cd245e7932)
semantic error, forgot to wrap one submenu button in a <li> item
- commit [Introduce custom class for a11y improvments for interactive indicators.](https://github.com/aiven/klaw/pull/312/commits/d5bfad7a92d90d0d5b816437028ce2b2abfae8f4)
- adds a global `accessiblity.module.css` where we add styles etc. to improve accessiblity
- some additional styles still need to be set on component level (see main navigation submenu) but that's only …

feat(coral): improve browse topic a11y

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx

https://github.com/aiven/klaw/pull/320 was missing `spyOn` on two test cases

refactor(coral) Add missing spyOn assertions for BrowseTopics tests

---

coral/src/app/accessibility.module.css
coral/src/app/features/browse-topics/components/topic-table/TopicTable.test.tsx
coral/src/app/features/browse-topics/components/topic-table/TopicTable.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.module.css
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.module.css
coral/src/app/main.module.css

- adds more useful name to css vars
- adds styling for text links
- adds links to detail page for topics in topic table
- updates link in main nav to go to "/coral/topics" which is needed to get the right behaviour in the full app
Resolves: #316

refactor(coral):  add links to topic details and coral/topics

---

coral/README.md

- updates link to design system
- makes "running coral inside klaw" vs "running coral in dev mode" more clear
Resolves: #321

docs(coral): Make running Coral inside Klaw vs in dev mode more clear

---

core/pom.xml

Currently maven complains like
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.aiven:klaw:jar:1.2.0
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:exec-maven-plugin @ line 186, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
The reason is that `exec-maven-plugin` declared several times.
It should be declared once and union all the execution

Union exec maven plugin executions

---

core/pom.xml

Current NodeJS version is `18.11.0` which is not LTS.
The first 18.x LTS is `18.12.0` more details are here https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-10-25-version-18120-hydrogen-lts-ruyadorno-and-rafaelgss
Also `18.12.1` is a security release including some security fixes (a list is available at https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2022-11-03-version-18121-hydrogen-lts-juanarbol)

Use LTS NodeJS 18.12.1

---

coral/src/app/pages/not-found/index.test.tsx
coral/src/app/pages/not-found/index.tsx
coral/src/app/router.tsx

- adds `NotFound` page
- use it as component of the `*` fallback route
This was implemented for two reasons:
- we did not have a 404 page, so we redirected everything to `/topics`
- we want to provide a simple way to hide unfinished work from users, and not adding a route to `router` is a simple way to do this for new pages.
- the 404 page also has a link to the index page of the old interface

feature(coral) Add NotFound page, use as fallback in router

---

openapi.yaml

Adds OpenAPI specification for following API endpoints:
- `GET /getEnvsBaseClusterFilteredForTeam`
- `GET /getAdvancedTopicConfigs`
- `POST /createTopics`
Resolves: #353

Add OpenAPI definition for endpoints required for topic request

---

coral/.husky/pre-commit
coral/package.json

- Add `husky` script to run `lint-staged` on `openapi.yaml
- Add a `*.yaml` rule to `lint-staged` config to run `prettier --check` on these files.
Will bail out of commit if file is not formatted according to `prettier` rules:
We want to keep our formatting consistent, and `prettier` can handle `yaml` files, so we should leverage it to ensure consistency.

refactor: add prettier formatting for openapi.yaml

---

coral/docs/mock-api-for-development.md
coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.test.tsx
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-test-helper.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/environment/index.ts
coral/src/domain/team/team-api.msw.ts
coral/src/domain/team/team-api.ts
coral/src/domain/team/team-transformer.ts
coral/src/domain/team/team-types.ts
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-test-helper.ts
coral/src/domain/topic/topic-transformer.test.ts
coral/src/domain/topic/topic-transformer.ts
coral/src/domain/topic/topic-types.ts
coral/types/utils.d.ts

After this only the application types will be exported from `domain`. In order to make the API types more developer friendly, this PR also introduces the following utility types:  `KlawApiResponse` and `KlawApiModel`.

refactor(coral): do not re-export API types from domains

---

coral/types/api.d.ts

Includes types for following endpoints:
- /getEnvsBaseClusterFilteredForTeam
- /getAdvancedTopicConfigs
- /createTopics
No need to re-export the API types as we should prefer `KlawApiResponse` and `KlawApiModel` utility types
Resolves: #354

feat(coral): update API types

---

openapi.yaml

Include documentation for all operations needed for subscription request in our OpenAPI specs.
- `getTopicsOnly`
- `getTopicTeam`
- `getClusterInfoFromEnv`
- `createAcl`
Resolves: #363

feat(coral 🪸): Include "Request new subscription" operations to OpenAPI specification 

---

coral/.husky/pre-commit
coral/package.json

When committing changes to both `openapi.yaml` and some files in `src`, I noticed two problems with the way the `husky` scripts were set up to allow us to run `lint-staged` on `openapi.yaml`:
- one wasteful problem: it makes `lint-staged` run twice on all the patterns defined in `package.json`
- one blocking problem: if one commits `openapi.yaml` changes along with changes in `src` (`ts*` or `css`), an `eslint` check fail, as it cannot resolve the imported modules' paths. This failure happens in the `lint-staged` ran in case there are changes to `openapi.yaml`. I suspect that the fact that we change the working directory with `--cwd="$GIT_ROOT"` in this case results in this behaviour.
This PR removes the additional conditional run of `lint-staged`, and adds the proper pattern for one …

fix(coral): Fix husky lint-staged issues

---

coral/src/domain/acl/acl-api.ts
coral/src/domain/acl/acl-mutations.ts
coral/src/domain/acl/acl-queries.ts
coral/src/domain/acl/acl-types.ts
coral/src/domain/acl/index.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-queries.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/environment/index.ts
coral/src/domain/topic/index.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-queries.ts
coral/src/domain/topic/topic-types.ts
coral/types/api.d.ts
coral/types/utils.d.ts
openapi.yaml

Add the entities in `domain` related to the endpoints documented in https://github.com/aiven/klaw/pull/381
Resolves: #362
- also fixes small issues in the `openapi.yaml` specs for the ACL endpoints ([30d7bdd](https://github.com/aiven/klaw/pull/382/commits/30d7bdd87377c69f48ae3508201bfd9491eb296e), [6217cf7](https://github.com/aiven/klaw/pull/382/commits/6217cf756613781bea3ced72ccd82bb504ed14c4))
- introduces a new generic type util for API requests [ec144ad](https://github.com/aiven/klaw/pull/382/commits/ec144ad4328d9a5233e69c57b2842282f5e98210)

feat(coral) - Add ACL `domain` entities

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaAclService.java
core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/controller/ResourceClientController.java
core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/RegisterUserInfoModel.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/application.properties
core/src/main/resources/static/js/loginSaas.js
core/src/main/resources/static/js/requestAcls.js
core/src/main/resources/swagger_spec.json
core/src/main/resources/templates/modifyUser.html
core/src/main/resources/templates/oauthLogin.html
core/src/main/resources/templates/showUsers.html
core/src/test/java/io/aiven/klaw/ActiveDirectoryAuthorizationIT.java
core/src/test/resources/test-application-rdbms-ad-authorization.properties

When a user is being registered for the first time being a member of AD, his/her roles/teams are being retrieved from the authentication token.
Property : klaw.enable.authorization.ad setting to true will enable this functionality of retrieving role and team attributes.
If this is enabled, and no matching role and team are configured, user is denied registering, and is forced to configure the same in AD and then try login again.
- fixes bug of aclservice constructor
Resolves: #274 
Resolves: #388 
Why this way
A Super user does not have to manually change the role and team of the user, and it is automatically picked up from AD.

Retrieve authorizations/attributes from AD token

---

coral/src/app/components/ComplexNativeSelect.test.tsx
coral/src/app/components/ComplexNativeSelect.tsx
coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx

- Adds a component `ComplexNativeSelect` that implements a `NativeSelect` that can handle Array of Objects as options instead of only strings
- Adds `ComplexNativeSelect` in `Form`
Resolves: #396

coral(feat): Add component to handle NativeSelect with complex options

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx

- Add `MultiInput` component to `Form`
- Remove superfluous `register` of controlled inputs (wrapped in `Controller`) -> this was giving us props conflicts and console warnings, and was actually a no-op (registering a field is used when using the uncontrolled approach)

feat(coral) Add MultiInput component, remove superfluous register

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaTopicService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java
core/src/test/java/io/aiven/klaw/service/TopicSyncControllerServiceTest.java

- Adds unit tests to Klaw-core to ensure that the issue 332 does not re-occur.
- Reformats api response from create topic when topic already exists.
- Integration test that verifies the return message is in the expected returned format for calling APIs.
Resolves: #332 
Why this way
This is a small change that returns the expected API response and includes unit tests to prevent the issue-332 from being re-introduced.

Issue 332 Synchronise Topics

---

core/src/main/java/io/aiven/klaw/controller/SchemaRegstryController.java
core/src/main/resources/static/js/requestAvroSchemaUpload.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/UtilMethods.java

teamname field in SchemaRequest is not required, as when the user submits a new schema request, teamId is retrieved from user who submits it. So it's redundant. field is removed in PR.
Why this way
Field is redundant, and hence removed.
Signed-off-by: muralibasani <muralidhar.basani@aiven.io>

Remove teamname from schemareq

---

core/src/main/java/io/aiven/klaw/auth/KwAuthenticationService.java

This is a very small change.
- The interface `javax.naming.Context` defines constants that are used as keys in order to define environments. Therefore, I would use these constants instead of duplicating them. 
- Modified the method `KwAuthenticationService#rootDnFromDomain`. 
I think it slightly improves readability, although it is a very small change.

Use constants defined in javax.naming.Context

---

README.md
core/Makefile
core/pom.xml
core/src/main/resources/application.properties

during mvn install, node, npm, pnpm are installed and coral assets are copied to the right dir to serve under spring boot application. However the maven plugins are not executed with expected behaviour in different OS like gcp/ubuntu etc. Hence disabling them temporarily.
Why this way
If users would like to view the new interface, they will follow the instructions under coral/readme anyways.
Signed-off-by: muralibasani <muralidhar.basani@aiven.io>

Remove node,pnpm installation plugins

---

coral/src/domain/schema-request/index.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/schema-request/schema-request-types.ts
coral/types/api.d.ts
openapi.yaml

- fixed upper-case typos
- adds global enums for  `RequestStatus` and `TopicRequestTypes`
- updates open API desc for `schemaUpload` based on new swagger_spec
- adds types for requesting a new schema in `/domain`
- adds API calls for creating a new schema and getting the schema registry envs
Resolves: #368

🪸 Add types for "Request new schema" operations

---

core/pom.xml

Fix maven execution plugin on successcodes
Why this way
Ignore the error of execution and continue to build maven

Fix success codes maven exec plugin

---

.gitignore
coral/package.json
coral/pnpm-lock.yaml
coral/vite.config.ts

Adds new script `pnpm run bundle-analyze` that produces a gitignored "stats.html" file which can be used to see bundle contents

feature(coral): Add rollup bundle analyzer

---

cluster-api/Dockerfile
core/Dockerfile

Updates the dockerfiles to pull a java 17 JRE as we have moved to spring-boot 3.0 which requires 17. (11 no longer supported)
Why this way
This JRE was recommended by AdoptOpenJDK which was the previous JRE we used and has now been deprecated.

Update docker java

---

coral/src/app/components/Form.test.tsx
coral/src/services/test-utils/render-form.tsx

Make the `renderForm` function available for use in tests across the project.
https://github.com/aiven/klaw/pull/398 extracted field components which rely on `react-hook-form` context to be rendered in a `fields` folder. Testing them require to wrap them in a `Form`. Using `renderForm` allow this with minimal code.

refactor(coral): Extract renderForm from Form.test.tsx

---

coral/src/app/accessibility.module.css
coral/src/app/components/FileInput.module.css
coral/src/app/components/FileInput.test.tsx
coral/src/app/components/FileInput.tsx
coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx

(also body for commit message!) 
- adds a component `FileInput` that implements a styled and accessible version for `input type="file"`
- adds `FileInput` in `Form` context
- fixes style issue that the * in label text for required inputs was not red
I based my implementation on the approach from [US Gov Design System](https://designsystem.digital.gov/components/file-input/) (and a bit research and testing 👩‍💻):
- the actual functionality is added by the native `input` element. This provides a lot of accessibility already!
- I added a change to the (visually hidden) label: it will include the file name of the uploaded file, so the user gets information about the value for this input and know that did successfully add a file. It mirrors (roughly) how screen readers inform about a text input …

🪸 Add component to upload files 

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/ClusterApiController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/AivenApiService.java
cluster-api/src/main/resources/application.properties
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/AivenApiServiceTest.java
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/static/js/requestAcls.js
core/src/main/resources/swagger_spec.json
core/src/main/resources/templates/requestAcls.html
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java

Currently in a subscription request on an Aiven environment, user is allowed to enter a service account. He is not sure which exist and which don't. 
This Pr, retrieves the service accounts and displays in the Acl request form, and user can choose which one to use or create a new one.
Resolves: #431 
Why this way
User does not have to login to see the service accounts, rather, view in klaw and request a subscription.

Display service accounts for a new subscription on Aiven env

---

coral/jest.config.ts
coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
coral/src/app/features/topics/request/schemas/topic-request-form.ts
coral/src/app/main.tsx
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-transformer.test.ts
coral/src/domain/topic/topic-transformer.ts
coral/src/domain/topic/topic-types.ts
coral/src/services/configure-monaco-editor.ts
coral/test-setup/mock-monaco-editor.tsx
coral/vite.config.ts

Includes [Monaco Editor](https://microsoft.github.io/monaco-editor/) as a new dependency. The form field is type `z.string()` in order keep the type same as Monaco Editor. As a result, we would need to run `JSON.parse(...)` in order to pass the advanced config. The Monaco editor should take care of the `json` validation out of the box. 
UX candy:
- auto suggest for known advanced configuration keys
- help tooltip when a valid property name is hovered
- red squiggly and error msg on hover for unknown key
Missing nice-to-haves:
- Monaco editor lazy loaded only when needed. Currently it is loaded for each page. Not the end of the world due browser caching, but not optimal
- Advanced config field value validation. Preferably the API would return a JSON Schema to describe the schemas for each …

feat(coral): implement advanced topic config request as JSON editor 

---

coral/src/services/test-utils/render-with-wrappers.tsx

(for commit description)
- Make return values from `render` available from `customRender` (notably `rerender`)
- Remove `console.error` default case, return vanilla `render` instead
- Improve type safety of the `renderWith` argument to keep the functionality lost by removing `console.error`: it is now not optional (using `customRender` without custom behaviour is probably not a thing), and TS should complain about non-existing option.
https://github.com/aiven/klaw/pull/398 needs to call `rerender` to test some behaviour, and `customRender` did not allow to access the method.

refactor(coral): Refactor render-with-wrapper

---

core/src/main/java/io/aiven/klaw/model/TopicRequestModel.java
core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
core/src/main/resources/static/js/requestTopics.js
core/src/test/java/io/aiven/klaw/TopicRequestValidatorImplIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java

When submitting a new topic request, teamname is not required, as it can be retrieved from the user details of submitting request. 
So the field is made optional.
Even when apis are exposed, this should work, as teamname should be derived from logged in user.
Why this way
teamname is not required when submitting a request.

Teamname optional in topic request

---

coral/src/app/features/topics/request/TopicRequest.test.tsx

Updates tests for `TopicRequest` to be handled in querying for async rendered elements more explicitly. This should - I hope - reduce the flakiness since the async queries are now more granular (e.g. waiting until topic partitions has changed from an input to an select before checking display value).

refactor(coral): Update topic request tests.

---

coral/vite.config.ts

When the build was run with 'NODE_ENV=production' it resulted in an require error. The monaco editor bundle has a requirement to JSX as the monaco editor we have in the project already has bindings to React.

fix(coral): bundle monaco editor together with rest of vendor

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/request/components/SelectOrNumberInput.tsx
coral/src/app/features/topics/request/schemas/topic-request-form.ts
coral/src/app/features/topics/request/utils.test.ts
coral/src/app/features/topics/request/utils.ts
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.test.ts
coral/src/domain/topic/topic-api.ts
coral/src/services/mutation-utils.ts
coral/types/api.d.ts
openapi.yaml

This PR demonstrates how to change state on server. This PR still includes MSW API mocks as the overall functionality is easier to verify. After this PR is merged, we can have a final acceptance testing @muralibasani against the real API.

feature(coral): implement topic request with mocks

---

coral/src/app/accessibility.module.css
coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap

https://github.com/aiven/klaw/issues/448
- updates the `formSchema` objects used in tests. They mostly used `name="name"`, this covered a bug in error handling. 
- update `parseFieldErrorMessage` in `Form` to use `errors[name]` (e.g. errors[myFieldName]`) instead of `errors.name`
- remove usage of `const error = get(errors, name)?.message as string;` that now is not needed anymore
- updated `MultiInput` in `Form` to show error messages in some cases: 
-  error is shown and field marked as invalid when user wants to submit an empty MultiInput that is required 
- error is shown when user adds something to MultiInput that may not be valid and tabs out
- error is shown (for an required MI) when user adds something and removes it again 
Resolves: #448

fix(coral): Fix broken error message handling in some Form elements

---

.github/workflows/coral-pr-pipeline.yml
coral/package.json
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/services/test-utils/mock-intersection-observer.ts

```
- refactor mock for intersection observer
- refactor BrowseTopic tests
- replace msw mocks with jest mocks
- update test script used in pipeline
```
- I added a script `test-ci` in our `package.json` 
- This script is used in the github pipeline now
- currently, it only added the `--ci` flag ([docu](https://jestjs.io/docs/cli#--ci))
I had one try run with `run-in-band` which runs the test in parallel, which can help in CI environments. One of the flaky tests failed right away, so it does not seem to be helping us (with our current size of test suite). 
As far as I read up, github offers 2 workers. The default in jest is to run on `all available cores - 1`, so setting `max-workers=50%` would yield no change.  
I've added a comment in the code for this change and the source for where I …

refactor(coral): Refactor flaky BrowseTopics test

---

coral/README.md
coral/src/app/features/topics/browse/components/topic-table/TopicTable.module.css
coral/src/app/layout/main-navigation/MainNavigationLink.module.css
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.module.css
coral/src/app/layout/skip-link/SkipLink.module.css

- uses camelCase in all CSS module classes 
- except in `accessibility.module.css` since it's a globally available class that is used as string
- add short section in README about use of module CSS
Resolves: #436

refactor(coral): Make css class names consistent

---

coral/package.json

`start` is (besides `dev`) a pretty common script for running development env. By adding the alias we can prevent people from running the familiar but wrong script and getting confused before checking our package.json 
(Me 😳 I am these "people")

refactor(coral) Add "start" as alias for "pnpm dev".

---

core/pom.xml

Signed-off-by: Callaert Anthony <callaertanthony@gmail.com>
Starting `klaw-core` with postgresql as database throws an error.
Configuration:
```
spring.datasource.url=jdbc:postgresql://localhost:5432/klaw?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
spring.datasource.username=kafkauser
spring.datasource.password=klaw
spring.datasource.driver.class=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL92Dialect
```
```
Caused by: java.lang.RuntimeException: Failed to load driver class org.postgresql.Driver in either of HikariConfig class loader or Thread context classloader
```
This is because the postgresql dependancy is not present and driver cannot be loaded.
It's possible to add few test to ensure no regression in the …

chore: add postgres dependency

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceRegisterSchemaTest.java
core/src/main/java/io/aiven/klaw/model/cluster/ClusterSchemaRequest.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/swagger_spec.json

This change will first attempt to get the schema compatibility at the subject (topic level) , if that fails it will then get the subject at the Global level. It will then set the global compatibility to NONE on a force change change the Schema and then revert the global compatibility to the previous type.
Why this way
This allows users to force a schema through on a topic in must need situations.

Fallback to Global Schema when Subject not set

---

pom.xml

spring-boot-starter-parent upgrade from 3.0.1 to 3.0.2
Why this way

Spring boot starter upgrade

---

cluster-api/pom.xml
core/pom.xml
pom.xml

Same switch from `http` to `https` as done for maven at https://issues.apache.org/jira/browse/MNG-6778
Why this way

Use https for schemaLocation

---

.github/workflows/maven.yml

Make ci check 2 JDKs: one LTS (17) and the latest available (19)
to be able to detect issues earlier to simplify support for next LTS
Why this way

Add jdk19 to ci

---

core/src/main/resources/templates/requestTopics.html

If user has `klaw.coral.enabled=true` show user a banner with link to topic request in Coral.
https://user-images.githubusercontent.com/1408173/214078637-3b5c47dc-1b5e-4af6-8a71-2e7c0e8c1269.mov

feature(coral): Add experimental UI banner for topic request

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-consumer.ts
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-producer.ts
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts
coral/src/app/features/topics/acl-request/schemas/validation.ts

Following on acceptance test with @muralibasani, added more validation to the forms:
- allowed characters for transactional ID and consumer group
- allowed character length for transactional ID and consumer group
- allowed amount of IPs and Principal items in IPs and Principal fields
https://user-images.githubusercontent.com/20607294/214543947-7c38fd68-f409-46b1-a61d-8472e5c191aa.mov
https://user-images.githubusercontent.com/20607294/214543997-f239c89a-5752-4794-9a1b-e0b3c817b771.mov

feat(coral): Improve validation in forms

---

coral/.eslintrc.cjs
coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/FileInput.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx

Add rule to make sure we always import
`import thing from 'lodash/thing'`
instead of
`import { thing } from 'lodash'`
Resolves: #429

coral(style): Add linting rule for lodash imports

---

coral/src/app/components/FileInput.tsx

With a short button text, the File input button overlay was not covering the native UI.
Small adjustments to the styles lead to this result:

fix(coral): Fix FileInput button overlay width

---

core/src/main/java/io/aiven/klaw/controller/UtilController.java
core/src/main/java/io/aiven/klaw/model/SSODetails.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/application.properties
core/src/main/resources/swagger_spec.json
core/src/main/resources/templates/oauthLogin.html

This changes the returned SSO Providers into a standard object, this configuration is pulled directly from the application.properties file.
This object is then iterated over in the oauthLogin.html page and gives all configured providers as options to select for authentication.
Why this way
This allows any SSO OAuth provider including internal and custom providers to be used for authentication.
It does require an update to the documentation aswell.
#471 is resolved from this update.

Automatically add additional SSO Providers once configured

---

coral/src/app/components/PreviewBanner.tsx

Icon resized with browser size, see screenshot:
- wrap icon in Typography component to get font sizing inherited
- add fixed margin to Icon in order to equalize line-height and align icon properly with the font at top
- use `Typography.SmallText` since variant body-small is deprecated
Resolves: #482

coral(fix): Fix Icon in PreviewBanner resizes with browser

---

coral/src/domain/topic/topic-api.ts
coral/types/api.d.ts
openapi.yaml

https://github.com/aiven/klaw/pull/476 introduces a new param to the `/getTopicsOnly` endpoint to be able to pass an environment ID (or `"ALL"`), which allows to fetch only the topics that are available in the given environment.
This PR reflect these changes in API in the `coral` frontend:
- update the `openapi.yaml`
- generates the TS types
- updates `topic-api.ts` 
[feat(coral): ACL Request Form - Only load the topic names that belong to the selected topic](https://github.com/aiven/klaw/issues/483)

feat(coral): Update API schema, types, handler for /getTopicsOnly

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/ComplexNativeSelect.tsx
coral/src/app/components/FileInput.tsx
coral/src/app/components/Form.test.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
coral/src/app/main.module.css

Bump `aquarium` version.
Critical fix in this update: `MultiInput` does not submit form when pressing `Enter`
Other necessary change:
- `tsc` run in pre-commit hook flagged the `fontWeight` prop on `Typography.Caption` to be inexistent, so was removed
```
src/app/components/FileInput.tsx(48,29): error TS2322: Type '{ children: (string | false | Element | undefined)[]; fontWeight: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
Property 'fontWeight' does not exist on type 'IntrinsicAttributes & Props'.
```
- typography tokens updates required the download of the proper font variants in `main.module.css`
The update to `NativeSelect` requires the removal of our custom implementation of placeholder behaviour: https://github.com/aiven/klaw/issues/495

chore(coral): Update aquarium to 1.3.0

---

core/src/main/java/io/aiven/klaw/auth/KwAuthenticationSuccessHandler.java
core/src/main/java/io/aiven/klaw/config/ConfigUtils.java
core/src/main/java/io/aiven/klaw/config/SecurityConfigSSO.java
core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/auth/KwAuthenticationSuccessHandlerTest.java

- When provider routes user back to application, user is sent a url /{{provider}} which is not a valid one. Now user is sent to root page.
- Sometimes new users are directed form providers, full names consist of "," which are not accepted in Klaw during registration. They are replaced with empty strings now. 
Resolves: #493
Why this way
to continue with smooth redirection of user

Full name fix, provider route url fix

---

core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/resources/static/js/requestAvroSchemaUpload.js
core/src/main/resources/static/js/requestTopics.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/UiConfigControllerServiceTest.java

This change ensures that the environments that are selectable for a 'Request Topic' or 'My Schema Request' are filtered to only show the topics defined in the tenant model under requestTopicsEnvironmentsList and requestSchemaEnvironmentsList.
Why this way
This parses out any data that should not be available as an option to the user and resolves issue #491 so that superadmin has the ability to force users to use the promotion capabilities to promote topics and schemas to higher environments.

Limit Env dropdown based on tenant config

---

coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/router.tsx
core/src/main/resources/templates/requestAcls.html

- render ACL form at route `/topic/:topicName/subscribe` as per https://github.com/aiven/klaw/issues/452
- add CTA in Angular UI 
I also wanted to implement the `reuqest/acl` route, but there are issues to be solved, as currently the forms are very reliant on having a `topicname` in the route params. The full resoltution of https://github.com/aiven/klaw/issues/452 should be a separate PR.

feat(coral): Update ACL request route, add Angular CTA

---

coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/features/topics/schema-request/schemas/topic-schema-request-form.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/schema-request/schema-request-types.ts

- removes the api mocks from `TopicRequestSchema`
- adds precise types for `SchemaRequest` and `SchemaRequestPayload` to be used in the api call and make typing stricter there
- adds stricter typing to the useMutation hook for creating a new schema
Resolves: #372

feat(coral): connect "Request new schema" form with api data

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

Consumer group is not relevant if the environment is an Aiven cluster:
- make default value for `consumergroup` field `-na-`
- only render the Consumer group field id the cluster is NOT an Aiven cluster

fix(coral): ACL request form: do not show Consumer Group field if Environment is Aiven cluster

---

coral/src/services/api.test.ts
coral/src/services/api.ts
coral/src/services/mutation-utils.ts
coral/src/services/type-utils.ts

Klaw currently does not return ERRORs from the API but always a 200.
An error is always following this pattern:
```
{
status: null,
timestamp: null,
message: null,
debugMessage: null,
result: "Failure. <SOME MORE TEXT>",
data: null,
};
```
To provide error messages for the user, we added `checkForFailureHiddenAsSuccess` 
as a temporary fix.

feat(coral): Add error handling in frontend

---

coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts

The `creatAcl` does not accept `acl_ssl` values that are < 3 characters:
- add `zod` schema validation to forbid `acl_ssl` values < 3 characters
Noticed that we had `keepPreviousData: false` in the `clusterInfo` query. This would cause `clusterInfo` to be undefined when the form re-render because of a server error, making it impossible to interact with the `IP / SSL` checkboxes and fields:
- changed it to be `keepPreviousData: true`

fix(coral): Add acl_ssl item length validation

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx

As we are navigating the user back to Angular application, we can not use React Router for the operation: fix redirect after topic request

fix(coral): fix redirect after topic request

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

The behaviour of the current redirect (basically a `go back to previous page` action) is not desirable currently. So we redirect to the same page as the angular app (My request page filtered by `created`)

fix(coral): ACL request form - Redirect to My requests page on success

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/utils/ClusterApiUtils.java

pem cert support for trust stores
Resolves: #181 
Why this way
Support for both key and trust stores

Pem support for trust store cert

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.test.tsx
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

If Environment is an Aiven cluster:
- only allow `LITERAL` pattern type
- do not render Transational ID field and do not send it as part of the request
https://user-images.githubusercontent.com/20607294/215801877-927fa1d8-a1d7-4d09-abc6-557525cda2ad.mov

fix(coral): ACL request form - If Aiven cluster, only LITERAL allowed, no Transactional ID field

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameField.test.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/acl-request/queries/useEnvironmentTopics.tsx

- only topics that are available in the scope of the selected environment will be part of the Topic name field's dropdown
- if no environment is selected, Topic name field is disabled
https://user-images.githubusercontent.com/20607294/215762737-63c77613-f77a-40de-87ee-812bbd46ac9d.mov
https://user-images.githubusercontent.com/20607294/215763091-701c8e82-1a03-479b-aeb5-9e4b3aa85ec9.mov
- We create a query for each environment and stash the results in state: https://github.com/aiven/klaw/pull/518/files#diff-068b6b4530a8332b187652e53e151f81552bacea92f0f4c2b9dcab507c4df59eR72-R87
- We pick the relevant data and pass it down to the forms https://github.com/aiven/klaw/pull/518/files#diff-068b6b4530a8332b187652e53e151f81552bacea92f0f4c2b9dcab507c4df59eR150-R153
I don't think it's very nice to …

feat(coral): Only load topic names that are available in given env in topic name field

---

core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/error/KlawExceptionHandler.java
core/src/main/java/io/aiven/klaw/error/KlawNotAuthorizedException.java
core/src/main/java/io/aiven/klaw/model/TopicCreateRequestModel.java
core/src/main/java/io/aiven/klaw/model/TopicRequestModel.java
core/src/main/java/io/aiven/klaw/model/TopicUpdateRequestModel.java
core/src/main/java/io/aiven/klaw/model/enums/PermissionType.java
core/src/main/java/io/aiven/klaw/perf/CreateBulkTests.java
core/src/main/java/io/aiven/klaw/service/DefaultDataService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
core/src/main/resources/static/js/requestTopics.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/TopicRequestValidatorImplIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java

Fix: Allows the creation of an edit topic config request and ensure it is available on all environments.
Resolves issue #503 which due to validation the edit topic will not be created.
It also resolves an issue where the edit button was not available on all environments if the requestTopicsEnvironmentsList is set to a subset of environments.
Why this way
Maximizes code re-use and minimizes changes to the API to maintain stability during the Front End coral updates.

Fix: Create Edit Topic Requests

---

.github/workflows/maven.yml
core/pom.xml
core/src/main/java/io/aiven/klaw/uglify/UglifyFiles.java
core/src/main/resources/application.properties
core/src/test/resources/test-application-rdbms-ad-authorization.properties
core/src/test/resources/test-application-rdbms-sso-ad.properties
core/src/test/resources/test-application-rdbms-windows-ad.properties
core/src/test/resources/test-application-rdbms.properties
core/src/test/resources/test-application-rdbms1.properties

Auto updates the version number from the project version in property files. 
Also enables uglify from the parent directory if that is where the maven build is being run from.
Why this way
Reduces the need on releases to manually update files and have some files forgotten.
Also properly uglifies the files.
Updating a project now only requires one command from the klaw parent project and all version numbers will be updated.
example: mvn versions:set -DnewVersion=2.0.1

Version Numbers and Uglify fixes

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx

Consumer group value should be:
- Aiven cluster: `"-na-"`
- not Aiven cluster: `""`
To achieve this:
- set default value of `consumergroup` to `""`
- when an environment is selected:
- if field is hidden (Aiven cluster), set its value to `"-na-"`
- if field is rendered (noy Aiven cluster). set its value to `""`
https://user-images.githubusercontent.com/20607294/216052807-9b20d294-b194-4820-8b06-75dea3bf4aa0.mov

fix(coral): Make consumergroup value -na- only for Aiven clusters

---

coral/src/app/pages/topics/acl-request.tsx

Path should be `requestAcls?topicname=${topicName}` (notice the `s`)
It was `requestAcl?topicName=${topicName}`

fix(coral): Fix typo in PreviewBanner url

---

core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java

This change adds three optional paramters to the getCreatedAclRequest.
1) topic the topicName
2) environment DEV/TST/UAT/PRD
3) AclType PRODUCER/CONSuMER
Why this way
The use of the example repo allows for further extension without writing custom queries for a multitude of options.
It also allows a reuse of existing code without the addition of a lot of new code.

Add Parameter Options to getCreatedAclRequests

---

LICENSE
mvnw
mvnw.cmd
openapi.yaml
pom.xml

replace `http` to `https` for apache license
Why this way

Use https in apache license url

---

coral/jest.config.ts
coral/src/app/hooks/useFeatureFlag.ts
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.test.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.tsx
coral/src/app/main.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/test-setup/setup-files-after-env.ts
coral/vite.config.ts

(can also be the commit body)
- add `Routes` enum for a bit more type safety
- add `active` props to all links in coral so they are styled and marked correctly based on route
- remove general acl request feature flag and link (dev need only)
- remove `useRouter` prop from `MainNavigationLink`, component determines which link to dependent wether the path is part of `Routes`

refactor(coral): Update main navigation to show correct active links

---

coral/src/domain/acl/acl-api.ts
coral/src/domain/acl/acl-types.ts
coral/types/api.d.ts
coral/types/utils.d.ts
openapi.yaml

- add openapi documentation
- add acl-api function
- ad acl-types for endpoint
- added a `KlawApiRequestQueryParameters` util to pick query params types from the generated types, like for request payloads.
Resolves: #559

feat(coral): Add /getAclRequestsForApprover endpoint

---

coral/src/domain/acl/acl-api.ts
coral/src/services/api.ts
coral/types/api.d.ts
openapi.yaml

- add openapi documentation
- add acl-api function
- introduces `KlawApiRequestQueryParameters` util to pick query params from the generated types
- modidy `api.post` in `api.ts` to be able to handle `POST` request without payloads
Resolves: #561

feat(coral): add `/execAclRequest` endpoint

---

coral/jest.config.ts
coral/src/app/components/FileInput.test.tsx
coral/src/app/components/Pagination.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/components/search/SearchTopics.test.tsx
coral/src/app/layout/Layout.test.tsx
coral/src/app/layout/header/Header.test.tsx
coral/src/app/layout/header/HeaderMenuLink.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.test.tsx
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx
coral/src/app/pages/topics/schema-request.test.tsx
coral/test-setup/mock-ds-icon-component.tsx

- adds a mock the `Icon` component in `setupAfterEnv`, so we don't have to mock it out in component tests to reduce clutter in test output (e.g. `screen.debug()` or in output for failing tests. 
- the mock enables us to still assert that the icon is rendered (based on test-id) and even if the right icon is rendered -> there should not really be a need for that, but there may be edge cases where it's valuable to be able to do it. 
- removes mocks in test files and updates test where needed
Resolves: #282

refactor(coral): Add general mock for DS Icon component

---

coral/src/app/components/ComplexNativeSelect.test.tsx
coral/src/app/components/ComplexNativeSelect.tsx
coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

`NativeSelect` implemented new behaviour in the last DS release how to show accessible placeholder. This PR removes the custom implementations we did to get an accessible placeholder on our site now. 
Background: The native `placeholder` for `select` does nothing, it does not show up or is useful for assistive technology. The implementation in DS adds this. Since it's not based on native behaviour, when using `NativeSelect` as a base component in `Form` (or `ComplexNativeSelect`) we have to account for that.
- removing custom placeholder implementation in  `ComplexNativeSelect` and making sure we get the wanted behaviour for required/optional select (mainly making sure we do an `onBlur` with `undefined` when needed. 
- adapt usage in `Form`: 
-  make `NativeSelect` controlled, otherwise …

refactor(coral): Remove custom implementation for placeholder NativeSelect

---

coral/src/app/components/Modal.module.css
coral/src/app/components/Modal.test.tsx
coral/src/app/components/Modal.tsx

- We now have multiple user journeys where user can cancel or submit forms and get redirected to a different page without warning / information why this is happening. 
- The `Modal` from Aquarium design system uses `react-aria`, which currently [does not work](https://github.com/adobe/react-spectrum/issues/779#issuecomment-1353734729) in React18 `StrictMode`.
- I added a temporary implementation to create a better usability for our users, especially since we're going to add more forms now. This gives us time to see if the mentioned issue is getting fixed or to decide how we want to continue with this. 
- uses `dialog` and `aria-modal` to support assistive technology
- `setFocus` in `Modal` is removing focus and focusability from `#root` while setting focus on the `h1` element (it's …

feat(coral): Add temporary Modal component

---

core/src/main/java/io/aiven/klaw/model/EnvModel.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/resources/static/js/envs.js
core/src/main/resources/static/js/modifyEnvs.js
core/src/main/resources/templates/modifyEnv.html
core/src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java

- Currently there is a restriction on the size of env names, which is now changed to 10
- Update done all new and update envs, for kafka, schema and connect
Resolves: #563
Why this way
There is no change in db. Only code validations are updated.

Env name size increment from 3 to 10

---

coral/src/app/components/ComplexNativeSelect.tsx
coral/src/app/components/FileInput.tsx
coral/src/domain/acl/acl-types.ts
coral/src/domain/schema-request/schema-request-types.ts
coral/src/services/api.ts
coral/types/utils.d.ts

- Adds type helper `Prettify`
- Adds changes to types exposed for `acl` and `schema-request` as showcase (and because I felt it's most useful for these)
Found this neat little util on [Twitter ](https://twitter.com/mattpocockuk/status/1622730173446557697) 😅  and it solves an annoyance I had quite often already.

Refactor(coral): Add type helper Prettify

---

core/src/main/java/io/aiven/klaw/controller/SchemaRegstryController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/service/SchemaRegstryControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/static/js/execSchemas.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/controller/SchemaRegstryControllerTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SchemaRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java

This change adds topic, env and search parameters available on the GetCreatedSchemaRequests API.
It also renames the API to getSchemaRequestsForApproval to match other Approval endpoints.
Resolves: #586 
Why this way
This supports the React UI and its new design to allow filtering and pagination.
It also updates the requests to follow the same pattern as previously updated requests to make them consistent and uniform in their implementation.

Extend schema for approval api with filter parameters

---

coral/src/app/features/approvals/SkeletonTable.tsx
coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/domain/acl/acl-api.ts
coral/src/domain/acl/acl-transformer.ts
coral/src/domain/acl/acl-types.ts

https://user-images.githubusercontent.com/20607294/218109160-c3da654f-a304-4dfc-807b-9f6b913e0ef9.mov
- add content to `AclApprovals` component: `DataTable` populated with data from `getAclRequestsForApprover`, `Pagination` component (not from `aquarium`, cf "Follow-ups")
- to be able to implement this, added `acl-transformer` to parse the data from the API in a `Paginated` format.
- implement sync between pagination and search parameters with `?page={number}` search param
- add data filters
- add approve and delete modal behaviour on relevant buttons (cf https://github.com/aiven/klaw/issues/587)
- `Pagination` from `aquarium has a bug that prevents gracefully syncing and pagination and search parameters, so will be implemented once it is fixed
- When there are several columns without …

feat(coral): Add DataTable and Pagination for ACL approval page

---

core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/static/js/execConnectors.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java

This change renames the endpoint inline with how the other approvers endpoints have been renamed.
It also adds the ability to search by environment and by a wildcard topic search name.
Resolves: #592 
Why this way
This follows the same pattern as the other updates we have made and make them all consistent with each other.

Adds parameter options for endpoint and rename the ednpoint

---

coral/src/app/components/Modal.test.tsx
coral/src/app/components/Modal.tsx

- removes attribute when component unmounts
- adds a regression test 
Resolves: #603

fix(coral): Remove inert attribute when Modal component unmounts

---

core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/TopicRequestModel.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbcTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java

Adds filter parameters to My Topic Requests 
Add isEditable and isDeleteable parameters 
Enforcement checks to only allow a request owner delete their own request.
Resolves: #600 
Why this way

Extend Get Topics Requests API to use filter parameters

---

coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/domain/topic/index.ts
coral/src/domain/topic/topic-types.ts

- adds the "Approve schema request page" ui only with:
- adds table, filter elements, search element and pagination
- hard coded data for requests
- placeholder values for selects
- no functionality behind any buttons or pagination 
- adds temp type (updated API def for changes endpoint will come later)
- there were api endpoints added already, but they were updated in the meantime, so will update that and connect them in a later PR
- I added types as they are needed right now - when the api endpoints change, already added types and transformer will change, but I'll do that in the other PR
Resolves: #608

feat(coral): add data table approve topics request UI only

---

core/src/main/java/io/aiven/klaw/controller/SchemaRegstryController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/SchemaRequestModel.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegstryControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/controller/SchemaRegstryControllerTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbcTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SchemaRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java

Adds Filter parameters required for new React UIs
Adds isEditable and isDeletable to responses
Enforces only request creator can delete their own request Also only returns true if the status of the ticket is created.
Resolves: #601 
Why this way

Issue 601 extend get schema requests with filters

---

coral/src/app/components/Modal.module.css
coral/src/app/components/Modal.test.tsx
coral/src/app/components/Modal.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.tsx
coral/src/app/features/approvals/components/RequestRejectModal.test.tsx
coral/src/app/features/approvals/components/RequestRejectModal.tsx
coral/src/app/layout/Layout.tsx

For merge message
```
- add `RequestDetailsModal` component
- add `RequestDeclineModal` component
- add `isLoading` and `disabled` props to `Modal` component
```
This enables sharing this Modal UI across approval tables :
https://user-images.githubusercontent.com/20607294/218511007-73439f20-374e-4d97-adba-08974de7d159.mov
Resolves: #587
Use these new modal components in a generic `RequestApprovalTable` component: https://github.com/aiven/klaw/issues/617

feat(coral): Add RequestDetailsModal and RequestDeclineModal

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/domain/acl/acl-api.ts

- use `ApprovalsLayout` for `AclApprovals` component
- add placeholder filters
- fix typo in API path for `reject` endpoint
- replace instances of `cluster` by `environment` in ACL approval context

feat(coral):  use ApprovalsLayout for AclApprovals component

---

coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.test.tsx
coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/pages/topics/index.test.tsx

- Removes mention of "cluster" from UI. User always interact with Klaw's environments. 
- Uses consistently `Environment` and "--- Please select ---" as placeholder in forms for select
Resolves: #541

fix(coral): Align naming in form/table views

---

core/src/main/java/io/aiven/klaw/model/KafkaConnectorRequestModel.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/resources/swagger_spec.json

Adds isEditable and isDeletable to KafkaConnectorRequests which is the last request to get this update.
This conforms the KafkaConnect response to be the same as all the other request types and allows us to 
Resolves: #596 
Why this way

KafkaConnector Requests indicate if they are editable or deletable in response

---

coral/src/app/components/Dialog.test.tsx
coral/src/app/components/Dialog.tsx
coral/src/app/components/Modal.test.tsx
coral/src/app/components/Modal.tsx

Adds a `Dialog` component with a similar API to the one in DS so we can replace it smoothly later. 
The additional tests in `Modal` are a bit sparse, since the new props are only to be used in `<Dialog />` and `<Dialog />` itself is tested for its rendered output. Since both components are temp implementations, I felt it's ok to cover it like that instead of more in depth. It's very unlikely that we will suddenly start to use a `<Modal />` with a dialog-related prop in the wild 😅  
Resolves: #615

feat(coral): Add Dialog component.

---

coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/domain/requests.ts
coral/src/domain/topic/index.ts
coral/src/domain/topic/topic-api.msw.ts
coral/src/domain/topic/topic-api.test.ts
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-test-helper.ts
coral/src/domain/topic/topic-transformer.test.ts
coral/src/domain/topic/topic-transformer.ts
coral/src/domain/topic/topic-types.ts
coral/types/api.d.ts
openapi.yaml

The api endpoint changed from `getCreatedTopicRequests` to `getTopicRequestsForApprover`. 
This MR: 
(also commit body)
- removes `getCreatedTopicRequests` from api definition and types
- adds general enums for `RequestType` and `RequestStatus` in api definition and types
- adds `getTopicRequestsForApprover` in api definition and types
- updates types and api function related to topic requests 
Resolves: #607

feat(coral): Update api definition, types and functions for `getTopicRequestsForApprover`

---

coral/src/app/components/Modal.module.css
coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/components/DetailsModalContent.test.tsx
coral/src/app/features/approvals/acls/components/DetailsModalContent.tsx
coral/types/api.d.ts
openapi.yaml

https://user-images.githubusercontent.com/20607294/219307114-5347d68a-0734-478f-b5aa-dc434566fd77.mov
- Add modals showing when clicking SHow details or Reject quick action
- Add business logic to handle approval and rejection of ACL requests
- Fix ACL request definition in `openapi.yaml` (was missing `requestingTeamName` property)
- Make `max-height` of `Modal` bigger to avoid scrolling in `Modal`
https://github.com/aiven/klaw/issues/633
Resolves: #621

feat(coral): Add approve/reject ACL subcription request behaviour

---

core/src/main/java/io/aiven/klaw/model/TeamModel.java
core/src/main/java/io/aiven/klaw/model/UserInfoModel.java
core/src/test/java/io/aiven/klaw/model/TeamModelTest.java
core/src/test/java/io/aiven/klaw/model/UserInfoModelTest.java

Issue 577 team contact too strict accents and international dialing numbers.
This change caters for most accents, umlauts as well as international dialing codes.
Resolves: #577 
Why this way
This while not an exhaustive fix allows for more inclusive development and usage of Klaw allowing people to correctly spell their names more accurately.

Expand Team contact and Full Name Validation

---

coral/README.md
coral/package.json

- `pnpm:devPreinstall` script fails on running build on Windows 10. 
(it runs before every `pnpm install`)
- removes `pnpm:devPreinstall` 
- add custom script for adding directory for pre-commit hooks
- adds info for that in setup for development in corals README
Resolves: 🐛 #641

fix: Remove `pnpm:devPreinstall` in favour for custom script

---

docker-scripts/README.md

Updates a README file to expand on how to utilize docker and Klaw.
Why this way
This provides a nice utility for those who want to test or demo or trial Klaw with minimal commitment.

Add additional documentation on how to utliise dockerized Klaw

---

coral/src/app/layout/Layout.tsx
coral/src/app/main.module.css

- sets the global font-size to 16px to match DS instead of console so styles for DS are applied correctly.
The navigation links now are 16px (default), but in console they are 14px (default from console). Since we're not integrated in console yet, we're not implementing overwrites for that now. 
Resolves: #620

style(coral): Consistent font-sizes to console

---

coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/domain/acl/acl-types.ts
coral/src/domain/schema-request/index.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/schema-request/schema-request-transformer.test.ts
coral/src/domain/schema-request/schema-request-transformer.ts
coral/src/domain/schema-request/schema-request-types.ts
coral/src/domain/topic/topic-types.ts
coral/types/api.d.ts
coral/types/utils.d.ts
openapi.yaml

- adds api definition for `/getSchemaRequestsForApprover.`
- updates api definition for `SchemaRequest` (there was an update)
- adds types to `/domain`
- adds api call with transformer to `/domain`
Resolves: #639

feat(coral): Add api definition and types for getSchemaRequestsForApprover

---

docker-scripts/README.md
docker-scripts/docker-compose-klaw.yaml

Adds a volume and attaches it to the cluster-api image
Adds information on finding the exact mount location for your containers.
Adds information on how to switch over to the release versions on dockerhub.
Why this way
Adding additional information is always helpful for customers.

Docker readme compose update

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/components/ApprovalsLayout.test.tsx
coral/src/app/features/approvals/components/ApprovalsLayout.tsx

All approvals table can reuse the UI for loading and error-cases for fetching their requests 
- extends ApprovalsLayout with loading and error UI
- uses updated ApprovalsLayout component in ACL approvals

feat(coral): Extend ApprovalLayout

---

coral/src/app/components/Dialog.test.tsx
coral/src/app/components/Dialog.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/forms/SkeletonForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/browse/BrowseTopics.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/request/schemas/topic-request-form.ts
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

- adds a "Cancel request" flow to
-  Request a new schema
-  Request a new topic        
-  Request a new ACL
- makes naming for buttons consistent in forms
Resolves: #582
Since the workflows and skeleton of the forms are very similar, I thought about adding a layout component that may also take care of the dialogs (will add a success next). Since they are using `<Form />` and all it's less straightforward than I hoped, so I added the dialogs like this and will do the same for success handlings. It's a bit redundant, but way faster for now.

feat(coral): add cancel workflow to "Request new x" workflows

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.tsx

- do not render quick actions in rows for request where `requestStatus` is not `CREATED`
- add `disabledActiouns` prop to `RequestDetailsModal` to forbid accepting/rejecting a request  where `requestStatus` is not `CREATED` 
https://user-images.githubusercontent.com/20607294/220363203-3e009693-4593-4d31-8bdc-5ac48f0a25f5.mov
Resolves: #660

fix(coral): Do not allow approve/reject when requestStatus is not CREATED

---

core/src/main/resources/templates/addUser.html
core/src/main/resources/templates/modifyUser.html
core/src/main/resources/templates/myProfile.html
core/src/main/resources/templates/showUsers.html

Updates the label from 'Can switch Teams' to 'Enable switching Teams'  in user profile pages
Why this way

Label changes for switch teams

---

coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/DetailsModalContent.test.tsx
coral/src/app/features/approvals/topics/components/DetailsModalContent.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

- Add View details modal for Topic request approval table
- Unify some styles to keep consistent with ACL approval table
https://user-images.githubusercontent.com/20607294/220571014-a90dda15-c83a-44e1-abe3-b209ca448cd7.mov
Resolves: #667

feat(coral): Topic request approval: add View details modal

---

coral/src/domain/topic/topic-api.ts
coral/types/api.d.ts
openapi.yaml

- Fix documentation of the `request/approve` and `request/decline` endpoint in `openapi.yaml`
- Use those endpoint to define the `domain/topic` entities `approveTopicRequest` and `rejectTopicRequest`
Resolves: #686

feat(coral): Add approveTopicRequest and rejectTopicRequest endpoints 

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.tsx
coral/src/app/features/topics/schema-request/components/TopicSchema.tsx

- add a modal for details overview to the schema requests list for approvers
I named the component that is used in the Modal itself `SchemaRequestDetails` because it describes better what it does. It could be used outside of a modal, so I don't think it should have the connection to `Modal` in it's name. 
I also updated the function to check for a definition of a term in test, so we can make sure the definition is related to a certain term. BUT this only works correctly in that way because our dt/dd terms all are wrapped in a div together, so it depends a bit much on DOM structure, so I'm not too sure about the approach. I think it's important to make sure the right key/values pairs are related, on the other hand it's more brittle that way because it depends on the DOM structure. 🤔  I …

feat(coral): add detail view modal to schema request approvals

---

coral/src/domain/requests.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/schema-request/schema-request-types.ts
coral/src/domain/topic/topic-api.ts

- adds a ts helper to create the types for approve/decline for different `requestEntityType` s 
- is it necessary? maaaaaaybe not. does it make me feel like a smol typescript-🧙‍♀️? Yes, yes it does! 
- adds api calls for approving / declining in the `schema-request-api.ts`
Resolves: #691

feat(coral) Add api definition/types/functions for approve/decline schema request

---

coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/domain/topic/topic-api.ts

Add business logic to:
- approve request on clicking approve quick action
- show Reject modal when clicking reject quick action
- approve request when clicking approve button in Show details modal
- show Reject modal when clicking reject button in Show details modal
Resolves: #688

feat(coral): Topic requests table: add approve / reject topic request actions

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/domain/acl/acl-api.ts

Replace soon deprecated `execAclRequest` and `execAclRequestDecline` endpoint with the generic `request/approve` and `request/decline` endpoints
Resolves: #633

chore(coral): Update approve and reject ACL request endpoints

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.test.tsx
coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.tsx
coral/src/app/features/approvals/schemas/hooks/useTableFilters.test.tsx
coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
coral/src/app/features/approvals/topics/components/DetailsModalContent.test.tsx
coral/src/app/features/approvals/utils/request-status-helper.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/services/check-exhaustive.ts

- adds utils maps for getting readable names for `RequestStatus` values and the correct type of status chip values matched to colours (will add that to topic/acl in a later PR to have a consistent look)
- Replace `NativeSelect` with `ComplexNativeSelect` to sync right value for status
- adds `tableFilters` hook for schema request approvals
- adds `SelectSchemaRegEnvironment` component that takes care of fetching the right environments for schemas from `/schemaRegEnvsGet`
- I added this component in a way that is optimised for the usage in my `tableFilters` hook, it's one of the things we can revisit after this release!
- add filter functionality for environment, status and topic
Resolves: #677 
Why this way

feat(coral): add filter functionality to schema requests approver table

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

Approving a request is an async process that might take a few seconds, so we want to disable the ability to reject the same request while the approve request is not done.
(disregard failure of request, the DEV Kafka env is down ^^)
https://user-images.githubusercontent.com/20607294/221542803-156723d7-822b-4b1a-a888-e25fd71807f3.mov

fix(coral): Disabled reject buttons if approval is in progress

---

coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx

Connectors are not yet implemented in `coral`. Therefore, the corresponding tab in the Approval page should be disabled.
Resolves: #709

refactor(coral): Disable Connectors approvals tab

---

coral/src/app/pages/approvals/acls/index.tsx
coral/src/app/pages/approvals/schemas/index.tsx
coral/src/app/pages/approvals/topics/index.tsx
core/src/main/resources/templates/execAcls.html
core/src/main/resources/templates/execSchemas.html
core/src/main/resources/templates/execTopics.html

Add `PreviewBanner` to each `pages/approvals/*` page component: there is no central Approval page in the Angular app, so we need to granularily redirect to `/execAcls`, `/execTopics` etc.
https://user-images.githubusercontent.com/20607294/221599016-7afc414d-bc89-4450-8f70-6f82007f3187.mov
Resolves: #708

feat(coral): Add preview banners for Approvals

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/components/RequestDeclineModal.test.tsx
coral/src/app/features/approvals/components/RequestDeclineModal.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.test.tsx
coral/src/app/features/approvals/components/RequestDetailsModal.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/domain/acl/acl-api.ts
coral/src/domain/topic/topic-api.ts

For consistency, unify all terminology is UI and in code to use "decline" and variations  everywhere.
Resolves: #693

fix(coral): Approvals: replace all instances of "reject" by "decline"

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
coral/src/app/features/approvals/utils/request-status-helper.ts

- uses the `statusRequest[x]Map` for all approval table views
- removes the unnecessary `ComplexNativeSelect` in schemas table filters
- adds on const `statusList` to be used in all table views
Resolves: #690

refactor(coral): Make status columns in approvals consistent 

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/domain/schema-request/schema-request-api.ts

- adds rejecting workflow from quick action button
- adds rejecting workflow from details modal
- adds approving workflow from quick action button
- adds rejecting workflow from details modal
- renames "reject" to "decline" (see #721) 
- I left the RejectModal alone to not conflict with the mentioned PR!
- approving / declining buttons are disabled while another approve/decline call is in progress
Resolves: #698

feat(coral): Add approving/rejecting schema request 

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/enums/RequestMode.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/RequestStatisticsService.java
core/src/main/resources/openapi.yaml
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/ConnectorRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SchemaRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/RequestStatisticsServiceTest.java

The count statistics mismatch the data returned in some instances because that data is filtered.
So a new option is being provided to allow the correct filtering to also occur on the API stats count that is being returned.
Why this way
This follows a similar pattern already applied and is trying to reduce the number of queries required against the database.

Filter requestors requests from the approval count

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java

This address an issue where on sending a promotion type of request after the promotion of the topic was completed successfully it was not being saved to the Klaw Database. It has to be synced using the sync cluster functionality.
Resolves: #729 
Why this way
A bug fix changed to using enums and the enum for promotion was changed from create to promote.
So in the code where it is being saved to the database as this is a new topic it is and should be treated the same as a create operation.

Issue topic promotion not created

---

core/src/main/java/io/aiven/klaw/dao/SchemaRequest.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/SchemaRequestModel.java
core/src/main/java/io/aiven/klaw/model/cluster/ClusterSchemaRequest.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/openapi.yaml
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java

This change makes forceRegister Nullable. This means when querying by example it does not automatically set forceRegister to false. Previously it was causing an issue where it would only return schema requests where forceRegister was set to false. Meaning any forceRegister requests were not viewable in the UI.
Why this way

Fix return all schema requests including those with forceRegister set

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

- ⛔️ disables quick actions for other requests while an approve or decline is in process
**Note:** While the disabling is tested in the tables (where there are separate table components), there are no test in the higher up components `SchemaRequest` and `TopicRequest` for it right now. These components are responsible for giving the correct values in the prop for table, so they should be tested. Since it's an async process, we would (at our current state) need to add a kind of timeout to get this to work reliable and stable in the tests and that's just a baaaad pattern. We will work on our way to mock api calls that also include a better way of deferring, then we can cover these cases. It's all tested manually. 
- 🧹 unrelated change, removed console.errors from test logs
We had some …

feat(coral): Disable approve/reject buttons in approvals table while action is in progress

---

coral/src/domain/schema-request/schema-request-api.ts

`declineSchemaRequest` used the endpoint `requests/approve` ( 🤦‍♀️ @ myself) it's updated now.

fix(coral): fix endpoint for declining schema requests

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/components/ApprovalsLayout.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

- removes the min width from the data tables
- adds a non-breaking space to the date to prevent linebreak that makes layout look weird ^^ (will also add a note to DS later that having a min-width for table cols could be nice!)
Resolves: #738

fix(coral): Min-width in approvals table fits content

---

coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaRequestDetails.tsx

- adds schema version to details modal
- renames label for schema preview to "Schema preview" (more consistent with label above)
Resolves: #746

feat(coral): Add schema version to details modal for approvals

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/components/ApprovalsLayout.test.tsx
coral/src/app/features/approvals/components/ApprovalsLayout.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

- uses `Alert type="error"` for alerts that notify user that app was unsuccessful to do an operation 
- also adds a missing role alert to ApprovalsLayout
Resolves: #735

fix(coral): Errors should be shown in alerts of type error

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/hooks/useTableFilters.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/schemas/hooks/useTableFilters.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/app/features/approvals/topics/hooks/useTableFilters.test.tsx
coral/src/app/features/approvals/utils/request-operation-type-helper.ts
coral/src/app/features/approvals/utils/request-status-helper.ts
coral/types/api.d.ts
openapi.yaml

- adds a request operation type helper
- chip colour is neutral (for now)
- update type for AclRequest 
- add request types to all tables 
- rename string representation for CREATED status to "Open"
- rename "Claim by team" to "Team" in topics approval table
Resolves: #753

feat(coral): Add request types in approval tables

---

Makefile
README.md
cluster-api/pom.xml
core/pom.xml
openapi.yaml
pom.xml

Update the version to 2.1.0 from 2.0.0 for a minor Klaw release.
Why this way
This will version Klaw jar files for users.

Update the version to 2.1.0 from 2.0.0 for a minor Klaw release.

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx

- moves the DataTable implementation from AclApprovals into own component.
- moves test cases that test the old DataTable away from AclApprovals into own test file.
- add test coverage
By extracting functional components we can reduce the complexity and responsibility of components while increasing the testability.

refactor(coral): Extract a Table component from AclApprovals.tsx #711

---

core/pom.xml

The jakara stream provider is missing without this dependency preventing emails from sending.
Why this way

Add jakarta mail dependency to enable email

---

coral/src/app/features/requests/components/RequestResourcesTabs.test.tsx
coral/src/app/features/requests/components/RequestsResourceTabs.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/requests/acls/index.tsx
coral/src/app/pages/requests/connectors/index.tsx
coral/src/app/pages/requests/index.tsx
coral/src/app/pages/requests/schemas/index.tsx
coral/src/app/pages/requests/topics/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts

Implement routing and empty views to initialize
my requests view in order to enable work on
the subviews.
~~Note*: Did not add test file for `RequestResourcesTab.tsx` yet since there is not really much to test. If requested though i guess we can add similar tab checks like in `ApprovalResourcesTab.test.tsx` for now.~~
Resolves #768
Resolves #771
Resolves #766

feat(coral): Add routes for the requests views #768, #771, #766

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/components/layouts/TableLayout.test.tsx
coral/src/app/features/components/layouts/TableLayout.tsx
coral/src/app/features/components/layouts/__snapshots__/TableLayout.test.tsx.snap

The My requests features use the same layout as the Approvals features. Therefore, rather than duplicating the `ApprovalsLayout` component, we can turn it into a reusable `TableLayout` component at the `coral/src/app/features/components/layouts` level.
```
- Rename ApprovalsLayout to TableLayout
- Move Table layout in coral/src/app/features/components/layouts folder
```
Resolves: #765

refactor(coral): Make ApprovalsLayout reusable as TableLayout

---

coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx

Improve consistency of Approvals tables by always having the same three first columns
https://user-images.githubusercontent.com/20607294/223453801-8ba115c0-4030-48e8-b7ca-cd8f0a8be212.mov

fix(coral): Approvals: always make topic, env and status first columns

---

coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-transformer.test.ts
coral/src/domain/topic/topic-transformer.ts
coral/types/api.d.ts
openapi.yaml

- add `openapi` specs for `getTopicRequests`
- add `getTopicRequests` function to `topic-api`
- the `operationType` param currently do not exist, but will be added shortly
- the transfomer used for `getTopicRequestsForApprover` has been renamed to `transformGetTopicRequestsResponse`, as it is also used for `getTopicRequests`
Resolves: #769

feat(coral): Topic Requests: add API definition and types for `/getTopicRequests`

---

coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

Make it clear for user when there are no approvable requests either at all or matching search criteria by adding empty state with a message to the approve request tables.
Note: Does not add empty state for the All topics view, since the state handling there is more "advanced" and needs some discussion.
Resolves: #684

feat(coral): Add EmptyState to tables #684

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/ClusterApiController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceRegisterSchemaTest.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceTest.java
core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/model/KwClustersModel.java
core/src/main/java/io/aiven/klaw/model/enums/KafkaClustersType.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/resources/openapi.yaml
core/src/main/resources/static/js/envs.js
core/src/main/resources/static/js/modifyEnvs.js
core/src/main/resources/templates/addCluster.html
core/src/main/resources/templates/clusters.html
core/src/main/resources/templates/modifyCluster.html
core/src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
core/src/test/java/io/aiven/klaw/MockMethods.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java

- New cluster type 'kafkarestproxy' can be added under Clusters menu. to store the rest proxy url info.  This cluster type is not used anywhere in klaw.
- When retrieving/registering schema for a topic, if subject compatibility is not set, get global compatibility
Resolves: #679 
Resolves : #726 
Why this way
- This url info can be used by developers while developing kafka clients.
- Compatibility is applicable when registering new schemas, and its relevant for users to view what is the actual compatibility

Adding rest proxy info in clusters, global compatibility set

---

core/src/main/java/io/aiven/klaw/controller/RequestController.java
core/src/main/java/io/aiven/klaw/service/RequestService.java
core/src/main/resources/openapi.yaml
core/src/test/java/io/aiven/klaw/controller/RequestControllerTest.java

This change extends the Request Controller to allow Delete Requests to be processed in the same manner as Approve and decline requests.
It provides the ability to do a multi or bulk delete in the API and it also provides an expanded number of Status Codes to help the UI best understand what worked and what didnt when using the API.
Resolves: #802 
Why this way
This follows a pattern of increasing the usage of Status Codes and reducing the number of endpoints and different objects needed to use the API.

Extend the Request API to process delete requests.

---

coral/src/app/features/requests/components/topics/TopicRequests.test.tsx
coral/src/app/features/requests/components/topics/TopicRequests.tsx

User is able to filter My teams topic requests by topic name. Adds topic filter input and syncs the search params to the api poll.
Resolves: #774

feat(coral): Topic Requests: add search Topic functionality #774

---

coral/src/app/features/requests/components/acls/AclRequests.test.tsx
coral/src/app/features/requests/components/acls/AclRequests.tsx
coral/src/app/features/requests/components/acls/components/AclRequestsTable.test.tsx
coral/src/app/features/requests/components/acls/components/AclRequestsTable.tsx
coral/src/app/pages/requests/acls/index.tsx

In `coral/src/app/features/requests` :
- add `acls` folder
- add `AclRequests.tsx`
- add `components/AclRequestsTable.tsx` 
- add data fetching calling `getAclRequests`
- render data fetched in `AclRequestsTable`
- add tests
Resolves: #799

feat(coral): Acl Requests: Add ACL requests page and table

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/pages/topics/schema-request.test.tsx

- updates packages that do not require fixed for updating
- Add fix for vulnerable peer-dep (`json5 1.0.1` from `eslint-import-resolver-typescript` and `eslint-plugin-import` which both are on latest version)
- test pipeline failed unrelated to the change (did run locally before and after), there was an api mock missing in an existing test suite that surfaced in the CI - test is fixed

chore(coral): Update packages

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/domain/schema-request/index.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/schema-request/schema-request-transformer.test.ts
coral/src/domain/schema-request/schema-request-transformer.ts
coral/src/domain/schema-request/schema-request-types.ts
coral/types/api.d.ts
openapi.yaml

- Add `getSchemaRequests` endpoint to openapi
- Add autogenerated types
- Add api call function
- rename existing functions / type to fit better (shared or separate usage)
- remove unnecessary / unused types
- update barrel file and imports from schema domain
Resolves: #806

coral(feat): My Schema Requests - add API definition and types for `/getSchemaRequests`

---

coral/src/app/features/requests/components/topics/TopicRequests.tsx
coral/src/app/features/requests/components/topics/components/TopicRequestsTable.test.tsx
coral/src/app/features/requests/components/topics/components/TopicRequestsTable.tsx

The edit feature for requests will not be implemented in the backend for this sprint. Remove the action column to edit request.
Resolves: #838

refactoring(coral): Remove Edit column from my topic requests #838

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.tsx
coral/src/app/features/requests/components/schemas/utils/mocked-schema-requests.ts
coral/src/app/pages/requests/schemas/index.test.tsx
coral/src/app/pages/requests/schemas/index.tsx

- adds new directory for `/schema` in feature
- adds component with schema table
- adds component responsible for doing the api call and passing data to the schema table
- adds a utils folder with the mocked data since they are used in all tests anyway, it's easier to keep that up to date and aligned that way. 
Changes `const rows = within(table).getAllByRole("rowgroup");` to a query checking for `rows` in approvals table for topics and schema: 
-> `rowgroup` looks for row groups (well! :D ) like `header`, `body`, `footer`. The test was green by chance. Checking for `row` will return all rows that are rendered and match the lengths of entries plus the row with the columnheaders.  Now it rests what it's supposed to -> "there is one row of content rendered for each entry".
Resolves: #808 
- …

coral(feat): Add table with my schema requests

---

coral/src/app/features/requests/components/topics/TopicRequests.test.tsx
coral/src/app/features/requests/components/topics/TopicRequests.tsx

User is able to browse paginated set of teams topic requests. Adds pagination controls to my teams topic requests page. Syncs the 'page' search parameter as the pagination value.
Resolves: #773

feat(coral): Topic Requests: add pagination to the table #773

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
coral/src/app/pages/requests/schemas/index.test.tsx

- adds pagination to My Schema Request view
- adds missing mocks to tests in SchemaApprovals (they caused a `console.error` that only showed up when running test in separation due to async nature)
Resolves: #809
https://user-images.githubusercontent.com/943800/225607148-55a848b9-e233-4043-a3a4-674581efc0fa.mov

coral(feat): Add pagination with functionality my-schema-requests

---

coral/src/app/features/components/table-filters/MyRequestFilter.test.tsx
coral/src/app/features/components/table-filters/MyRequestFilter.tsx
coral/src/app/features/requests/components/topics/TopicRequests.test.tsx
coral/src/app/features/requests/components/topics/TopicRequests.tsx

This PR renames the url-query-parameter for the toggle "Show only my requests" to `showOnlyMyRequests` (instead of `isMyRequest`).  It's a more precise/descriptive name in context of the UI. 
It also decouples a bit FE code from backend-api, because if BE e.g. would rename `isMyRequest` to `isReallyMyRequest` we only need to update it in one place.

refactor(coral): Rename url param for only showing my requests.

---

coral/src/app/features/components/layouts/TableLayout.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx

- Wraps the filter elements in `TableLayout` in a flexbox component to align them correctly (the toggle was misaligned before)
https://user-images.githubusercontent.com/943800/225877373-3b108986-da4c-4d25-8054-fee7b9d739cf.mov
- adds the toggle to filter request by users own requests
- extends tests for `SchemaRequest` to cover components responsibility to populate filters through url params
Resolves: #812 
https://user-images.githubusercontent.com/943800/225877954-186cf2fd-d0ed-467d-bf31-b381209eb941.mov

feat(coral): My Schema Requests - add Toggle for "Show only my requests"

---

coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/requests/components/acls/AclRequests.test.tsx
coral/src/app/features/requests/components/acls/AclRequests.tsx
coral/src/app/features/requests/components/acls/components/AclRequestsTable.tsx

- add filters to ACL Requests page (Environment, ACL type, Request type, Status)
- harmonize chip components for `acl_ssl` and `acl_ip`: make them `dense`, like the other chip components in tables
**Before:**
**Now:**
Resolves: #830

feat(coral): Acl Requests: add filter functionality (Environment, ACL type, Request type, Status)

---

coral/src/app/features/components/table-filters/MyRequestsFilter.test.tsx
coral/src/app/features/components/table-filters/MyRequestsFilter.tsx
coral/src/app/features/requests/components/acls/AclRequests.test.tsx
coral/src/app/features/requests/components/acls/AclRequests.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
coral/src/app/features/requests/components/topics/TopicRequests.tsx
coral/src/domain/acl/acl-api.ts
coral/src/domain/acl/acl-types.ts

- Add toggle to show only the ACL requests submitted by current user
- rename MyRequestFilter -> MyRequestsFilter (more accurate)
- fix API and types for `getAclRequests` and `getAclRequestsForApprover`
Resolves: #856

feat(coral): ACL requests: add Toggle for "Only my requests"

---

core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
core/src/main/java/io/aiven/klaw/service/RequestService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/test/java/io/aiven/klaw/controller/RequestControllerTest.java
core/src/test/java/io/aiven/klaw/controller/SchemaRegistryControllerTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
openapi.yaml

This PR fixes (HOPEFULLY) a little typo I noticed:
`SchemaRegstry[x]` => `SchemaRegistry[x]`
Since I don't have real experience with working with Springboot, I'm not 100% sure I did everything needed to do this changes safe. 
I did run 
- `mvn spotless:apply`
- `mvn verify`
- `mvn test`
- `mvn clean compile` 
and also did start klaw locally and run coral against the remote-api (i've no data locally) to check the app manually. 
It looks like everything works 🤔 🙏

Fix: fix typo `SchemaRegstry[x]`

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx

When approving or declining a requests in the Approvals UI, we need to trigger a refetch of the `getRequestsWaitingForApproval` call in `ApprovalresourceTabs` to keep the number in the tabs in sync (https://github.com/aiven/klaw/blob/main/coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx#L18-L20)
It looks like this:
```tsx
queryClient.refetchQueries(["getRequestsWaitingForApproval"]);
```
This refetch was missing in a number of situations, so it was added.
Additionally, this refetch was happening before we checked for errors, which makes it sometimes superfluous. It was moved after the error check.

fix(coral): Approvals - Add missing refetch calls for tab tag number

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/DetailsModalContent.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

Unifies the usage of the DataTable actions in the approvals views for more unified experience. In practice, changes from column type "custom" into "action".
Fixes couple of corner cases:
- the ` isBeing*` check per request did not consider if the request was loading. This made it "loading" for example in case where the request failed.
- when request was declined, it was technically possible to click the button again after modal closed. It now disables the row's decline button as well until the decline request in finished.
Tries to do minimal changes to tests to ease review process. Adds couple more test cases per table.
Note*: prior to this commit, we hide the action button if it's not feasible per request, for example: not in `CREATED` state. After this change, the button will always …

refactoring(coral): Use DataTable action column type for table actions #797

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Since the next release will include the new views for "My team's" requests, we can now change the redirects after user successfully created a new topic, schema or acl request. 
Instead of directing to: `/my[Acl/Topic/Schema]Requests?reqsType=CREATED&aclCreated=true` we now redirect to `/requests/[Acl/Topic/Schema]?status=CREATED`
https://user-images.githubusercontent.com/943800/226919006-c986d301-2c41-4daf-a7d5-336bb59fbc56.mov

feat(coral): Update redirect routes after creating new requests

---

coral/src/app/features/requests/components/DeleteRequestDialog.test.tsx
coral/src/app/features/requests/components/DeleteRequestDialog.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
coral/src/domain/schema-request/index.ts
coral/src/domain/schema-request/schema-request-api.ts

- adds api call to delete a schema request
- adds delete process flow from quick action button as well as from details modal
- add additional (for now optional, will change that in a later PR) property `isLoading` to the delete modal that shows a loading animation on the delete button and disables the cancel button. (`isLoading` is active while either the deletion or the refetching of schema requests is in process)
- only close the delete modal after the re-fetch of the schema-requests was successful. That way, user can't manipulate other request while there are still api calls in process. 
Resolves: #814
https://user-images.githubusercontent.com/943800/226834599-49e34681-6161-4189-8a27-3d52416469ca.mov

feat(coral): My Schema Requests - add delete functionality

---

coral/src/app/features/components/layouts/TableLayout.tsx

Implement wrapping behaviour for the filters in `TableLayout` so they stay usable in small vieports
https://user-images.githubusercontent.com/20607294/227160661-9af2149f-4141-46c8-ac06-367e25119b05.mov

fix(coral): Wrap filter components in TableLayout

---

coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
coral/src/domain/schema-request/schema-request-api.ts

Adds filter for Request type in "My team's requests" for schemas. 
Notes: 
- the naming should be "Request type" everywhere, we decided to make that change in the end when all views are done to avoid conflicts etc. (issue for that #896)
- In this PR I changes the order of the columns in the table to match the order in the designs. I included that as a not in #896 so we can make that consistent through all tables)
- `operationType` does not have an "ALL" value like status -> which is more correct and we'll streamline status to follow that approach (follow up issue and more infos: #900) 
- the handling of "ALL" value is a "for now working" solution here, in scope of the follow up we should check how we want to handle types and "who is responsible for creating what parameter" in frontend …

feat(coral): My Schema Requests - add filter functionality for Type 

---

core/pom.xml

Increase and make configurable the timeout and retries for Integration tests
Resolves: #744 
Why this way
Allows users to more easily get around the issue of slow machines.

Increase and make configurable the timeout and retries for Integration tests

---

coral/src/app/components/Modal.module.css

**Problem**: if OS sets "always show scrollbars" behaviour, then scrollbars always show in modals, even when not needed:
https://user-images.githubusercontent.com/20607294/227497279-a1cee8bd-5d9c-4ff5-bf5a-2583d504d18b.mov
**Solution**: set `overflow: auto` instead of `overflow: scroll` in Modal css
https://user-images.githubusercontent.com/20607294/227497507-23847d86-7986-4ffb-b027-5bd08be0f4cb.mov

fix(coral): Fix scrollbars showing inappropriately in Modals

---

coral/src/app/components/Dialog.test.tsx
coral/src/app/components/Dialog.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Adds "success" workflow when user creates a new: 
- topic request
- ACL request
- Schema request
(note: this is a temporary solution to not redirect users without any notice what happened. We'll use a toast notification for that as soon as it's available from the DS) 
The PR also updated the check for our hidden error to be more readable and safe (I noticed an console error in a test, where the success case was mocked by `[ { result: "Success" } ]` -> which was not a success case for our app. 
Resolves: #583
https://user-images.githubusercontent.com/943800/227460687-60a9af5c-8d62-40c1-932a-8cc94c82f287.mov
https://user-images.githubusercontent.com/943800/226944793-f515a1f6-7c9d-4aff-a8da-b50e54af91fa.mov

refactor(coral): Add "success" information "Request new..." workflows

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/dao/Env.java
core/src/main/java/io/aiven/klaw/dao/ServiceAccounts.java
core/src/main/java/io/aiven/klaw/dao/Team.java
core/src/main/java/io/aiven/klaw/helpers/EnvTagConverter.java
core/src/main/java/io/aiven/klaw/helpers/ServiceAccountsConverter.java
core/src/main/java/io/aiven/klaw/model/response/TeamModelResponse.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/resources/application.properties
core/src/main/resources/db/changelog/changelog.yaml
core/src/main/resources/templates/requestAcls.html
core/src/test/java/io/aiven/klaw/MockMethods.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java

As part of Acl request for Aiven system, service accounts are created. To maintain security of those accounts, and prevents from being used by other teams, they are assigned to teams.
Resolves: #723
Why this way
This prevents users from teams to use the service accounts of different teams.

Service acnts

---

core/pom.xml
openapi.yaml

This change allowsklaw to be built on a system that is already running an existing version of klaw by changing the openapi port to the non standard 8097.
Resolves: #741 
Why this way
This allows users to pull and build changes on a server or device without having to take down an existing running version of Klaw.

Configure pom to build the openapi.yaml off port 8097

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/components/layouts/TableLayout.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/services/api.ts
coral/src/services/mutation-utils.ts

We've endpoints that don't return `ApiResponse`, but a _list_ of `ApiResponse`:
- `/request/delete`
- `/request/decline`
- `/request/approve`
They return an array in order to (later!) enable batch operation, e.g. deleting multiple schema requests. 
In that case, they will return:
- a `200` when _all_ requests where successful
- a `500` or `405` when _no_ request was successful
- a `207` when the list contains requests that where successful and others that weren't 
- in that case, they will also contain `data` with `req_id` so we know exactly which requests failed
In our `api.ts`, we have no handling for the `207` case and don't need it currently, since it won't happen. 
But when we get an error from Backend, the UI assumes it's always in a certain structure (and that's not an array :D), …

refactor(coral): Better error handling for ApiResonse[] cases

---

coral/src/app/features/approvals/utils/request-operation-type-helper.ts
coral/src/app/features/components/filters/RequestTypeFilter.test.tsx
coral/src/app/features/components/filters/RequestTypeFilter.tsx
coral/src/app/features/components/filters/useFiltersValues.test.tsx
coral/src/app/features/components/filters/useFiltersValues.tsx
coral/src/app/features/requests/acls/AclRequests.test.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
coral/src/domain/schema-request/schema-request-api.ts

- the naming for (request)operation-type is made consistent to be "Request type" in all user-facing elements
- order of filters and columns in approvals table is aligned and updated
- change CONSUMER and PRODUCER to Consumer and Producer for ACL types (UI only)
Resolves: #896

feat(coral): Streamline naming and order for "My team's requests" views

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/requests/TopicRequestModel.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
openapi.yaml

- validation on 'description' field in requests is now removed. 
- seraching topics based on one env used to return only one env, instead of topics if also exists in other envs. its fixed in this pr
Why this way
For good experience :)

Description field valition, gettopics search for env fix

---

core/src/main/java/io/aiven/klaw/config/CustomJwtDecoder.java
core/src/main/java/io/aiven/klaw/config/SecurityConfigSSO.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/application.properties
core/src/test/java/io/aiven/klaw/config/CustomJwtDecoderTest.java

there is a know issue in keycloak 10.x https://issues.redhat.com/browse/KEYCLOAK-14309
With this implementaion with a different jsson parser in spring, duplicate keys will be ignored.
Why this way
Applicable to only old keycloak version 10.x

Keycloak fix for legacy version

---

core/pom.xml
openapi.yaml

Revrts a change to add a -D param into the core/pom.xml
The change had been added to allow the openapi.yaml to be work off port 8097 however this is also the port now used when using mvn spring boot run.
Why this way
it reverts a breaking change of changing the port.

Reverting change to -D param for pom

---

core/src/main/java/io/aiven/klaw/service/BaseOverviewService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/main/resources/templates/browseAcls.html
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java

This change removes the ability to see sensitive ACL data that has been supplied by another team.
Resolves: #696 
Why this way
This will contribute to a better more secure experience.
As no data is sent over via https request unless it has been validated already in the backend.

Mask ACL data that is not owned by the team.

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.test.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.tsx
coral/src/app/features/topics/browse/components/TopicTable.test.tsx
coral/src/app/features/topics/browse/components/TopicTable.tsx

- add an `ariaLabel` prop to all our `XXTable` components 
- pass it an informative aria label with the page context
- forward this `ariaLabel` value to `DataTable`'s `ariaLabel` prop
Resolves: #925

feat(coral): add ariaLabel prop to tables, pass a better label

---

core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

This change puts in a null pointer check for when some kafka envs have schema registries attached and others do not.
It also fixes an issue where Kafka environments were not being updated when an association was removed from a schema registry to a blank registry.
Why this way
This makes sure that the behaviour is as expected when we go to request or promote a schema.

Schema Association defect

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/components/filters/TopicFilter.tsx
coral/src/app/features/requests/acls/AclRequests.test.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/domain/acl/acl-api.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/topic/topic-api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/resources/application.properties
core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
openapi.yaml

Use `search` param for the API calls in My Requests and Approval tables, to allow partial match.
https://user-images.githubusercontent.com/20607294/228792839-27188cf2-95cd-4406-b8be-7b43b1dbd6ef.mov
As visible in the video, the `getAclRequestsForApprover` endpoint did not currently support the `search` param. Changes to the API have been made to make it possible, but it is missing specific testing. It works though :o
https://user-images.githubusercontent.com/20607294/229109052-f58aba8a-554c-4229-9535-80160cb2305d.mov
Resolves: #939

feat(coral): Use `search` param to filter by topics in data tables

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java
openapi.yaml

when a user or team is deleted, check if there are any users or requests associated to them, and prevent from deletion
Resolves: #947 
Why this way
Keeps sanity of the metadata

Fix user deletion, team deletion validation

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/topic/topic-api.ts

Add support for filtering by request type for Topic approvals and Schema approvals
https://user-images.githubusercontent.com/20607294/229511244-91be6274-b749-48a3-a6cc-3d6e8bf98720.mov

feat(coral): Topic approvals, Schema approvals : Add operation type filter approvals

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx

Matches navigation in sidebar to the current design in Figma  (see issue #976) 
- It's called "Dashboard" because that's the established name for Klaw users in the Angular app
- there's no "User and Teams" page in Angular app, that's why we have a submenu list with relevant links
- We don't have pages in Angular app to link to in "Settings"  that's why it's currently only one list item without sub menu
Resolves: #976
Why this way

refactor(coral): Update main navigation based on current design.

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/connectors/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts

- adds a skeleton page for the new All Kafka Connectors view
- adds routing
- adds correct navigation
Resolves: #980
(note: I noticed that the button text is wrong and renamed it to "Request new Connector", didn't update the recording bc it's not necessary for demostrating)
https://user-images.githubusercontent.com/943800/229723381-8a1d1fdc-84e3-4af4-96af-f9d0826a76f7.mov

feat(coral): Routing and skeleton page All Connectors view

---

coral/src/app/features/requests/RequestsResourceTabs.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx
coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.test.tsx
coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.tsx
coral/src/app/pages/requests/connectors/index.test.tsx
coral/src/app/pages/requests/connectors/index.tsx

Enables the "Connectors" tab in My Teams requests for user and displays all connector requests from the team.
Resolves: #964

feat(coral): My Connector Requests: Add Table rendering connector requests #964

---

Makefile
README.md
cluster-api/pom.xml
core/pom.xml
openapi.yaml
pom.xml

Update version numbers from 2.1.0 to 2.2.0 for Klaw.
Why this way
This is part of the Klaw release process.

Minor Klaw version release.

---

coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/environment/index.ts

- update types in `domain/environment` to make concept more explicit (see description in #993)
- removes ClusterInfo as type
this is needed as prep for adding envs from a new endpoint to the browse connectors view, but felt like it should be in it's own scope
Resolves: #993

refactor(coral): Update concept of Environment in coral 

---

coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
coral/src/app/features/connectors/browse/BrowseConnectors.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.test.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/pages/connectors/index.tsx
coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/connector-transformer.ts
coral/src/domain/connector/connector-types.ts
coral/src/domain/connector/index.ts

- adds missing endpoint `getConnectors` as well as related type and transformer
- add the browse-connector view with 
-  table with connectors
- pagination element for multi page responses
Resolves: #981 
https://user-images.githubusercontent.com/943800/229812391-7c9a89bd-90ec-4198-b0d4-a88eda76255d.mov

feat(coral): Paginated table All Connectors view

---

core/src/main/resources/static/js/envs.js
core/src/main/resources/static/js/modifyEnvs.js
core/src/main/resources/templates/addCluster.html
core/src/main/resources/templates/modifyCluster.html

If the cluster is kafka only and the angularjs UI see it is an aiven kafka service it will allow the service name and project name to be altered.
Resolves: #930 
Why this way
This removes setup information that is not used for either kafkaconnect with aiven nor the schema registry with aiven.

Allow users to edit schema registry cluster with the project and service name

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/controller/TopicSyncController.java
core/src/main/java/io/aiven/klaw/model/TopicInfo.java
core/src/main/java/io/aiven/klaw/perf/CreateBulkTests.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/static/js/browseTopics.js
core/src/main/resources/static/js/syncBackTopics.js
core/src/main/resources/templates/browseTopics.html
core/src/main/resources/templates/syncBackTopics.html
core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
openapi.yaml

- Currently getTopics endpoint takes teamname string as filter param, is now changed to teamId
- To get teams in topics page, getAllTeamsSUOnly is changed to getAllTeamsSU
Resolves: #928 
Why this way
teamId is better than team name strings for filtering data

teamId as filter param in getTopics

---

coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
coral/src/app/features/components/filters/EnvironmentFilter.tsx
coral/src/app/features/requests/acls/AclRequests.tsx
coral/src/app/features/requests/schemas/SchemaRequests.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/app/features/topics/browse/BrowseTopics.tsx
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-test-helper.test.ts
coral/src/domain/environment/environment-test-helper.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/index.ts

We're getting `Environment`s user can use to e.g. filter requests by through different endpoints. This PR updates the `EnvironmentFilter` component to define which endpoints it gets the Environments from so we can reuse it in different cases. 
It also updates the transformer / helper to reflect the `Environment` concept better (the Backend has the concept of an `EnvModel` but this is only used when creating a new Environment)

refactor(coral) Update EnvironmentFilter to handle multiple endpoints.

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java

Allows Environment to be used in My Teams Requests page as a drop down 
Why this way
This allows the filters to be used for the My Requests Page

Allow environment to be used for My Teams requests

---

coral/src/app/features/approvals/components/ApprovalResourceTabs.test.tsx
coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.tsx

- enable the connectors tab in Approval page
- Add connectors table
- Add filters
https://user-images.githubusercontent.com/20607294/231186604-71d12efd-ec9f-4a46-afb9-d6477c334f34.mov
The View, Approve and Reject buttons are nonfunctional, feature to be added in issue 
#1014 
Resolves: #1013

feat(coral): Approve connector request: Add `Connectors` tab content (`DataTable`, filters)

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

This change allows connectors to be searched using a case insensitive partial match.
Why this way
This makes it consistent with the other resources like topics and requests and maintains a common user experience.

Add case insensitive checks

---

coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
coral/src/app/features/approvals/connectors/ConnectorApprovals.tsx
coral/src/app/features/components/ConnectorDetailsModalContent.test.tsx
coral/src/app/features/components/ConnectorDetailsModalContent.tsx
coral/src/app/features/components/SchemaRequestDetails.tsx
coral/src/domain/connector/connector-api.ts

- Add `ConnectorDetailsModalContent` component
- Add Approve, Decline and Details modals and business logic handling their respective actions
https://user-images.githubusercontent.com/20607294/231417796-2b9b1fc2-8b72-4bb9-9323-d027cde232c5.mov
- fix `getConnectorRequestsForApproval` API endpoint path -> `getConnectorRequestsForApprover`
- make height of `MonacoEditor` for Connector and Schema requests a little smaller, to avoid rendering superfluous vertical scroll bars
Resolves: #1014

feat(coral): Approve connector request: Add View, Approve and Reject logic

---

coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
coral/src/app/features/connectors/browse/BrowseConnectors.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.tsx
coral/src/domain/connector/connector-api.ts
coral/src/domain/topic/topic-api.ts

- adds a select element to enables users to filter the Connectors by Environment 
- adds a search field to enable users searching by a Connectors name
- `Filter by team` will be in a separate PRs as I'm waiting for a little Backend change for that (we want to use `teamId` here to be consistent with the other requests, it currently still uses `teamName`)
- The search is currently case-sensitive, this will be updated in the Backend
(note: I only have Connectors in `DEV` and can't create Connectors requests on different Envs as a service is not running at the moment, that's why it looks weird in the recording. API calls work like expected and I will test that manually later when the service is up!)
https://user-images.githubusercontent.com/943800/231199064-b0a2798a-c83c-4d46-a6e1-29cc56241ec8 …

feat(coral): Add filter for Environment and search field.

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/ClusterApiController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/ClusterTopicRequest.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/ServiceAccountDetails.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/AivenApiService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaTopicService.java
core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/enums/EntityType.java
core/src/main/java/io/aiven/klaw/model/response/ServiceAccountDetails.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/static/js/browseAcls.js
core/src/main/resources/static/js/requestAcls.js
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/CommonUtilsServiceTest.java
core/src/test/java/io/aiven/klaw/service/ExportImportDataServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java
openapi.yaml

- All users are now part of internal memory, and retrieved from memory. When user added/modified, memory is updated.
- All topics are now part of memory, and when topic requests are approved, this memory is updated.
- get services accounts and get service account endpoints are updated to return custom class
Resolves: #1007
Why this way
To reduce number of db calls, users and topics can be part of memory, which should handle even 50k topics.

Users and topics set in memory to reduce db calls

---

coral/src/domain/acl/acl-api.ts
coral/src/domain/auth-user/auth-user-api.ts
coral/src/domain/connector/connector-api.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/requests/requests-api.ts
coral/src/domain/schema-request/schema-request-api.ts
coral/src/domain/team/team-api.ts
coral/src/domain/topic/topic-api.test.ts
coral/src/domain/topic/topic-api.ts
coral/src/services/api.test.ts
coral/src/services/api.ts

In `domain`, we write functions to interact with the Klaw API in `coral`. The way we used to write such functions  was like this:
```tsx
api
.get<KlawApiResponse<"getAclRequests">>(
`/getAclRequests?${new URLSearchParams(filteredParams)}`
)
api
.post<KlawApiResponse<"deleteRequest">, DeleteAclRequestPayload>(
`/request/delete`,
{ requestEntityType: "ACL", reqIds }
);
```
This relied entirely on typing the correct string as the path, which is uncomfortable and allows for easily avoidable errors.
This PR introduces an `API_PATHS` map, allowing to write such functions in this way, which is more ergonomic and more secure:
```tsx
api
.get<KlawApiResponse<"getAclRequests">>(
// no hardcoded path, autocomplete available
API_PATHS.getAclRequests,            
// no need for string interpolation of …
```

refactor(coral): Use API_PATHS map instead of hardcoded paths in `domain`

---

coral/src/app/components/Form.tsx

Having `MultiSelect` be rendered oustide of a `Controller` component had the side effect of introducing a desync bwteen the value stored in the `form` and the value displayed by the component. This would happen when a value is set in the `form` before the component is rendered, most notably in ACL request form, when switching between an Aiven cluster environment and a non Aiven cluster environment:
https://user-images.githubusercontent.com/20607294/232729487-ac14a38e-d149-4378-bf9d-18f1ce601da6.mov
We make `BaseMultiSelect` a controlled input by adding the `value` prop explicitly, fixing the issue:
https://user-images.githubusercontent.com/20607294/232730139-cc1a9e65-4f39-4f66-ac26-d0d9bbd029ca.mov

fix(coral): Add controlled value for MultiSelect

---

coral/src/services/api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/model/response/TopicOverview.java
core/src/main/java/io/aiven/klaw/service/BaseOverviewService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/main/resources/static/js/browseAcls.js
core/src/main/resources/templates/browseAcls.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/controller/AclControllerTest.java
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java
openapi.yaml

Retrieves one environment details only in Topic overview page
- Topic envs
- Schema envs
- topic promotion details are only displayed in highest topic env
A drop down is displayed with all available envs of the topic
- getAcls endpoint changed to getTopicOverview
Resolves: #943 
Why this way
User gets a clear view of one env details of topic

Topic overview per environment

---

coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
coral/src/app/features/connectors/browse/BrowseConnectors.tsx
coral/src/app/pages/requests/connectors/index.test.tsx

- adds a select element for teams
Resolves: #1019

feat(coral): Add team filter in All Connectors view

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/connector-types.ts
coral/src/domain/connector/index.ts
coral/src/domain/topic/topic-api.test.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/controller/AclSyncController.java
core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
core/src/main/java/io/aiven/klaw/controller/KafkaConnectSyncController.java
core/src/main/java/io/aiven/klaw/controller/RolesPermissionsController.java
core/src/main/java/io/aiven/klaw/controller/ServerConfigController.java
core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/controller/TopicSyncController.java
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/controller/UtilController.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
openapi.yaml

- Add `createConnectorRequest` to `domain/connector`
- All responses are typed as `application/json` in `openapi.yaml`
- Generate types and update outdated tests
Resolves: #1053

feat(coral): Add createConnectorRequest in domain/connector, update API response to be `"application/json"`

---

coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
coral/src/app/features/components/filters/EnvironmentFilter.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/pages/requests/connectors/index.test.tsx
coral/src/services/api-mocks/server.ts

We had api calls in unit tests due to a missing mock. 
- added the missing mock
- update the query in test to check for the correct element (combobox)
- before, it rendered a `textbox` because the call to aiven service accounts returned an error, so it defaulted to the `textbox`. it should render a `combobox` for an aiven service account though, which it now does after adding the correct mock

refactor(coral): Fix api mocks in tests

---

coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/features/topics/browse/components/TopicTable.tsx

Adds a link Icon to make links in tables more discoverable.
Resolves: #990

refactor(coral): Add Icon as link indicator in tables

---

core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

Defect in processing the response from the cluster-api
Why this way
Resolves the defect.

Correct Approve Connector requests response

---

coral/src/app/components/Form.tsx
coral/src/app/features/topics/acl-request/fields/IpOrPrincipalField.test.tsx

- `MultiSelect` in `Form` switched from uncontrolled to controlled components, it's now controlled
- adds more specific testing for the right error to be passed and makes sure there's only an error logged when we expect it
Resolves: #1059 
(there are no service accounts currently, so I mocked the response for the recording)
https://user-images.githubusercontent.com/943800/233925113-30e35d98-f64d-43f8-90b1-5991c51f2e91.mov

fix(coral): Make `MultiSelect` controlled

---

core/src/main/java/io/aiven/klaw/dao/migration/MigrateData2x2x0.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/test/java/io/aiven/klaw/dao/migration/MigrateData2x2x0Test.java

Do a look up for the superadmin or admin to run the queries for migration to 2.0.0 Klaw
Instead of using the default superadmin user a look up is done to find the superuser if the superuser is not found, it will throw an error preventing startup.
Tested on a brand new system which does not have any db yet (starts fine)
Tested on an existing system requiring update (starts fine)
Why this way
The default superadmin user is not available when single sign on is being used for Klaw.

Do a lookup for the superadmin or admin user for db look ups in migration utility

---

coral/src/app/features/topics/request/schemas/topic-request-form.ts
coral/src/domain/environment/environment-transformer.test.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/src/services/api.ts

This is a 🐛  fix for #1085
- based on the `openapi.yaml` [definition](https://github.com/aiven/klaw/blob/main/openapi.yaml#L6782), the `params` property for `EnvResponseModel` is required, that's what our api functions and transformers are based of
- the endpoints `getSchemaRegEnvs` and `getSyncConnectorsEnv` return a `EnvResponeModel` based on openapi, but in reality they can return environments that don't have a `params` property (and they do so on the current staging env, that's how I noticed the bug
(Temporary fix for now, we should see why the openapi defines it that way and see if we can make that better)
Since we can't be 100% certain that there are `params` on the Environment, I updated our own type `Environment`, updated the transformer and all usage accordingly, so we're on the …

fix(coral):  Add handling for missing params in `Environment`

---

coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/connectors/request/schemas/connector-request-form.ts
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/domain/acl/acl-api.ts
coral/src/domain/connector/connector-api.ts
coral/src/domain/topic/topic-api.test.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/model/requests/BaseRequestModel.java
openapi.yaml

Draft for Create connector request. Misssing:
Resolves: #1055

feat(coral): New connector request: add form to create new connector request

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
coral/src/app/features/topics/request/utils.test.ts
coral/src/app/features/topics/request/utils.ts
coral/src/domain/environment/environment-transformer.test.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/topic/topic-api.test.ts
coral/src/domain/topic/topic-api.ts

Adds additional information about topic name pattern for users as placeholder. That's not ideal, because it's not a good way to inform users, but since DS component do not support a more usable/accessible way, it's a compromise. VO screenreader on mac does read a placeholder, too. (it's not readable on a small screen, outside of high contrast env, for people struggling with low contrast etc.)
I would create a follow up in DS to enable description of form inputs, then we can update and use proper description instead of placeholders. That also enables us to more text.
- the placeholder always inform about general pattern for topic name (regex is based on [backend](https://github.com/aiven/klaw/blob/main/core/src/main/java/io/aiven/klaw/model/requests/TopicRequestModel.java))
- if there is …

feat(coral): Add regex validation for topic request 

---

coral/.nvmrc
coral/README.md
coral/package.json

- adds `.nvmrc` file
- allows a broader range of node-version to be used in package.json and also nvm

refactor(coral) Add nvmrc and define more broad version

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/request/form-schemas/topic-request-form.ts
coral/src/app/features/topics/request/utils.test.ts
coral/src/app/features/topics/request/utils.ts
coral/src/domain/environment/environment-test-helper.ts

When a topic name should have a regex ( `applyRegex: true` in the environments params), then _only_ this regex is used for validation, regardless if prefix or suffix is also in the params. 
This PR updates this in form field instructions (currently the placeholder) and validation. 
It also removes a small text that was used to try out options for field instructions and sneaked itself in 🥷 through the last PR. 
It also updates test cases to confirm proper validation.
(using a mocked environment api call)
https://user-images.githubusercontent.com/943800/236470395-da6e0751-70e0-4d35-b605-f7422d081155.mov

refactor(coral): Only use regex for topic name validation if it should be applied

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/ClusterApiController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/RegisterSchemaCustomResponse.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/RegisterSchemaResponse.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceRegisterSchemaTest.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/UtilComponentsServiceTest.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/model/cluster/RegisterSchemaCustomResponse.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/DefaultDataService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java
core/src/test/java/io/aiven/klaw/service/UiConfigControllerServiceTest.java

- When a new schema is requested, it is stored in db together with its version. Cluster api is updated to return version together with id
- there is a superuser mailid which is now removed and using klaw admin mail id from application.properties.
Resolves: #1102 
Resolves: #1111 
Why this way
- Schemas can now be searched through

Save schemas with versions in db

---

coral/src/domain/schema-request/schema-request-api.ts

- `uploadSchema` does not require the `requestOperationType` to be in the payload
- typing for the api call did not use the ` KlawApiRequest<"uploadSchema">` type to define payload, which is why the TS compiler didn't catch it. 
It's now updated to:
```api.post<
KlawApiResponse<"uploadSchema">,
KlawApiRequest<"uploadSchema">
>(API_PATHS.uploadSchema, payload);
```
this made `pnpm tsc` fail and surfaced that bug. 
We're now passing the `requestOperationType`
Note: We should check other APIs too for this pattern. 
Why this way

fix(coral): Update payload and typing in schema request

---

coral/src/app/layout/page/BasePage.tsx

Adds a high z-index to skip link for `focus-visible` (so only when it's in focus due to keyboard navigation) which is needed now for it to show up. 
Resolves: #1117
https://github.com/aiven/klaw/assets/943800/7c05a43c-e72f-4436-9a7e-1e3724c88558

fix(coral): Add z-index to skip link for focus-visible

---

coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

https://github.com/aiven/klaw/pull/1119 introduced a "smarter" environment Select input in ACL forms. The available environments will be enabled or disabled depending on the topic chosen. However, when choosing the `PREFIXED` pattern type, all environments would be disabled and render a wrong state, because the prefix may not be === an existing topic name.
https://github.com/aiven/klaw/assets/20607294/e43e9e57-0f0d-431a-8fef-c9ae9d8d7574
In regards to how the `PREFIXED` option is used, we should allow all environments to be chosen in this case.
https://github.com/aiven/klaw/assets/20607294/ab6b12b1-e897-486b-b9fc-3e5bb62f5242

fix(coral): Make all env available when using prefix in ACL request

---

coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Navigating to `/topic/aivtopic1/request-schema` will return this warning in the browser's console:
```
Warning: Select elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled select element and remove one of these props. More info: https://reactjs.org/link/controlled-components
```
This is because we set a `defaultValue` for the Topic name's `NativeSelect`, when none is needed: its `value` is already set by the `useForm`'s `defaultValues` option.
We can therefore safely delete it and solve the conflict.

fix(coral): Remove superfluous `defaultValue` in `TopicSchemaRequest`

---

core/src/main/java/io/aiven/klaw/dao/Acl.java
core/src/main/java/io/aiven/klaw/dao/AclRequests.java
core/src/main/java/io/aiven/klaw/helpers/AivenAclIdConverter.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/static/js/browseAcls.js
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java

- service account pwd is not visible in UI
- delete aiven acl with id, after sync
Why this way

Fix pwd for service account, delete acl

---

core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java
core/src/test/java/io/aiven/klaw/service/SchemaOverviewServiceTest.java
openapi.yaml

Change in API requires finding the environments a topic is provisioned on by a different look up.
This change makes a list of the Kafka environments that the topic is provisioned on using existing information instead of information passed in through the API.
Why this way
This means we do not rely on the api to pass the information but it allows us to do a look up using information we already have from a verified source, straight from the db.

Return Schema Promotion button using new TopicOverview button

---

core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/test/java/io/aiven/klaw/service/MailUtilsTest.java

This change removes the team being CC'd on password resets.
Why this way
This is a security concern and needs to be rectified to ensure others can not access Klaw while pretending to be another party.

Remove CC of team on password resets.

---

coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/forms/SkeletonForm.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/layout/Layout.test.tsx
coral/src/app/layout/Layout.tsx
coral/src/app/layout/LayoutWithoutNav.test.tsx
coral/src/app/layout/LayoutWithoutNav.tsx
coral/src/app/layout/page/BasePageWithoutNav.test.tsx
coral/src/app/layout/page/BasePageWithoutNav.tsx
coral/src/app/pages/approvals/index.tsx
coral/src/app/pages/connectors/index.tsx
coral/src/app/pages/connectors/request.tsx
coral/src/app/pages/index.tsx
coral/src/app/pages/not-found/index.tsx
coral/src/app/pages/requests/index.tsx
coral/src/app/pages/topics/acl-request.tsx
coral/src/app/pages/topics/index.tsx
coral/src/app/pages/topics/request.tsx
coral/src/app/pages/topics/schema-request.tsx
coral/src/app/router.tsx

- Add `LayoutWithoutNav` and `BasePageWithoutNav`
- Use `Layout` and `LayoutWithoutNav` as parent `element` in `router.tsx` for relevant routes
- Remove inline `Layout` usage in pages
- Fix layout styles
All forms are now rendered without side nav, as per design specs.
https://github.com/aiven/klaw/assets/20607294/c58666fc-923c-4195-a9ea-7b251a756e2e
Resolves: #1141

feat(coral): Implement layout for request creation forms (no side nav)

---

core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java

When a user is deleted, look for existing requests with only created state
Resolves: #1219  
Why this way
Helps in removing stale data like inactive users

Update query with created state

---

core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/static/js/connectorOverview.js

This sends the requestOperationType with the request on creation allowing it to correctly create the request and it also ensures that the requestOperationType is handled correctly on approval
Resolves: #1070 
Why this way

Issue connector promotion

---

coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
coral/src/app/router.tsx
coral/src/domain/topic/topic-types.ts

Add Table rendering Topic subscriptions. The Table can render each of the three types of subscriptions:
- user subscriptions
- prefixed subscriptions
- transactional subscriptions
The Table takes a `filteredData` prop because we will filter the data we get from the `getTopicOverview` call further in the PR implementing the filter #[1230](https://github.com/aiven/klaw/issues/1230)
https://github.com/aiven/klaw/assets/20607294/fc5d13a3-7f77-4853-9cf4-f694fec82688
- The UI to switch between subscription types is tabs in the design, but there are no such tabs in `aqaurium`, so radio button were implemented
- The data fetched currently has a hardcoded `environment` param, as this value will be picked from the outlet context once it is implemented
Resolves: #1229

feat(coral): Topic overview, subscriptions - Add Subscriptions table component

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/model/AclInfo.java
core/src/main/java/io/aiven/klaw/model/SyncAclUpdates.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/resources/static/js/synchronizeAcls.js
core/src/main/resources/templates/synchronizeAcls.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java
openapi.yaml

when aiven acls are synced with klaw, aclid is captured so that deletion is possible
Resolves: #1244 
Why this way
It is now possible to delete acls which are synced from other clustr

Fix acls sync delete from other clstr

---

coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
coral/src/app/features/team-info/TeamInfo.test.tsx
coral/src/app/features/team-info/TeamInfo.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/domain/team/index.ts
coral/src/domain/team/team-api.ts

If a user is able to switch teams, we want to enable them to do so in coral to make usage more comfortable. 
- adds a component to show a dropdown with possible teams for users that are able to switch teams
- adds a _temporary_ property to enable us to show a modal without any button. The DS as a UI Block component in progress that we will use in the future, so this is only a temporary solution.
Resolves: #1096
https://github.com/aiven/klaw/assets/943800/4a7c9eda-1c0f-4a90-b880-f012a453ccb3

feat(coral): Enable users to change teams in coral

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/layout/header/HeaderNavigation.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx

Update `aquarium` dependency.
- `Toast` is here. This issue can be tackled: https://github.com/aiven/klaw/issues/614
- The icons have been updated, and `layoutGroupBy` has beend eleted. It jas been replaced by `dataflow02`:

chore(coral): Update aquarium -> 1.20.0

---

coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx

Use `SegmentedControlGroup`  instead of `RadioButtonGroup` for subscription options:
https://github.com/aiven/klaw/assets/20607294/2e23faae-4a82-4c89-88db-04469512f423
https://github.com/aiven/klaw/assets/20607294/ca831cd0-d285-490b-a61a-0318d4d7e8b5

feat(coral): Use SegmentedControlGroup for subscriptions options

---

coral/src/app/features/topics/overview/messages/TopicMessages.test.tsx
coral/src/app/features/topics/overview/messages/TopicMessages.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageItem.test.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageItem.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageList.test.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageList.tsx
coral/src/app/pages/topics/overview/messages/index.tsx
coral/src/app/router.tsx
coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-types.ts

User is able to view topic content
- "5" is hardcoded as the offset (always 5 latest messages) for the message request. The filter + button to consume has it's own ticket.
- selected env is hardcoded for the message request, needs a follow up pr when the env is selectable and available through `useTopicDetails`
- `partition` and `timestamp` are not available as metadata
- The "notdefined" for consumer group is copied over from the old ui. I assume it is a magic value that shifts the responsibility for making up the consumer group id in the client to the server side.
If consuming messages is succesful, the api returns messages as: `{ 0: 'HELLO', 1: 'WORLD' }` where key = offset. If there is no topic content or consuming failed, the endpoint returns `{ "status": false }`. Currently, the …

feat(coral): Topic messages: Add topic message list #1235

---

coral/src/app/features/topics/overview/messages/TopicMessages.test.tsx
coral/src/app/features/topics/overview/messages/TopicMessages.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageItem.test.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageItem.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageOffsetFilter.test.tsx
coral/src/app/features/topics/overview/messages/components/TopicMessageOffsetFilter.tsx
coral/src/app/features/topics/overview/messages/useOffsetFilter.test.tsx
coral/src/app/features/topics/overview/messages/useOffsetFilter.tsx
coral/src/services/api.ts

User is able to specify the offset a.k.a the amount of messages starting from latest. In addition, a button to refresh messages
[Screencast from 2023-05-26 10-28-03.webm](https://github.com/aiven/klaw/assets/15416578/52c7d377-eaf6-4d70-be58-31cc0020e88c)
Resolves: #1237
Resolves: #1239

feat(coral): Topic messages: Add filter to set offset #1237

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
coral/src/services/api.ts

- adds `PageHeader` component with "Request a subscription" button
- renders a specific ACL request form for this context:
- environment is locked to the one currently selected in topic overview
- topic name is locked to the one in the topic overview
- pattern type can only be `LITERAL`
- `/topic/:topicname/subscribe` requires an `env` search param or it will redirect to `topic/:topicName/subscriptions`
https://github.com/aiven/klaw/assets/20607294/7d569891-55f8-4877-91e5-31dc55e3743c
Resolves: #1232

feat(coral): Topic overview, subscriptions - Add Request a subscription button

---

coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/queries/useExtendedEnvironments.tsx

`useExtendedEnvironments` returns the `data` and `isLoading` values from `useQuery`. However, there is a render tick that will have `isLoading` as `false` while `data` is still the empty value. In `TopicSubscriptions`, this results in the `isValidEnv` check to fail, and redirect when clicking "Request new subscription". The second click behaves correctly, as the data is already fetched. 
https://github.com/aiven/klaw/assets/20607294/7a1d8b03-a855-44ce-b765-3403ac5c467e
Use `isFetched` instead of `isLoading` to ensure the data is present:
https://github.com/aiven/klaw/assets/20607294/2a20ae69-0a4c-41ca-8c70-47e3850c8ca4

fix(coral): fix redirect on first load for Request submission from Subscriptions tab

---

coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx

Add boxes with the amount of producer and consumer subscriptions for the current topic
https://github.com/aiven/klaw/assets/20607294/3fdf6da8-62fb-4b5f-a6c6-171fdf82ca70

feat(coral): Topic subscriptions - Add stats for consumers and producers

---

coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx

Because we have the `environmentId` value in the `useTopicDetails` context hook relies on the `environmentId` state defined in `TopicDetails`, it is `undefined` until the user choose to interact with the environment select input. This leads to some unexpected behaviour and a desync between what is shown in the UI and what is accessible in the `useTopicDetails` hook. For example, navigating to create a new subscription lead to an emnpty `env` search param:
https://github.com/aiven/klaw/assets/20607294/70c9aecd-c020-406b-9cd2-e9c069932997
Add the first environment in the list as default value for `environmentId`, as it seems to be what is fetched from the API.

fix(coral): Add default value for context environmentId in useTopicDetails

---

coral/src/domain/topic/topic-api.ts
coral/src/domain/topic/topic-types.ts
coral/src/services/api-helper.ts

- add `getSchemaOfTopic`
- modify `convertQueryValuesToString` to be able to parse arrays of strings as well (the `kafkaEnvIds` param is typed as `string[]`, I assume that this means the param should transform `[1, 2]` to `1,2`, but to be verified.
The types for `kafkaEnvIds` are wrong, only the first ID is taken into account, so it should be corrected to be `string` and not `string[]` (talking under the authority of @aindriu-aiven ). This PR still is valid, I think, as it stands currently.

feat(coral): Add `getSchemaOfTopic` to `topic-api` domain

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/model/AclInfo.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/static/js/synchronizeAcls.js
core/src/main/resources/templates/synchronizeAcls.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java
openapi.yaml
pom.xml

- In Acl sync from Cluster : if acls exist in klaw and not in cluster, show an option to remove from klaw
- Team deletion should be possible now (fix in a few db queries, requests in created state)
Resolves: #xxxxx (partially fixes 1286)
Why this way
It is now possible to remove acls from klaw, and delete teams

Fix acl removefromklaw, teams delete defect

---

coral/src/app/features/topics/details/history/TopicHistory.test.tsx
coral/src/app/features/topics/details/history/TopicHistory.tsx
coral/src/app/pages/topics/details/history/index.tsx
coral/src/app/router.tsx
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java

- adds the table showing topic history
https://github.com/aiven/klaw/assets/943800/6d3ce12c-864b-4ad6-837e-c42ac463ad0c
Resolves: #1299

feat(coral) Topic overview - Add topic history view and table [epic #1299]

---

coral/src/app/features/topics/details/TopicDetails.tsx

We have a flash of stale data when navigating to Topic overview in succession:
https://github.com/aiven/klaw/assets/20607294/0d25d8af-41fe-4fba-979a-ab57fc4f5cda
This is because we rely on `isLoading`, which is only `true` the first time we fire a query.
Display loading state when a discrepancy is detected between the topic name passed as props and the one in the current data. Still preserves the instant switch between environments after first fetch (as opposed to using another value from the `useQuery` like `isRefetching`):
https://github.com/aiven/klaw/assets/20607294/e3b57567-3864-495d-8efb-d61cbde61911

fix(coral): Show loading state instead of stale data

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/AivenApiService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/AivenApiServiceTest.java
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.tsx
coral/src/domain/acl/acl-api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/requests/DeleteAclRequestModel.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/static/js/browseAcls.js
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
openapi.yaml

- Sync acls from cluster now gets 'readwrite' acls for Aiven cluster. this is be ignored.
- Submitting Delete Acl request should not be allowed multiple times
- On approve acl request, check if topic exists before.
- CreateDeleteAclSubscriptionrequest change request param to request body
Resolves: #1286
Why this way
readwrite should be ignore, as it's not a standard, and submitting multiple delete acl request should not be allowed

Improvements

---

coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

- env can now be passed via query param in the url to fill out the schema form
- I added `navigate(-1)` (which is the last page the user came from) instead of to a certain page, because we don't know (necessarily) where a user came from now. 
----> I could update that for the other forms, too?
Resolves: #1307

refactor(coral): Enable passing env through query for schema requests

---

coral/src/app/features/topics/browse/components/TopicTable.test.tsx
coral/src/app/features/topics/browse/components/TopicTable.tsx
coral/src/app/features/topics/browse/utils/create-topic-overview-link.test.ts
coral/src/app/features/topics/browse/utils/create-topic-overview-link.ts

- if the feature flag for topic overview is not enabled, the links in topic list go to the original Klaw app
(feature flag is only enabled in DEVELOPMENT mode, so it's not in the build)

fix(coral): link to angular for topic overview if feature flag is not enabled.

---

coral/src/app/features/topics/details/components/TopicDetailsHeader.test.tsx
coral/src/app/features/topics/details/components/TopicDetailsHeader.tsx

- Updates the styles in `TopicDetailsHeader` to match the `PageHeader` in the DS (we can't implement the current layout with the DS component, so it's agreed with design to do it like that for now)
Resolves: #1322

feat(coral): Update styles for page header topic details

---

.github/ISSUE_TEMPLATE/01_question.md

Adds a top level name as this is a required part of the bug template.
Why this way

Add top level name.

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-api.ts

The rest endpoint to get only the allowed/configured envs are returned for topic creation
Use The following rest api endpoint
/getEnvsBaseCluster
instead of
/getEnvsBaseClusterFilteredForTeam 
to retrieve the configured list of allowed kafka envs instead of a list of all envs.
Why this way

Fix(Coral): Topic Creation retrieves a sublist of environments based on admin config

---

core/src/main/resources/static/js/requestAcls.js
core/src/main/resources/templates/browseAcls.html
core/src/main/resources/templates/requestAcls.html

The coral acl request forms require the environment id to be passed to allow the redirect to be accepted.
Why this way

Correct the redirect urls

---

coral/src/app/features/topics/details/components/StatsDisplay.tsx
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap

When the value of the `amount` prop is `0`, the typography styles do not apply
Replace boolean coercion by more specific check (`0` is falsy)

fix(coral): Fix incorrectly displayed 0 values in `StatsDisplay`

---

core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java

It checks if there are any open requests for the topic when determinig if the topic should be able to be deleted.
Why this way

Only show delete button when no request is open against the Topic

---

coral/src/app/features/topics/details/TopicDetails.test.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
coral/src/app/features/topics/details/history/TopicHistory.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/utils.test.ts
coral/types/api.d.ts
openapi.yaml

This resolves a miss where a file was not checked in as part of PR 1347
Why this way

OpenApi.yaml was not correctly committed as part of PR 1347

---

coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
coral/src/app/features/topics/details/history/TopicHistory.test.tsx
coral/src/app/features/topics/details/history/TopicHistory.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/model/response/SchemaDetailsPerEnv.java
openapi.yaml

https://github.com/aiven/klaw/assets/20607294/866d5d1d-fd47-40cc-b64f-d29252da7e6f
- Render correct data for selected schema
- Refetch data when switching schema version
- redirect to correct form when clicking 'Request new Schema"
- to achieve this, allow schema request form to use environment name as well as environment ID as `env` search param
- Add empty state when topic has no schema
https://github.com/aiven/klaw/assets/20607294/4ab81b04-89aa-4beb-bdfb-4ebec3ce791b
Resolves: #1319
Resolves: #1320

feat(coral): Topic details - Schema data and switching versions

---

coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/pages/topics/schema-request.test.tsx

- we used a confirmation dialog to inform users about successful creating of requests as a temp solution
- with the available toast we now can add notifications
- replaces dialog with notification for creating topic, acl, schema and connector requests
https://github.com/aiven/klaw/assets/943800/2442bd41-ffa2-485e-9429-02ea16325edc
https://github.com/aiven/klaw/assets/943800/5e198022-1121-475d-a479-71e4eab541ee
https://github.com/aiven/klaw/assets/943800/3dbd7f3b-99eb-4020-b205-a591be0e4502
https://github.com/aiven/klaw/assets/943800/4717914c-5e43-406d-a530-4167ea9e8a97
https://github.com/aiven/klaw/assets/943800/43a01b15-823b-47dd-a041-95e3ef416e15
Resolves: #614

refactor(coral): Replace temp dialog with toast

---

coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/details/settings/TopicSettings.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

https://github.com/aiven/klaw/pull/1352 introduced some inconsistency in the copy for the toast notifications dispatched on successful operations. This PR harmonize them according to the pattern that was reviewed and approved by Harshini.

fix(coral): Harmonize toast copy

---

core/src/main/resources/templates/requestConnector.html

Adds a link from the angular UI to the coral ui on the connector request page.
Resolves: #1357 
Why this way
This is consistent with how we now show this option.

Add link to coral connector

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

Add debug logging to find and print out any issues from trying to delete a team.
Allows a user to debug an issue where they are unable to delete a team to see why they can not delete that team.
add the following logging line in klaw cores application.properties to see these additional logging statements.
logging.level.io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc=debug
Why this way
This way the queries are still only executed once but are also logged out.

See why a team is not available for deletion with debug logging

---

coral/src/app/components/FileInput.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/components/AclDetailsModalContent.test.tsx
coral/src/app/features/components/AclDetailsModalContent.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx

We had a small bug, where the UI showed `[object Object]` instead of the name of an environmentList, after the environmentList changed from a list of string to a list of objects with `{ id, name }`. We didn't notice this in test/typescript, because we used literal string to pass the env information, like this: 
```
environmentList.map( ( env: string, index: number) => {
return <element propertyThatIsTypedAsString={`$env} ` />
})
```
To prevent that from happening in the future, I replaced all usage of template strings in passing props where it could cause the same kind of error. 
Hope I found all 🤞 and it's a good learning to use template strings carefully :D

refactor(coral): Remove template string where it could hide type errors.

---

coral/src/app/features/topics/details/TopicDetails.tsx

`isLoading` only is `true` on first load, not on refetch. Therefore, when navigating through different topics, we have a flash of stale content showing : 
https://github.com/aiven/klaw/assets/20607294/ea09e0ef-1a53-4c1b-9694-4c0e21e6c161
~~Use `isFetching`, which will be `true` on first load and subsequent fetches. This flashes the loader, which is more appropriate.~~
Use exhaustive keys in our queries so that the cache is properly invalidated when navigating to different topics, but still preserved when appropriate.
https://github.com/aiven/klaw/assets/20607294/5ad88229-7c67-4f7c-87f4-bb5a676ba6a2
Probably would be even more graceful after implementing this: https://github.com/aiven/klaw/issues/1296

fix(coral): Fix flash of stale content on TopicOverview

---

coral/src/app/features/components/EntityDetailsHeader.test.tsx
coral/src/app/features/components/EntityDetailsHeader.tsx
coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/topics/details/TopicDetails.tsx

- adds `entityIsUpdating` prop to `EntityDetailsHeader`
- passes refetching state in topic and details connector
Resolves: #1442 
https://github.com/aiven/klaw/assets/943800/629d4704-69a4-4918-b901-5aba9ae1e622

refactor(coral): disable edit button for topic/connectors while data is updated

---

coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
coral/src/app/features/team-info/TeamInfo.test.tsx

- Adds toast notification for success and error to switch-team functionality. 
Resolves: #1458

refactor(coral): Add toast notification to switch-team.

---

coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
coral/src/domain/helper/documentation-helper.ts

While my 💻  decided to have a brain fart today which lead to my local coral deciding it didn't know what ES modules are ( 🤷‍♀️  computers!), I discovered that we don't have a good error handling in case something goes wrong when we transform `stringifiedHtml` into a markdown string. We _do_ get an error and show it to the user, but since we're doing that transformation when we're getting the `topicOverview`, the error bubbled up to that until it was threaded like an error happening during that api call. 
Now, when transforming stringifiedHtml to markdown for `topicOverview`, instead of letting that error bubble, we:
- catch it
- log a `console.error` for developers / admins to be able to see it and act 
- add a very unique id as `topicDocumentation` on `topicOverview`
In …

refactor(coral): Improve error handling for documentation

---

coral/src/app/components/documentation/DocumentationEditor.tsx

Because it is rendered inside the markdown editor, the link to the CommonMark reference page link is not clickable:
https://github.com/aiven/klaw/assets/20607294/8246891a-54bd-41bf-a010-e911d0b64063
Solution is to render it outside :
https://github.com/aiven/klaw/assets/20607294/389a1c38-ef86-41f2-aac1-3abfbdca6df9

fix(coral): MD reference link unclickable

---

coral/src/app/features/topics/details/overview/TopicOverview.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.tsx

Some issues surfaced after merging the PRs for Edit (https://github.com/aiven/klaw/pull/1436) and Promote (https://github.com/aiven/klaw/pull/1420) topic, as well as with the changes made to the `promotionDetails`  property on `TopicOverview` (https://github.com/aiven/klaw/pull/1440). This PR addresses them:
- The error message was always showing on the form, because of a wrong check: 220510bc718e5db7884b205738f2281147009931
- The Promote topic form was lacking in error handling, and its tests were not well organized: 29fde145d9111ad1db84aeaa3bae4ccecdc0b078
- The Promotion banner shown on the Topic overview tab was not taking the changes to `promotionDetails` and `TopicOverview` into account: 323f7b765f667e4a20755236e5feec20672e130e
- The promotion banner now show two different state if …

(fix/refactor): Followup for Promote and Edit topic requests

---

coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx

If a user is not authorized to see the details of a subscription, then the password is `undefined`. We currenlty render nothing:
https://github.com/aiven/klaw/assets/20607294/56f8723f-0729-464f-9d0a-3c5678cc7ff6
This PR adds the same text as other pieces of data that are unavailable:
https://github.com/aiven/klaw/assets/20607294/01e2866c-e89d-42cc-b3da-a4f8ca8d7830

fix(coral): Show appropriate message when not authorized to see password

---

coral/src/app/features/connectors/details/ConnectorDetails.test.tsx
coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/model/ResourceHistory.java
core/src/main/java/io/aiven/klaw/model/response/ConnectorOverview.java
core/src/main/java/io/aiven/klaw/model/response/TopicOverview.java
core/src/main/java/io/aiven/klaw/service/BaseOverviewService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/main/resources/static/js/connectorOverview.js
core/src/main/resources/templates/connectorOverview.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
openapi.yaml

This changes the names of the connector overview to reference connectors instead of topics to reduce confusion on a shared resource.
Why this way

Update to generalise the class name for the topic and connector history

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/dao/Env.java
core/src/main/java/io/aiven/klaw/dao/KwClusters.java
core/src/main/java/io/aiven/klaw/model/response/EnvModelResponse.java
core/src/main/java/io/aiven/klaw/model/response/EnvUpdatedStatus.java
core/src/main/java/io/aiven/klaw/model/response/KwClustersModelResponse.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/EnvControllerService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/java/io/aiven/klaw/service/ServerConfigService.java
core/src/main/resources/static/js/envs.js
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
core/src/test/java/io/aiven/klaw/service/ServerConfigServiceTest.java
openapi.yaml

- uses enum `ClusterStatus` for all `clusterStatus` values instead of string
- uses enum `ClusterStatus` for all `envStatus`  values instead of string
- uses enum `ClusterStatus` as return type for `testClusterApiConnection`  values instead of string
- changes `envstatus` to `envStatus` for `EnvUpdatedStatus` model
Relates to: #1462

refactor: Use ClusterStatus enum instead of strings for clusterStatus and envStatus

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/AivenApiService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/AivenApiServiceTest.java

when an Aiven acl is deleted from Klaw, and if it doesn't exist in kafka cluster, then return SUCCESS
Resolves: #1387 
Why this way
this is basically caused by manual changes in cluster, and hence return success

Aiven acl deletion if not found on cluster

---

coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx

I have noticed an unpleasant flicker when switching between tabs in the Topic and Connector details part of the app:
https://github.com/aiven/klaw/assets/20607294/9a243480-78d6-4c29-9ff6-e1b60b6c000f
I was very confused by it, and I assumed either some `StrictMode` shenanigans, or some inefficiency in the React renderer when returning JSX which maps over `tabsMap` every time a tab content changes, and then select the content to show based on the `currentTab` prop. 
It was not `StrictMode` (removing it made the flicker less noticeable, but was still present).
The solution I found was to create a component for the returned value of `TopicOverviewResourcesTabs` and `ConnectorOverviewResourcesTabs`. This completely eliminated the flicker. I assume that the React renderer has a easier time …

fix(coral) - Topic/Connector details: fix tab content flicker on select

---

coral/.prettierrc
coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/Form.tsx
coral/src/app/features/topics/details/messages/useOffsetFilter.tsx
coral/src/app/features/topics/request/utils.ts
coral/src/services/api.ts

This PR also upgrade `prettier` to version `3.0.0`, as our current version did not support the `satisfies` syntax needed for this PR: https://github.com/aiven/klaw/pull/1480
However, given that `3.0.0` is a breaking change which has `all` as the default value for `trailingComma`, this PR also adds a `.prettierc` file to keep the `es5` behaviour. There were also some small changes bug fixes which required running `prettier --write` on the codebase to add missing semicolons and parenthesis: [0672e86](https://github.com/aiven/klaw/pull/1480/commits/0672e8678139b806189dfad94d49e71602c9e63b)

housekeeping(coral): Upgrade `prettier` to `3.0.0`

---

coral/src/domain/team/team-api.ts
coral/src/services/api.ts

Separate the API paths with dynamic parts into `DYNAMIC_API_PATHS`, which holds functions returning interpolated values for the dynamic parts of the path
Resolves: #1446
The CI fails because the current version of `prettier` doesn't recognize the `satisfies` syntax. It will be fixed after this is merged: https://github.com/aiven/klaw/pull/1481

refactor(coral): Add DYNAMIC_API_PATHS

---

coral/src/app/components/Form.tsx

`Form.tsx` uses components from `aquarium`. The `error` prop on these components is flagged for deprecation, so this PR replaces it with `helperText`. It also replaces `PrimaryButton` by `Button.Primary`.

fix(coral): Fix deprecated components and props in Form.tsx

---

coral/docs/development-with-local-klaw.md
coral/docs/development-with-remote-api.md
coral/docs/development-witout-api.md

Noticed some inconsistencies and typos while reading the new docs and trying to break the local env setup process.

fix(docs): Minor typos and formatting issues

---

coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/overview/TopicOverview.test.tsx
coral/src/app/features/topics/details/overview/TopicOverview.tsx
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
coral/src/domain/promotion/index.ts
coral/src/domain/promotion/promotion-types.ts

- adds a shared component `PromotionBanner` to be used for topics as well as schemas
- PromotionBanner takes the `PromotionStatus` as well as `hasOpenRequest` and based on that decides what to show. It's up to the components using `PromotionBanner` to decide if it should not be rendered at all because the user is not topicOwner
- it takes `topicName` as explicit prop. The `topicName` is available on promotion details for topics, but not for schemas.  
- updated `TopicPromotionBanner` to use `PromotionBanner`  internally.  
- `TopicPromotionBanner`  is responsible for passing the right promote element (which differs for topic and schema) as well as passing the right properties through. I left this as a separate component because that way it is easier to tests this well without making the …

feat(coral): Improve promotion information for schema

---

core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
core/src/main/java/io/aiven/klaw/error/KlawBadRequestException.java
core/src/main/java/io/aiven/klaw/error/KlawExceptionHandler.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/resources/static/js/requestConnector.js
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java

This updates the error response to use a proper error response code and returns just the message as an alert to the user.
Why this way
Simplifies the behaviour for the UI and is a better method for handling errors.

Return error msg to the UI when making a call to the connectors.

---

coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/features/topics/details/components/TopicClaimBanner.test.tsx
coral/src/app/features/topics/details/components/TopicClaimBanner.tsx

This PR introduces two new states to the Claim topic banner:
1. if a claim request already is opened:
https://github.com/Aiven-Open/klaw/assets/20607294/8de796ec-f030-45f3-82ea-491f5b7b8fea
2. [NOT CURRENTLY IMPLEMENTED BY THE BACKEND] if the current owners have a pending request for the topic:
The state 2. is not currently visible, as `hasOpenRequest` is currently not aware of the requests opened by other teams than the user's own team. This will however be changed by this PR https://github.com/Aiven-Open/klaw/pull/1543
Resolves: #1504

feat(coral): Add missing states for Claim topic banner

---

coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.test.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameField.test.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameField.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.test.tsx
coral/src/app/features/topics/acl-request/fields/TopicNameOrPrefixField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/details/TopicDetails.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/features/topics/schema-request/components/TopicSchema.test.tsx
coral/src/app/features/topics/schema-request/components/TopicSchema.tsx
coral/src/app/pages/topics/schema-request.test.tsx

- adds `read-only` to all labels to make it more clear for useres
- remove `required` from readOnly elements, otherwise the visual and AT feedback is a bit confusing (marking a form element as "required" is a information for the user that they need to fill this one out, but they don't, because it already has a value
Resolves: #1532

refactor(coral): Add (read-only) to labels for readonly elements

---

coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
coral/src/domain/schema-request/schema-request-api.ts

- uses `hasOpenSchemaRequest` for `SchemaPromotionBanner` since it's now added in backend
- links the correct location for seeing requests for schemas (type is always `CREATE` and not `PROMOTE` as for topics)
- 🐛  little bug fix, wrong property for operationType was used in api call

refactor(coral): Use correct property for promote schema banner

---

coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
coral/src/app/features/connectors/details/overview/ConnectorOverview.tsx

Before, we were erroneously rendering the whole Connector entity in the Connector overview (the Klaw entity):
This PR make it so that only the connector config is rendered:
Resolves: #1529

fix(coral): Connector details:  Render only connector config, add header

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java

Corrects mistakes in copies and or adds improvement to copy.
Why this way
This will make it easier for users to understand what is being shown to them.

Copy correction required for claim emails.

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java

The issue of `io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc#findAllComponentsCountForTeam` is that from one side it tries to calcute everything by running a number of quesries to db, from another side sometimes there is no need for it for instance at `core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService#deleteTeam`
so it would make sense to have lazy option. The pr adds this option

Invoke queries for finding all components in lazy mode

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/TeamRepo.java

The problem with current `io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc#selectTeamDetailsFromName` is that it requests for **ALL** teams for the specified tenant and and name and then takes only the first one.
The improvement is to select only the first one on DB level to minimize amount of data transferred between the app and DB

Find the first available team rather than all and then pick only the first one

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java

The idea is pretty straightforward.
The problem is that for every topic (almost every) it invokes `topicRepo#existsById` which is under the hood is a call to DB. That means it is a heavy call. 
The idea is to minimize a number of calls to DB by replacement of multiple calls `topicRepo#existsById` by just one `findAllById` and then processing separately  `existingTopicIds` and others

Speed up insertIntoTopicSOT

---

core/src/main/java/io/aiven/klaw/controller/ServerConfigController.java
core/src/main/java/io/aiven/klaw/model/ServerConfigProperties.java
core/src/main/java/io/aiven/klaw/service/ServerConfigService.java
core/src/test/java/io/aiven/klaw/service/ServerConfigServiceTest.java

The issue with `io.aiven.klaw.service.ServerConfigService` is that it keeps properties in a property list.
As a result to answer a question whether it contains a property with a specific key or not it should go through all properties inside that list (worst case) that means O(N) complexity.
The  obvious solution is to use `map (key, property)` then it will require to check only existence of a corresponding key and the complexity will be O(1)

Use map for props to speed up checking for existence of properties

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/EnvRepo.java
core/src/main/java/io/aiven/klaw/repository/KwClusterRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwPropertiesRepo.java
core/src/main/java/io/aiven/klaw/repository/KwRolesPermsRepo.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TeamRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/UserInfoRepo.java

The issue with current `DeleteDataJdbc` is that first it loads data into memory and then removes it...
In fact it could be done without extra loading into memory via custom deletes by condition.
The extra requirement for that is an explicit `Transactional` annotation

Use custom delete methods to avoid loading data before removal

---

core/src/main/java/io/aiven/klaw/config/MigrationUtility.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
pom.xml

It seems the update of google-java-format was missed while moving to JDK17 
The reason of sticking to `1.15.0` version is that it was the latest supported jdk 11.
Since now minimum JDK is 17 we could safely bump google-java-format

Update google java format

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java

Since there is a need only for the first available `RegisterInfo` or even only for existence then there is no need for `findByAll...` queries.
Having this in mind we could minimize amount of data transferring between the app and db

Use findFirstByUsernameAndStatus rather than findAllByUsernameAndStatus

---

cluster-api/pom.xml

Upgrades spring kafka test version. to 3.0.9
Resolves PR: #1498
Why this way

Upgrade kafka test spring

---

core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java

When authentication type is db and user pwds are "", then user doesn't have to be loaded. 
These users added only during AD auth type.
Resolves: #1220 
Why this way
For clean loading of users when auth type is db

Dont load users with empty password and auth type is db

---

coral/src/app/context-provider/AuthProvider.test.tsx
coral/src/app/features/team-info/TeamInfo.test.tsx
coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/domain/auth-user/auth-user-api.msw.ts
coral/src/domain/auth-user/auth-user-api.ts
coral/src/domain/auth-user/auth-user-test-helper.ts
coral/src/domain/auth-user/auth-user-types.ts
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java

- checks for role `SUPERADMIN` when determine the `coralIsEnabled` boolean. For `SUPERADMIN`, the preview banner with link the new interfaces are not shown anymore
- checks for `userrole` when getting auth user and, if userrole us SUPERADMIN, manually throws an unauthorized error, so user get redirected from coral to Klaw (this is in case a user accesses a link to `/coral` manually)
Users with role `superadmin` only have certain processes they can do, it's a role to admin Klaw. We're currently focusing on building all views for users, not superadmins. Since coral is now enabled as preview per default, we want to avoid superadmins to access coral, to avoid confusing - they can't access the api for things they are not allowed to do, e.g. creating a topic, but there's no reason they should …

fix(coral): Temporary deny access to coral to superadmins

---

coral/src/app/features/topics/details/TopicDetails.test.tsx
coral/src/app/features/topics/details/history/TopicHistory.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
core/src/main/java/io/aiven/klaw/model/response/SchemaDetailsPerEnv.java
core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java
core/src/main/resources/templates/execSchemas.html
core/src/main/resources/templates/mySchemaRequests.html
core/src/test/java/io/aiven/klaw/service/SchemaOverviewServiceTest.java
openapi.yaml

Add a boolean to let the UI know when to show request a new schema or only allow promotion into the environment for schemas.
Removes a check  in the html which always returned true "schemaRequest.requestOperationType !== 'APPROVED'"
Removes an unused autowired service.
Why this way

Boolean to indicate if environment can create new schema or only accept promotion.

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

The change is similar to https://github.com/Aiven-Open/klaw/pull/1573
instead of selection of all and checking for size of the collection there could be only check for existence done which minimizes amount of data transferring between the app and db

Check for existence of schema components rather than select all and check for size of collection

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

The change is similar to https://github.com/Aiven-Open/klaw/pull/1573
instead of selection of all and checking for size of the collection there could be only check for existence done which minimizes amount of data transferring between the app and db

Check for existence of connector components rather than select all and check for size of collection

---

core/src/main/java/io/aiven/klaw/helpers/ValidationHelper.java

There is a useless validation `Validate.notEmpty` since `Validate.notBlank` does the same thing + checks whether input consists of only whitespaces or not

Remove useless validation `Validate.notEmpty`

---

core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java
core/src/test/java/io/aiven/klaw/service/SchemaOverviewServiceTest.java

Small bugfix to check for schemas that are set up with RequestOperationType PROMOTE
When Schema Promotion was corrected to use the promote operation type, this check was missed.
Why this way

SchemaPromotionDetails Correct OperationType.

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

The change is similar to https://github.com/Aiven-Open/klaw/pull/1573
instead of selection of all and checking for size of the collection there could be only check for existence done which minimizes amount of data transferring between the app and db

Check for existence of kafka components rather than select all and check for size of collection

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java

Update existing check to only look for open/active schema requests when determining if it should be deleted.
Previously any request in any state would prevent the environment from being deleted, now if there are none in an open(CREATED) state it will allow the deletion/removal of the schema env.
Why this way

Delete Schema Env allowed when no open requests remain

---

coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx

Updates link to request type PROMOTE after backend update.

refactor(coral): Update link for open request to PROMOTE for schema promotion

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java

When checking if a env can be deleted we should only check for open requests not any request that has ever been made.
It adds the RequestStatus value "created" to the exists query making sure that there are no open requests.
Why this way

bugfix - Allow delete kafka env when no open reqs

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java

Adds when a connector of type promote is created to add it to the DB cache.
Why this way
Makes it available to the user straight after promotion.

Missing case for promote type operation on connectors

---

coral/src/app/components/documentation/DocumentationEditor.test.tsx
coral/src/app/components/documentation/DocumentationEditor.tsx
coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.test.tsx
coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.tsx
coral/src/app/features/connectors/details/documentation/components/NoDocumentationBanner.test.tsx
coral/src/app/features/connectors/details/documentation/components/NoDocumentationBanner.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.test.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
coral/src/app/features/topics/details/documentation/TopicDocumentation.tsx
coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.test.tsx
coral/src/app/features/topics/details/documentation/components/NoDocumentationBanner.tsx
coral/src/app/router_utils.ts

- renames "Documentation" to "Readme" (UI only) for topic and connector
- adds description to readme view (view of existing one as well as edit view)
1. No readme 
2. View for readme
3. Edit readme
Resolves: #1534

refactor(coral) - Topic/Connector details: Rename "Documentation" to "Readme" and add description

---

coral/src/app/components/Modal.tsx
coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.tsx
coral/src/domain/topic/topic-api.ts

This is an interesting one, because the bug report  #1620  actually surfaced two unrelated bugs. 
1. Details / decline modals in approval process are not removed in error cases for `topic` and `acls` (worked in `schema` and `connector`)
2. when creating an edit request for a topic, we need to use the optional paramter `otherparams` and this needs to be the `topicid`. Otherwise the request is not saved in the database. This does _not_ return an error when creating the topic edit request!  
⚠️ we will create a follow up issue for 2. to update the API. This is why the fix for 2. for now is not very elaborated and well tested, since it's going to be replaced soon anyway.
🐛  When approving a topic through the details modal or declining a topic (where a "decline modal" is open), when there was …

fix(coral): Fix UI and functional bug for approval tables

---

coral/src/app/components/DisabledButtonTooltip.module.css
coral/src/app/components/DisabledButtonTooltip.test.tsx
coral/src/app/components/DisabledButtonTooltip.tsx
coral/src/app/features/components/EntityDetailsHeader.test.tsx
coral/src/app/features/components/EntityDetailsHeader.tsx
coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/pages/topics/acl-request.tsx

There are cases where a user is allowed to edit a topic/connector in general, because they are topic owner, but the edit functionality is currently blocked because there is an open request. Before now, we didn't show the button in that case. 
In line with e.g. promoting a topic, we don't want to hide the button "Edit topic/connector" anymore, but show it disabled and inform the user why they can't edit at the moment. We're doing that by showing a disabled button with a tooltip.
_First: I sneaked in an unrelated type fix (really no need to make a new PR for one character 😅 ) -> https://github.com/Aiven-Open/klaw/pull/1637/commits/309495f1b0523f046d5e754645bd46bad9f5a1eb_ 
**Background**
- "Edit topic" and "Edit connectors" are links, not buttons (they just look like it)
- `<Tooltip />` …

feat(coral): Show info to user when they temp can not edit a topic

---

coral/src/app/components/InternalLinkButton.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.tsx

DRAFT: waiting for feedback Harshini for copy
- user should get information if a schema can not be created directly on an environment but has to be promoted
Relates to: #1592 (FE part)
(tested against local klaw to see different settings working)
Note: I made this recording before Harshini gave me feedback for the copy, so the text is wrong here. Will leave it, since it shows the core functionality. I updated the screenshots though!
https://github.com/Aiven-Open/klaw/assets/943800/5d18d2d8-031f-4538-81ba-df0ba9b10739

refactor(coral): Improve UI for schema requests per topic

---

core/src/main/resources/static/js/editTopicRequest.js
core/src/main/resources/templates/browseAcls.html
core/src/main/resources/templates/connectorOverview.html
core/src/main/resources/templates/editTopicRequest.html
core/src/main/resources/templates/execAcls.html
core/src/main/resources/templates/execConnectors.html
core/src/main/resources/templates/execSchemas.html
core/src/main/resources/templates/execTopics.html
core/src/main/resources/templates/kafkaConnectors.html
core/src/main/resources/templates/myAclRequests.html
core/src/main/resources/templates/myConnectorRequests.html
core/src/main/resources/templates/mySchemaRequests.html
core/src/main/resources/templates/myTopicRequests.html
core/src/main/resources/templates/requestAcls.html
core/src/main/resources/templates/requestConnector.html
core/src/main/resources/templates/requestSchema.html
core/src/main/resources/templates/requestTopics.html

- aligns copy for preview banner (capitalisation etc.)
- adds preview banner with links for topic overview
- updates link and link text for editing a topic (linked to /request before)
- updates link text for requesting an ACL ("ACL request" was ambiguous)
- NOTE: This also adds preview banner for connector overview, but commented out, because initially we wanted to release them. Thought I can leave it for next release. 
Resolves: #1227

feat(coral): Add and update preview links in Angular

---

coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/overview/TopicOverview.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx

Updates `PromotionBanner` to take property `hasOpenClaimRequest`: 
- if there is an open claim request, we show a link to `/approvals` (type CLAIM) and inform user that there is an open claim request
- if there is an open promotion request, we show a link to `/request` (type PROMOTE) and inform user that there is an open promotion request
- if there is another open request (e.g. update), we show a link to `/request` (type ALL) and inform user that there is a pending request
https://github.com/Aiven-Open/klaw/assets/943800/39939a38-bd08-4958-a84b-df6107d28e42
NOTE: In this recording, a little inconsistency is visible: I (as part of another team) did the claim request for the schema I wanted to show. If I'm the one making the request, I won't see it in `/approvals` because I can not approve …

fix(coral): Update handling for open CLAIM request in promotion.

---

coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx

- not topicOwner also should be able to see a schema preview
https://github.com/Aiven-Open/klaw/assets/943800/d00ae8ad-a6ef-4eb1-97c0-e09aebcaa130

fix(coral): remove `schemaPromotionDetails` from check for noSchema

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java

This change uses a string for the approving team comparison as the kafka connector and topic requests have a string type for appronving team, but an integer type for the teamId
Why this way
This allows the queries to run against the H2 and postgres (and other dbs)
Tested this against a local postgres and local H2

Update to use a type of String to make queries

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx

- both are links to pages that only superadmin has access to, so they are removed from coral (currently only supporting views for users)
Resolves: #1655

fix(coral) Remove "User requests" and "Settings" from nav.

---

cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java

After updating the compression type, a sleep makes sure the update is completed
Why this way

Add sleep for update cmp type

---

coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
coral/src/app/features/team-info/SwitchTeamsDropdown.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx

- `SwitchTeamDropdown` used `refetchQueries` -  I changed that to `invalidateQueries`. refetchQueries will try to refetch all queries on the spot, which will cause errors, cause for some parameters are not there yet. invalidateQueries will invalidate the queries and when the parameters have changed (indicating they need a new fetch) fetch the data
**before**
https://github.com/Aiven-Open/klaw/assets/943800/b443f6a7-01a9-4e69-8a62-9a8eac32d048
**after**
https://github.com/Aiven-Open/klaw/assets/943800/2effc374-0c13-491e-9580-4bd725408e40
**before**
https://github.com/Aiven-Open/klaw/assets/943800/0ffa4786-1f7d-4770-995d-b30bc6a71d33
**after**
https://github.com/Aiven-Open/klaw/assets/943800/1cc32f22-ae1b-4d50-9154-2d584a1b1a32
Resolves: #1501

fix(coral): Remove unnecessary re-mounting

---

core/src/main/resources/static/js/manageUsers.js

When adding a new user, and enabling switch teams, even after selecting own team, validation fails
Why this way

Add user switch team fix

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
openapi.yaml

Currently major part of consumer groups validation happens in memory with preliminay loading lots of data into memory.
The PR makes it on DB level minimizing amount of data transferring between the app and db

Validate consumer groups in sql

---

core/src/main/java/io/aiven/klaw/model/requests/AclRequestsModel.java

Add username or Service Account as the invalid object as it depends on the kafka provider as to the name provided to this value.
Resolves: #1670
Why this way

Update to provide a better error message to users creating ACLs.

---

coral/src/app/features/topics/acl-request/form-schemas/topic-acl-request-shared-fields.ts

Backend has validation for service account names to have at least 3 characters (3 and more) but we checked for more then 3 characters (4 and more). This caused valid service accounts that user could chose from the list to cause a validation error in frontend so users could not submit there request. 
This PR changes the min characters and updates the message in wording, too, so it's less confusing.
(I said "should have more than 3 characters" and there's a high chance user don't register "more than" and focus on 3, which was wrong)
I created a follow up ticket for more validation, too: https://github.com/Aiven-Open/klaw/issues/1675
https://github.com/Aiven-Open/klaw/assets/943800/42e02602-96da-4c98-91f0-1c1fdc8fb794
Resolves  #1671

fix(coral): Update validation for service accounts field

---

coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.test.tsx
coral/src/app/features/topics/details/subscriptions/components/TopicSubscriptionsDetailsModal.tsx
coral/src/domain/acl/acl-api.ts

in topic-overview -> subscriptions when opening the details modal, the password was not shown for users that did have permission to see it. 
This PR updates a (very misleading named :D) parameter `userName` to actually be the `serviceName` to fix this. 
1. user without permission
2. user with permission
1. user without permission
2. user with permission
Resolves: #1668

fix(coral): Use right parameter for `getAivenServiceAccountDetails`.

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/RequestStatisticsService.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java

The idea is to simplify this method and to minimize size of map transferring

Simplify SelectDataJdbc#getTopicRequestsCounts

---

coral/src/app/components/Modal.module.css

- adds a slight margin for the element settig the overflow for modal children, so the focus styles have anough room to show. 
claim modal
decline modal
promote modal
promote modal
claim modal
decline modal
Resolves: #1683 
Why this way

fix(coral):  fix focus style on focusable elements in modals

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/UserInfoRepo.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

In a couple of cases it's better to use `exists` rather than `getAll` to minimize amount of data transferring between db and the app

Introduce existsByTeamIdAndTenantId instead of getAll

---

coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/layout/header/HeaderNavigation.tsx

1. removes tooltip in decline button for ACL approvals
(It's the only button that has it. It's unecessary, since the connection between button and topic is visual. This is the screen reader text that is shown. And the tooltip is only working with mouse, so it's not really accessible anyway. 
https://user-images.githubusercontent.com/943800/262703207-5f15a00e-be25-46a9-9e38-68ce0b2e0d93.png
2. Remove tooltip for "Request new..." button. Has no effect whatsover.
Resolves: #1684

refactor(coral): Remove unnecessary tooltips

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

- fix error message not cleared properly when switching between Literal and Prefixed pattern types
- only fetch `teamId` when submitting the request, not on every change of `topicname` and other dependencies.
https://github.com/Aiven-Open/klaw/assets/20607294/0a365b01-bf3c-4050-b8f7-ececf3661a0b
Resolves: #1669

bug(coral) - ACL request form : Fix error in Topic name field, only fetch `teamId` when needed

---

coral/test-setup/mock-monaco-editor.tsx

- update mock for monaco editor to not use `jest.fn()`
Background: There's no need for using jest.fn() as a mock. Also, when using `jest.resetAllMocks` or `jest.restoreAllMocks` in a test, this will effect this mock and lead to unexpected behaviour, since the mock is not explicitly added in the test suite. 
Resolves: #475
(it does not really resolve this issue, but relate to it, and we won't investigate a more sophisticated way to mock the editor for now)

refactor(coral): Update monaco editor mock

---

coral/src/app/features/connectors/details/components/ConnectorPromotionBanner.test.tsx
coral/src/app/features/connectors/details/components/ConnectorPromotionBanner.tsx
coral/src/app/features/connectors/details/overview/ConnectorOverview.test.tsx
coral/src/app/features/connectors/details/overview/ConnectorOverview.tsx
coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx

Adds promotion banner to Connector overview. 
NOTE: There is an open PR for adding the actual form that the banner links to for promotion ( #1723 ) so following the link at the moment will show a 404. 
Relates to: #1639

feat(coral): Add promotion banner to connector promotion

---

coral/src/app/features/connectors/request/ConnectorPromotionRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorPromotionRequest.tsx
coral/src/app/features/connectors/request/components/ConnectorSkeletonForm.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/pages/connectors/promotion-request.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/index.ts
coral/src/domain/promotion/index.ts
coral/src/domain/promotion/promotion-types.ts
coral/src/domain/topic/index.ts

Is part of #1639
Testing on staging: e.g. https://localhost:5173/connector/Aindriu45/request-promotion?sourceEnv=4&targetEnv=6
- adds routing and page for promotion request
- adds api endpoint 
- adds form to promote connector

feact(coral): Add form to request connector promotion

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/services/test-utils/render-form.tsx

react-hook-forms expects the `onSubmitHandler` to return a Promise to be able to show `formState.isSubmitting` properly. We're using `mutate` from react-query, so this does not work. 
This PR updates the `SubmitButton` in `Form` to:
- if a property `loading` is passed, this property will be used to get a loading state on the button, otherwise it will take the state from `isSubmitting`. 
This way, we can pass `isLoading` from `mutate` to `SubmitButton` if needed but are still able to rely on `isSubmitting` in cases we don't use react-query.
This shows the `TopicRequest` form with passing `loading` in `SubmitButton`. 
https://github.com/Aiven-Open/klaw/assets/943800/0cac5159-e553-4d20-8010-9359fcea0ab1
Resolves: #1439

fix(coral): Fix proper loading state for `SubmitButton` in `Form`

---

coral/src/domain/environment/environment-api.ts

Don't return Kafka envs for all three endpoints 🤦

fix(coral): Use correct path for paginated envs endpoints

---

coral/src/domain/environment/environment-test-helper.test.ts
coral/src/domain/environment/environment-test-helper.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/helpers/Pager.java
core/src/main/java/io/aiven/klaw/model/response/EnvModelResponse.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
openapi.yaml

The designs for the Environments configuration section shows badges in the tabs with the total count of environments for each tab.
Because we want to use the paginated endpoints to fetch the data for these tabs, we do not have an eqasy way to compute this value on the front-end.
However, this value is available as `totalRecs` in `Pager.java`.
This PR adds this `totalRecs` value to the reponse payload `EnvModelResponse`.
This was discussed previously with @aindriu-aiven , but I am not sure if this implementation is the one we want. 
Additionally, unsure if this requires some testing in the backend.
Tested the endpoints locally in the context of this tabbed navitgation:
https://github.com/Aiven-Open/klaw/assets/20607294/c09dd94f-2a00-490e-91a0-a97aa433aa68

feat(api): Add `totalRecs` to `EnvModelResponse`

---

coral/src/services/test-utils/api-mocks/server.ts
coral/test-setup/setup-files-after-env.ts

Initialises the msw server beforeAll test suites for jest, hopefully this will surface missing mocks sooner for us.

fix(coral): Add `server` for all test suites

---

core/src/main/java/io/aiven/klaw/dao/Acl.java
core/src/main/java/io/aiven/klaw/dao/AclRequests.java
core/src/main/java/io/aiven/klaw/helpers/AclIPPrincipleTypeConverter.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java

* Remove custom exists queries and use jpql to have spring do queries based on the drivers which handle all details
* Update to rectify exists statement that had a not clause in it.
* Use a converter to ensure that the data is converted correctly from the DB to the app and vice versa
---------
Merge into a branch release251 which has been branched from tags/v2.5.0 to create a 2.5.1 release with a number of fixes to support mysql.
Why this way

MySQL Exists statement Support (#1760)

---

core/src/main/java/io/aiven/klaw/helpers/Pager.java
core/src/test/java/io/aiven/klaw/helpers/PagerTest.java
core/src/test/java/io/aiven/klaw/service/EnvsClustersTenantsControllerServiceTest.java

`deriveCurrentPage` did not account for the cases when `pageNo` is passed as a stringified int, as coral does to handle pagination, breaking pagination on coral.
This PR changes the `default` case to not return the `currentPage` but the `pageNo` when `pageNo` is a stringified number.
https://github.com/Aiven-Open/klaw/assets/20607294/16e298e6-e4a7-40ea-9955-ef7e7fb4ac76
Resolves: #1770

fix(core): Allow `Pager` to return `pageNo` as `currentPage` when `pageNo` is a stringified int

---

coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.test.tsx
coral/src/app/features/connectors/details/components/ConnectorOverviewResourcesTabs.tsx
coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
coral/src/domain/connector/connector-api.ts
coral/src/domain/topic/topic-api.ts

**(this all goes for connectors, too)**
`TopicOverview` has a property `topicInfoList` that, based on openapi, is required and always there (https://github.com/Aiven-Open/klaw/blob/main/openapi.yaml#L7691). But if a topic does not exist anymore, the endpoint `/getTopicOverview` will return a `TopicOverview` with _no_ `topicInfoList`. 
Since coral assumes based on typing a specific behaviour, this causes an error in our code, which leads to this error message for user:
We never get to the information that a topic does not exist, because the not-existent `topicInfoList` will throw an error before. 
This also means in the rest of the API the topic and topic-info will be treaded as existent.
There were two way to solve this:
1) (not done): mark `topicInfo` in our api types as optional. 
not …

fix(coral): 🐛  handle not existent topic/connector correctly

---

coral/src/app/layout/Layout.test.tsx
coral/src/app/layout/LayoutWithoutNav.test.tsx
coral/src/app/layout/header/HeaderMenuLink.test.tsx
coral/src/app/layout/header/HeaderMenuLink.tsx
coral/src/app/layout/header/HeaderNavigation.test.tsx
coral/src/app/layout/header/HeaderNavigation.tsx
coral/src/app/layout/header/ProfileDropdown.module.css
coral/src/app/layout/header/ProfileDropdown.test.tsx
coral/src/app/layout/header/ProfileDropdown.tsx
coral/src/domain/auth-user/auth-user-api.ts
coral/src/domain/auth-user/index.ts

- adds the profile dropdown menu in header
- adds logout functionality
- 🐛 additionally it updated the `HeaderLink` component to show internal and external links, because the link to `/approvals` did lead user to the Angular start page
Note: I tested all links in the build and they work
https://github.com/Aiven-Open/klaw/assets/943800/beafc901-0ab9-4cee-b149-8ffc42ef92e2
Resolves: #1758

feat(coral): Add profile dropdown

---

coral/src/app/features/configuration/environments/components/EnvironmentStatus.test.tsx
coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx

I discovered that in the Environments tables, the "update status" button would not work after the first two clicks (no API call dispatched, no loading state). This was because of the caching mechanism of react-query, which would keep the `isSuccess` value to `true` throughout the refetching. 
https://github.com/Aiven-Open/klaw/assets/20607294/da1fbc56-bc34-4c82-90c5-c429a7aff7d4
- make the `useEffect` also dependent on `isFetching`
- remove `isRefecthing` use, as it is superfluous in this case
- improve tests
https://github.com/Aiven-Open/klaw/assets/20607294/dc36e0a6-9198-48c4-bd5b-b28f54ca8056

fix(coral): Show environments:  Fix unable to refresh status after first two clicks

---

core/src/main/java/io/aiven/klaw/model/requests/EnvModel.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/resources/db/changelog/changelog.yaml
core/src/main/resources/static/js/envs.js
core/src/main/resources/static/js/modifyEnvs.js
core/src/main/resources/templates/addSchemaEnv.html
core/src/main/resources/templates/modifyEnv.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java

- cluster api url - connectivity bug fix for resttemplate
- extend length of environments table (schema env)
Resolves: #1787 
Why this way

Fix cluster connect url resttemplate, extend schema env length

---

.github/PULL_REQUEST_TEMPLATE.md

Below you can see what the template looks like: 
n/a
The PR template is very sparse and doesn't encourage a detailed approach
New PR template is a little more detailed and easier to "fill in"
This is only a suggestion, and we may want something different.

fix: Improve automated PR template

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java

The PR makes use  of `getCountRegisterUsersInfoForTenant` rather than getAllRegisterUsersInfoForTenant 
also it does it in lazy mode instead of invoking it always

Use getCountRegisterUsersInfoForTenant instead of getAllRegisterUsersInfoForTenant if possible

---

coral/src/app/features/components/ClaimBanner.test.tsx
coral/src/app/features/components/ClaimBanner.tsx
coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/topics/details/TopicDetails.tsx

Resolves: #1756 
If a topic/connector has an open promotion request, users from different team will see the "you can claim this" banner and be able to do a claim request. This can cause all kind of messes, e.g. a topic on different environments belonging to different teams etc.  Reason was that the property `hasOpenRequest`, that we used to check that, only checks request on the current environment, but a promotion request belongs to the target env. 
We have a new property in the backend, `hasOpenRequestOnAnyEnv` that, well, shows if there is any request open on any env. We now use this to decide how the claim banner looks and if user can claim.

refactor(coral): Use new property `hasOpenRequestOnEnyEnv` for Claim Banners

---

core/src/main/java/io/aiven/klaw/service/EnvControllerService.java
core/src/test/java/io/aiven/klaw/service/EnvControllerServiceTest.java

Resolves: #1773 
It was noted that the auto environment check was not adding the time stamp to when the environment was checked.
The envStatus timestamp is now added to the env object, and the also the reload cache function was removed as it was not required to keep the cache in sync.

Add timestamps to status check, remove reloading of cache on the hour.

---

coral/package.json
e2e/package.json

If the generated `api.d.ts` breaks one of our linting rules, it will be prevented from being committed by the pre-commit `lint-staged` rules. This is undesirable, as it is an automatically generated file that no human should edit.
- Exclude `api.d.ts` from being formetted and linted
- Adds a rule to check Prettier formatting of md files

fix(coral): Exclude api.d.ts from lint-staged, add md linting

---

coral/src/app/features/components/AclDetailsModalContent.tsx
coral/src/app/features/components/ConnectorDetailsModalContent.tsx
coral/src/app/features/components/SchemaRequestDetails.tsx
coral/src/app/features/components/TopicDetailsModalContent.tsx
coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx

We replaced the deprecated `Flexbox` by `Box.Flex`. However, the `direction` prop that was on `Flexbox` has been replaced by `flexDirection` on `Box.Flex`. This results in broken layouts, as the `direction` attribute is applied to the underlying `div` (which does nothing)
Restore correct layout by using the correct prop.

fix(coral): Replace `direction` by `flexDirection` on `Box.Flex`

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/UserInfoRepo.java

In `SelectDataJdbc#getDashboardStats` it's better to use count query instead of select all to get number of rows

Use countByTeamIdAndTenantId for counting instead of select all

---

cluster-api/pom.xml

There is a guava version configured in parent pom and there is not need to have another one
Moreover this one isn't used and not updated (from parent it is alredey referenced to guava 32.x while this only to 31.x)

Remove  useless guava version

---

.github/workflows/jobs-maven.yaml
pom.xml

The problem with current lombok version is that build fails with an attempt to build it with jdk21
because of this issue https://github.com/projectlombok/lombok/issues/3393
which has been fixed in 1.8.30
so to have it working need to bump lombok a bit
PS: so far GH does not support jdk21 `temurin` that's why I didn't update GHA
however it supports jdk21 `corretto` (AWS jdk build) we could either wait for `temurin` or try it with `corretto`

Bump lombok version to allow build it with jdk21

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java

count query always returns a number even if there is no data at all it will return zero
so no need for usage of arrays, lists or optionals

Use int for count query instead of list of array of objects

---

core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java

for `contains` call it's better to use set since it checks it for O(1) time rather than O(n)

Use set for contains call

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/features/topics/schema-request/form-schemas/topic-schema-request-form.ts
core/src/main/resources/static/js/browseAcls.js
core/src/main/resources/static/js/requestAvroSchemaUpload.js
core/src/main/resources/static/js/requestTopics.js
core/src/main/resources/templates/requestSchema.html
core/src/main/resources/templates/requestTopics.html

Force register a new schema also auto select the default partition and replication numbers on a new topic request.
Resolves: #1882 

Force register a new schema

---

core/src/main/resources/static/js/requestAvroSchemaUpload.js

- [ X] Bug fix
Submission of schema request happens both on headers/parameters and body. Only body should exist
Request parameters is deleted in the post call

Remove schema submission in headers/parameters

---

coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx

While we disable the "Create a new schema version" button when there is an open request, we didn't disable it when there was an open promotion request. But user can't create a new version when there is an open promotion request. This is a frontend-only issue, since the creating in the backend (rightfully) failed anyway.
https://github.com/Aiven-Open/klaw/assets/943800/47471872-5934-4d61-8de5-8b6e53c7ac29
Now we disable this button in case there is an open request, so user don't go through the process of creating a new version and then get an error. 
https://github.com/Aiven-Open/klaw/assets/943800/92ab11ad-ba81-4a27-a4a2-c1b32b5c092a
I noticed a typo in the promotion banner and fixed that. It said "A**n** promotion request for..." instead of "a promotion request". I think we had "An open …

fix(coral): Disable creating schema version when open promotion request

---

coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/components/SchemaRequestDetails.test.tsx
coral/src/app/features/components/SchemaRequestDetails.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Resolves: #1882
This PR adds a consistent flow how user can force register a schema:
- first call to create / promote a schema is done in the usual flow
- in case a _specific_ error returns, the user gets the option to force register the schema
- this option is shown with a warning and a checkbox. 
- when the error was returned, buttons (to submit, promote etc) are _disabled_ and show a more specific text
- the buttons only are enabled once the user has checked the box
(otherwise, user could click the button again, get the same error, but nothing in the UI changes, so it's very confusing)
- if they did, the request will be sent with the option "forceRegister" true
This is done in the TopicSchemaRequest form (this is used for creating and requesting a new version) as well as in the …

feat(coral): Add force register to flow and tables

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/service/DefaultDataService.java
core/src/main/resources/application.properties
docker-scripts/docker-compose-klaw.yaml

Resolves: #1922 
Docker Compose setup won't work with the current `docker-compose-klaw.yml` due to the default of https in `klaw.uiapi.servers`.
`docker-compose-klaw.yml` is using the `KLAW_UIAPI_SERVERS` environment variable to overwrite the URL. Additionally a new config `klaw.clusterapi.url` has been added to `application.properties` so that the endpoint can be overwritten using the `KLAW_CLUSTERAPI_URL` environment variable and by that eliminating one manual step when using docker without the quickstart option.
n.a.

fix: Issue 1922 fix docker quick start setup

---

coral/src/app/features/configuration/environments/components/EnvironmentStatus.tsx

`EnvironmentStatus` uses the deprecated `GridItem` component. Now that `aquarium` is at v 1.43.0, we should use `Grid.Item`
Use `Grid.Item`

refactor(coral): Replace depracted GridItem in EnvironmentStatus

---

coral/src/app/features/components/EntityDetailsHeader.test.tsx
coral/src/app/features/components/EntityDetailsHeader.tsx
coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/pages/BreadCrumbsWithLinks.test.tsx
coral/src/app/pages/BreadCrumbsWithLinks.tsx

There is no breadcrumbs in the nested routes (mostly the individual connectors and topics pages).
Add breadcrumbs to Topic details and Connector details pages through `EntityDetailsHeader`.
https://github.com/Aiven-Open/klaw/assets/20607294/45e8bcc3-3749-4592-8253-51790dff1b72
This unpleasantness with `ts-ignore` will be fixed in a subsequent version of `aquarium`: https://github.com/Aiven-Open/klaw/pull/1932/files#diff-805d4419c6d9a1a062e4daa353ee8b9f17e7a0a70df1db782699559982c0cc95R4-R11
The reason for it is a wrong assertion of the return type of `asCrumb`.

feat(coral) - Add breadcrumbs to `EntityDetailsHeader` 

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-test-helper.ts

We are currently exporting `mockedEnvironmentResponse` from `environment-api.msw.ts`. We are removing our use of `msw`, and there is a `environment-test-helper.test.ts` which is used to export such helper values.
Export `mockedEnvironmentResponse` from  `environment-test-helper.test.ts`

refactor(coral): Move `mockedEnvironmentResponse` to helper file

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

Current implementation tries to load all teams by tenantid and then filter it by teamid in java...
At the same time there is already existing method to filter it on db level
The PR is aiming to use this to reduce java load

Use selectAllTeamsByTenantIdAndTeamId if possible

---

coral/src/app/NoCoralAccessSuperAdmin.test.tsx
coral/src/app/components/NoCoralAccessSuperadmin.tsx
coral/src/app/context-provider/AuthProvider.tsx
coral/src/domain/auth-user/auth-user-api.ts
coral/src/domain/auth-user/index.ts
core/src/main/java/io/aiven/klaw/model/response/AuthenticationInfo.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/templates/index.html
core/src/test/java/io/aiven/klaw/controller/UtilControllerTest.java

**NOTE: Stays draft until OK from Harshini and Venla**
- superadmin user don't see a preview banner when coral is enabled
- if a superadmin tries to access a coral route, they are redirected to /login
- superadmin see a banner informing them about the new interface for users if coral is enabled in built
- if a superadmin tries to access a coral route, they get a reduced page informing them about that coral is only for users and offers a link to either login or the old ui
(on my local built)
https://github.com/Aiven-Open/klaw/assets/943800/901376d0-9e7f-40df-b3ca-5d18072e4e80
https://github.com/Aiven-Open/klaw/assets/943800/1f25687d-80c0-4740-9ce7-4bf8b1460ef3

refactor: Inform superadmin user better about coral

---

coral/src/app/features/components/filters/TeamFilter.tsx
coral/src/app/features/configuration/teams/Teams.test.tsx
coral/src/app/features/configuration/teams/Teams.tsx
coral/src/app/features/configuration/teams/components/TeamsTable.test.tsx
coral/src/app/features/configuration/teams/components/TeamsTable.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/configuration/teams/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/src/domain/team/index.ts
coral/src/domain/team/team-transformer.ts
coral/src/domain/team/team-types.ts
coral/src/services/feature-flags/types.ts
coral/vite.config.ts

Resolves: #1182 
This PR introduces the Teams view based on the current UI.
Note: There's no layout for teams in Figma, but for users. I synced with Venla and we're keeping the currently implemented "1 page for teams, 1 page for users" structure, as it mirrors the Angular app. This is why there are no tabs. 
- renames `Team` and `AllTeams` types to be more fitting
- renames query for getting teams for topics, as it's the same endpoint and enables better caching
- adds a feature flag for team and user view
- adds new team page and link to it behind feature flag

feat(coral): View teams

---

core/src/main/java/io/aiven/klaw/controller/RequestController.java

The idea is that in case of multistatus there is no need to go through all the responses
it is just enough to know that there is at least one success and one failure, after that we could safely finish the iteration process

Add short path for multistatus

---

coral/src/services/api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
core/src/main/java/io/aiven/klaw/controller/TemplateMapController.java
core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/resources/static/js/editAvroSchemaUpload.js
core/src/main/resources/static/js/requestAvroSchemaUpload.js
core/src/main/resources/templates/editSchemaRequest.html
core/src/main/resources/templates/execSchemas.html
core/src/main/resources/templates/mySchemaRequests.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
openapi.yaml

Resolves: #1737 
- [ X] New feature
Currently it is not possible to edit the schema requests created by owners of the requests
- Users who created requests will be only able to edit them
- Requests should be only in CREATED state

Edit schema reqs

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

Activitycount instead of the date is returned for the x axis.
The date is now returned for the x axis
There is a second unrelated but new issue on the Topics per cluster graph which I will open a separate PR for.

Update to return the days the requests occur on for Requests Per Day

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/resources/templates/index.html

Currently the graph Topics per Cluster is not rendering
Now renders as expected and also made an improvement to remove the initial white space entry that was added.

Topics per cluster graph defect

---

coral/src/app/features/components/layouts/TableLayout.tsx

Resolves: #1927
The filters rendered in the `TableLayout` are too small for most content
Better behaviour all around for this row:
https://github.com/Aiven-Open/klaw/assets/20607294/5de01e30-98e5-4bc7-8797-3866c8c8e2c8
I am opening this PR as it is needed to render the UI for https://github.com/Aiven-Open/klaw/issues/1989

fix(coral) - Fix `TableLayout` filters row

---

coral/src/app/features/components/filters/TeamFilter.test.tsx
coral/src/app/features/components/filters/TeamFilter.tsx
coral/src/app/features/components/filters/useFiltersContext.tsx
coral/src/app/features/configuration/users/Users.test.tsx
coral/src/app/features/configuration/users/Users.tsx
coral/src/app/features/configuration/users/components/UsersTable.test.tsx
coral/src/app/features/configuration/users/components/UsersTable.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/main.module.css
coral/src/app/pages/configuration/users/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/src/domain/user/index.ts
coral/src/domain/user/user-api.ts
coral/src/domain/user/user-transformer.ts
coral/src/domain/user/user-types.ts
coral/vite.config.ts

Resolves: #1176 
Adds user overview based on layout and existing app, similar to teams overview. 
https://github.com/Aiven-Open/klaw/assets/943800/9b9341f0-ff09-4183-92bf-c08c173caf58
- adds pages and links to it behind a feature flag
- adds user table with pagination
- adds `user` domain with api call and types for getting the user list
- Extents the existing `<TeamFilter />` to optional handle `teamName` instead of `teamId`
- According to that extends userFilterContext
- adds filter for team name
- adds search for user name
Unrelated change, but I noticed it:
(this may be related to a DS update since it's not as visible on staging)
- update the `main.module.css` to overwrite browser styles for the little X in a search input (was only in webkit browser)
This is how it looked before:

feat(coral): View users

---

core/src/main/java/io/aiven/klaw/helpers/KlawResourceUtils.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java

Since there is a number of contains calls agaist ordered env it would make sense to use set here to make it a bit faster.
At the same time since order is important linkedhashset will help here

Use set for ordered env

---

core/src/main/java/io/aiven/klaw/service/MailUtils.java

The only reason for having this collection is checking for contains during filter below, for this purpose set suites better since it's faster for contains operation

Use set for roles

---

core/src/main/java/io/aiven/klaw/helpers/AivenAclIdConverter.java
core/src/main/java/io/aiven/klaw/helpers/DefaultAttributeConverter.java
core/src/main/java/io/aiven/klaw/helpers/EnvParamsConverter.java
core/src/main/java/io/aiven/klaw/helpers/EnvTagConverter.java
core/src/main/java/io/aiven/klaw/helpers/ServiceAccountsConverter.java
core/src/main/java/io/aiven/klaw/helpers/SwitchTeamsConverter.java

There is a number of converters like `AivenAclIdConverter`, `EnvParamsConverter`, `ServiceAccountsConverter`, `SwitchTeamsConverter` with duplicated logic
The PR introduces reusable `io.aiven.klaw.helpers.DefaultAttributeConverter` which could be extended to encapsulate common logic and keep it in one place

Add DefaultAttributeConverter

---

bin/run-klaw.bat
bin/run-klaw.sh

- [ X] Bug fix
Startup scripts in bin dir would not execute properly if ran from a different dir
setting the working dir properly now

Update startup scripts

---

core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

When another team loads the promotion details when setting to NOT Authorized, it throws a null pointer is caught by a catch and returns the correct NOT Authorized.
When another team loads the promotion details setting it to NOT Authorize (no null pointer/try-catch etc)

Fix null pointer exception that was hidden in the logs

---

coral/src/app/layout/header/ProfileDropdown.test.tsx
coral/src/app/layout/header/ProfileDropdown.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/user-information/change-password/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts

Resolves: #2023
There is no coral routes amdpages for the change password feature
Add necessary routes, page and links for accessing change password feature
https://github.com/Aiven-Open/klaw/assets/20607294/25df3288-6123-467a-b93b-e9e48283e39a

feat(coral): Add change-password route, page and links

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

There is now support for checksum checks while downloading maven 
this support is added here
also there is suppport for similar check for wrapper however it doen not work well for Windows as mentioned at
[MVRAPPER-103](https://issues.apache.org/jira/browse/MWRAPPER-103).
Now it is commented till the issue is fixed
most of the changes are result of generated code via command `./mvnw wrapper:wrapper`

Add distributionSha256Sum for maven

---

core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java

There is no need to load whole lists to answer a question whether there is at least one entity or not within these lists

Use  where existsConnectorRequestonly existence check is required

---

coral/src/app/components/Form.tsx

User can manipulate form elements that are disabled / readonly and change values. This is not a problem, because we validate everything in backend and the changes will not go through. 
To be double safe, we now handle this additionally in Frontend and don't allow elements that are disabled/readonly in `Form` to handle the events. This does only affect elements used in `Form` context. 
There are not tests added for this, since we can't simulate this kind of user manipulation in our tests.

refactor(coral): Update Form to not handle events for readonly or disabled elements

---

core/pom.xml

This change moves coral resources to the target folder after the main resources folder is copied to the target folder
The change also adds a complete delete of the coral dist folder to ensure that coral is re-built every time.
The coral dist is copied to the main resources folder after the resources folder is copied to the target folder.
The Coral dist is copied to the target folder after the main resources folder is copied to the target folder already.

Fix pom coral build

---

coral/src/app/layout/header/ProfileDropdown.test.tsx
coral/src/app/layout/header/ProfileDropdown.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/user-information/tenant-info/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts

Resolves: #2047
The links to Tenant info only direct to Angular app.
Add routes and components to go to `coral` when feature flag is active.

feat(coral): Tenant info:  add route, page, `MainNavigation` and `ProfileDropdown` links

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
core/src/test/java/io/aiven/klaw/TopicRequestValidatorImplIT.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java

The idea is to use `exists` on db level instead of select everything and then check whether list is empty or not

Check for existence for topic requests on db level rather than on java

---

coral/src/app/features/user-information/profile/Profile.test.tsx
coral/src/app/features/user-information/profile/Profile.tsx
coral/src/app/features/user-information/profile/components/SkeletonProfile.tsx
coral/src/app/features/user-information/profile/components/TeamsOverview.test.tsx
coral/src/app/features/user-information/profile/components/TeamsOverview.tsx
coral/src/app/features/user-information/profile/form-schema/profile-form.ts
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/pages/user-information/profile/index.tsx
coral/src/domain/user/index.ts
coral/src/domain/user/user-api.ts

Resolves: #2019 
- adds `Profile` component to view and edit profile
NOTE: I sneaked in a link to the teams page after making the recording and screenshots
https://github.com/Aiven-Open/klaw/assets/943800/67bb3583-f321-430b-917e-2343d9a5cc18
(message mocked by me)

feat(coral): View and update user profile

---

core/src/main/java/io/aiven/klaw/service/SchemaRegistrySyncControllerService.java

Currently username and tenantId are loaded alwas before checks where they are not required.
At the same time based on this checks it could happened that method will just return.
In this case there is no need for loading such data, so just move logic for loading data after these checks in case they are successful

Load user info in lazy way

---

cluster-api/pom.xml

In fact in spring boot internally only one property is used
I do not see any reason we should have more properties

Use one property for kafka and kafka clients

---

core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java

Resolves: #2090
`getRequestsStatistics` will count Claim requests as available for approval, when they are not.
Do not count Claim requests if:
- they are created by the team of the user
Count the Claim requests if:
- they are not created by the team of the user
Some tests had to be changed so the build could complete, but I am not sure if it's only because of the change in behaviour, or if the changes introduced a bug. 
Naively looking at the app, I could only ascertained that the fix *seemed* to now return accurate count for requests available for approval.

fix(core): Count claim requests correctly with `getRequestsStatistics`

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/service/ExportImportDataService.java
core/src/main/java/io/aiven/klaw/service/ServerConfigService.java

Currently there are places where `OBJECT_MAPPER` is going to be configured each time during method invokation.
Actually it could be done only once during init and all useless calls could be removed then

Configure object mapper during init rather than each time during method invokation

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

Since there is no real usages for `envModelsClustersStatus` it could be removed

Remove unused envModelsClustersStatus

---

core/src/main/java/io/aiven/klaw/config/ConfigUtils.java
core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java

Removes deprecated calls in web security config
Certain calls like csrf, oauth2Login, login, formLogin are deprecated
Update code 

Remove deprecated calls in web security

---

coral/src/app/layout/main-navigation/MainNavigationSubmenuList.tsx

The expandable menu items are not opening when user access a submenu in them from a link. For example: When "user information" is closed and I open the Profile dropdown, click on "User profile", then the "User information" stays close, even so "User profile" is active. 
Technically:
While the  initial value of `open` is set correctly (based on the property `defaultExpanded`, changes in `defaultExpanded` are not updating this state. 
Works ^^
We're updating the state when the prop updates now.

fix(coral): Update state for open submenu correctly

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/router.tsx
coral/src/services/feature-flags/types.ts
coral/vite.config.ts

Clusters view is behind a feature flag because it was waiting on this fix: https://github.com/Aiven-Open/klaw/pull/2071
Remove feature flag

feat(coral): Remove feature flag for cluster view

---

core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java

There are `getTopicNames(tenantId)` and `getConsumerGroups(tenantId)` invoking in a loop however they do not depend on loop variables that means they always return same result. For that reason they could be moved from the loop and precalculated only once

Speed up report generation

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwPropertiesRepo.java

The PR is about to reduce amount  of calls to db by replacement of `io.aiven.klaw.repository.KwPropertiesRepo#findAllByTenantId` with `io.aiven.klaw.repository.KwPropertiesRepo#findAllByTenantIdsOrdered` and this is allowed to have one call to db instead of call per loop's iteration

Use findAllByTenantIdsOrdered to reduce amount of calls to db

---

core/src/main/java/io/aiven/klaw/helpers/KlawResourceUtils.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

The idea is to use sets to speed up `getConvertedEnvs`

Use set rather than scan list

---

coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/topics/request/TopicEditRequest.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/app/features/user-information/change-password/ChangePasswordForm.tsx

Resolves: #1749 
Prevents user from submitting / canceling all forms while a request is in progress. 
Note:
I tried to find a good way to test this, but since it's a async process, the tests are either brittle or we need to work with a timeout, which slows all tests down. I felt that is unnecessary for this functionality, I tested all forms manually.

refactor(coral): Prevent action for submit and cancel buttons in form while mutation is ongoing

---

coral/package.json
coral/pnpm-lock.yaml
coral/vite.config.ts

Deploying the branch with the aquarium update here: https://github.com/Aiven-Open/klaw/pull/2164
Cause breakage in coral on staging. @aindriu-aiven was able to aacretain that the commit before the vite update was working, so we think this update may have had unintended side effects.
Revert vite upgrade.
We still don't know what happened, or why the aquarium update triggered it...

fix(coral): Revert vite v5 upgrade

---

coral/src/app/features/configuration/users/components/UsersTable.test.tsx
coral/src/app/features/configuration/users/components/UsersTable.tsx

fix: Fix values in Switch teams column (Users page)
Resolves: #2157 
The Switch teams column in Users page can have two values: enabled and false.
The values now can only be Enabled and Disabled

fix(coral): Use disabled instead of false for the value of the Switch teams column in Users page

---

core/src/main/java/io/aiven/klaw/service/EmailService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java

If there is no need to replace by regexp then there is String#replace which is much faster than replaceAll, thus it's better to use it instead

Use String#replace whenever possible

---

coral/src/app/features/components/TopicDetailsModalContent.test.tsx
coral/src/app/features/components/TopicDetailsModalContent.tsx

Resolves: #1679 
The details modal show values for topic partition, topic description and topic replication factor for `CLAIM` requests, but the endpoint does not return them. 
If it's a claim request, the headlines are not shown.

refactor(coral): Update modal with topic request details for CLAIM requests

---

coral/src/domain/requests/requests-transformers.test.ts
coral/src/domain/requests/requests-transformers.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/UtilController.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/model/response/AuthenticationInfo.java
core/src/main/java/io/aiven/klaw/model/response/RequestEntityStatusCount.java
core/src/main/java/io/aiven/klaw/model/response/RequestStatusCount.java
core/src/main/java/io/aiven/klaw/model/response/RequestsCountOverview.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicIntegrationTest.java
openapi.yaml

Resolves: #2173 
- Updates getAuth endpoint to fetch topics count at tenant level
- Adds notnull constraints to /topics/statistics endpoint
Topics count at tenant level doesn't exist
Adding topics count at tenant level in getAuth endpoint

Add Tenant level topics count, null constraints

---

core/Makefile

Enable windows coral build and also continue support for tools like cygwin on windows.
Currently the make file in core builds coral, however it uses unix commands to do so which do not translate to windows machines preventing windws build users from being able to avail f the coral UI.
Now the make file detects if it is a windows OS and if it is , it does a further check to see if it is a unix like shell if not it executes specific dos and powershell compatible command.
In all other cases it will run the existing UNIX commands.
N/A

Enable windows coral build 

---

coral/src/app/components/AsyncNativeSelectWrapper.test.tsx
coral/src/app/components/AsyncNativeSelectWrapper.tsx

This PR introduces `AsyncNativeSelectWrapper`. The component can be used whenever we need a `NativeSelect` where options are based on data fetched from an API. 
`AsyncNativeSelectWrapper` then handles showing the correct loading state as well as showing an error state and notifying the user about errors.
all three states - screenshots are a bit static 😅  I'll use the new component in https://github.com/Aiven-Open/klaw/pull/2144 when it's merged.

refactor(coral): Add native select wrapper to handle  async option data

---

coral/src/app/features/activity-log/ActivityLog.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/connectors/ConnectorApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
coral/src/app/features/components/filters/EnvironmentFilter.tsx
coral/src/app/features/components/filters/TeamFilter.test.tsx
coral/src/app/features/components/filters/TeamFilter.tsx
coral/src/app/features/configuration/users/Users.test.tsx
coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
coral/src/app/features/requests/acls/AclRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/pages/requests/acls/index.test.tsx
coral/src/app/pages/requests/connectors/index.test.tsx
coral/src/app/pages/requests/schemas/index.test.tsx
coral/src/app/pages/requests/topics/index.test.tsx
coral/src/app/pages/topics/index.test.tsx

⚠️ This PR had 2 commits from PR  https://github.com/Aiven-Open/klaw/pull/2143 cherry-picked, so that one would need to be merged first! 
Resolves: #1084 
When the shared Environment or Team filter is used, there is no error handling. In case there is an error in the backend for those endpoints, the filter stays in Loading state and shows no information whatsoever. 
An error in one of the used endpoints will show up as toast and the filter element will have an error information, too:

fix(coral): Add UI error handling in shared filters

---

coral/src/app/components/AsyncNativeSelectWrapper.test.tsx
coral/src/app/components/AsyncNativeSelectWrapper.tsx
coral/src/app/features/activity-log/ActivityLog.test.tsx
coral/src/app/features/components/filters/EnvironmentFilter.test.tsx
coral/src/app/features/components/filters/TeamFilter.test.tsx
coral/src/app/features/components/filters/TeamFilter.tsx
coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/features/requests/acls/AclRequests.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Resolves: #2183
✅  tested on local build as well as dev-mode
(not sure if it's more a fix or a new feature 
- update `AsyncNativeSelectWrapper` to be able to handle all cases / general improvements
-> `entity` now is formatted in error message, so that the upper/lower case letter are correct in all cases
-> test-id now has the entity as part of the id, so we can query for specific selects if needed
-> `ComplexNativeSelect` is now also a valid child 
-> check for valid child needed to cover `displayName` as well as `name` for native select (once for imports from DS, once for imports from `Form.tsx`)
- adds `AsyncNativeSelectWrapper to`
-> TopicRequest
-> TopicSchemaRequest
-> ConnectorRequest
-> TopicDetailsSchema
Note: Following NativeSelect did **not** need a wrapper: …

refactor(coral): Add UI error handling in async filters 

---

core/pom.xml
core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/config/MigrationUtility.java
core/src/main/java/io/aiven/klaw/config/OpenApiConfig.java
core/src/main/java/io/aiven/klaw/service/ExportImportDataService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/application.properties
core/src/test/java/io/aiven/klaw/config/MigrationUtilityTest.java
core/src/test/java/io/aiven/klaw/service/ExportImportDataServiceTest.java
core/src/test/resources/test-application-rdbms-ad-authorization.properties
core/src/test/resources/test-application-rdbms-sso-ad.properties
core/src/test/resources/test-application-rdbms-windows-ad.properties
core/src/test/resources/test-application-rdbms.properties
core/src/test/resources/test-application-rdbms1.properties

Update to use the build info properties to determine the build version of Klaw. This will prevent accidental incorrect configuration in the application.properties files
Currently if an external application.properties file is not updated with the correct build info then the migration Utility does not execute appropriately. As the klaw-version and the properties version are incorrect.
Now the klaw version will be taken from the build properties (from the pom when building) and used internally to ensure the correct version is being used.
This also prevents any issue where the klaw.version in the application.properties file is left with the placeholder that is normally replaced as part of the build.

Version Number in Klaw from buildProperties instead of external configuration

---

coral/src/app/features/configuration/users/Users.test.tsx
coral/src/app/features/configuration/users/Users.tsx
coral/src/domain/user/user-api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/static/js/manageUsers.js
core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java
openapi.yaml

Resolves: #2001 
The endpoint /_showUsers_ takes the _teamName_ parameter to filter by _team_. It uses _teamName_ as a string, but other endpoints where we use _team_ as a parameter use _teamId_.
The endpoint /_showUsers_ takes the _teamId_ parameter to filter by team.
Screenshots of Klaw Core refactored:

refactor: Use id instead of name for querying teams

---

.github/workflows/end-to-end-tests.yaml
.github/workflows/workflow-merge-to-main.yaml
.gitignore
e2e/README.md
e2e/tests/basic-health-check.spec.ts

This PR introduces a new workflow that needs to be completed before being able to merge to main.
The workflow:
- builds Klaw
- opens Klaw and logs in as superadmin
- goes to a coral page and checks that the message visible is from coral
These tests are only meant to make sure that the Klaw build, including coral, was successful.  
⚠️ the test uses the default admin password to login, which will always be correct on CI, but may not be locally. To make sure we're using a clean, reproducible setup of Klaw for E2E tests, we need to setup DB etc. which we've not yet done. I've documented that in README as well as the test file itself.

ci: Add health test e2e

---

core/src/main/java/io/aiven/klaw/service/MailUtils.java

When a new user is added, user details email should be sent to user only and not to team.
This fix, sends email only to user and not to team.
- [ X] Bug fix

Fix for new user mail content

---

core/src/main/java/io/aiven/klaw/helpers/UtilMethods.java

There is no need to calculate `statusTime` if env is not present

Calculate statusTime only when it is required for updateLatestStatus

---

core/src/main/java/io/aiven/klaw/helpers/UtilMethods.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java

The PR is to move load of `userExists` to call it only when it is required

Load userExists only when it is required

---

core/src/main/java/io/aiven/klaw/helpers/KlawResourceUtils.java

Remove the break that was only adding one environment to the list of environments.
Resolves: #2220 
Only one environment is currently returned when you call getTopics
All the environments the topic exists on are added.

Return all environments in the topics overview

---

coral/src/app/features/components/filters/TopicTypeFilter.test.tsx
coral/src/app/features/components/filters/TopicTypeFilter.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/domain/topic/topic-types.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/resources/static/js/browseTopics.js
core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
openapi.yaml

Add the permission check and also use an enum to get the topics with producers or consumer acls you have setup.
Resolves: #2216
Uses a string
Uses an enum

 Use Enum and check permission in getTopics api

---

core/src/main/resources/templates/forgotPassword.html

Resolves: #2212
Reset pw flow design is not harmonious with coral design
Redesigned accordingly:
https://github.com/Aiven-Open/klaw/assets/20607294/e081a5de-c8bd-4ec7-ab6c-889b2e1d25ec

refactor(core): Redesign reset password flow

---

coral/src/app/features/dashboard/Dashboard.tsx
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/dashboard/hooks/useDashboardData.ts
coral/src/domain/analytics/analytics-api.ts

Currently we can't change the timeframe of the requests chart on Dashboard.
Additionally, the copy is wrong, as it shows the *approved* requests.
- Add select component to show 7, 30 or 90 days worth of approved requests
- Change title of section
https://github.com/Aiven-Open/klaw/assets/20607294/6ca88d6c-968b-4438-9753-8c55867db202
Other changes:
- Make each data point have their own loading state as opposed to one loading state for everything on dashboard
- Remove `layout="vertical"` which does nothing (yet)
- [ x The pull request title follows [our guidelines](https://github.com/Aiven-Open/klaw/blob/main/CONTRIBUTING.md#guideline-commit-messages)

feat(coral): Add timeframe dropdown

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/java/io/aiven/klaw/service/RolesPermissionsControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/test/java/io/aiven/klaw/TopicRequestValidatorImplIT.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/EnvsClustersTenantsControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/MailUtilsTest.java
core/src/test/java/io/aiven/klaw/service/OperationalRequestsServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistrySyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/ServerConfigServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/UiConfigControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/UiControllerLoginServiceTest.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

The current issue with `isNotAuthorizedUser` is that it goes each time to db
the idea of this optimization especially for the code like that
```java
if (!commonUtilsService.isNotAuthorizedUser(
getPrincipal(), PermissionType.SYNC_BACK_SUBSCRIPTIONS)
|| !commonUtilsService.isNotAuthorizedUser(getPrincipal(), PermissionType.SYNC_TOPICS)
|| !commonUtilsService.isNotAuthorizedUser(
getPrincipal(), PermissionType.SYNC_SUBSCRIPTIONS)
|| !commonUtilsService.isNotAuthorizedUser(
getPrincipal(), PermissionType.SYNC_BACK_TOPICS)) {
...
```
retrieve permisions for current pricipal and then check against them instead of going to db for each check

Reduce amount of db calls while check permissions

---

coral/src/app/context-provider/AuthProvider.tsx
coral/src/app/pages/configuration/clusters/add/index.tsx
coral/src/app/pages/configuration/clusters/index.test.tsx
coral/src/app/pages/configuration/clusters/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/src/domain/cluster/cluster-api.ts
coral/src/domain/cluster/cluster-types.ts
coral/src/services/feature-flags/route-utils.test.tsx
coral/src/services/feature-flags/route-utils.tsx
coral/src/services/feature-flags/types.ts
coral/vite.config.ts

Resolves: #2294
Superadmin users currently cannot create  clusters from Coral UI.
- add route for add new cluster `/configuration/clusters/add`
- add button `Add new cluster` to `/configuration/clusters` view
- add domain entities for creating new Kafka cluster (`addNewCluster`)
https://github.com/Aiven-Open/klaw/assets/20607294/cbadb0ae-2f4e-427f-aafa-9cf27f93f8d3
- no feature flag added because superadmin users cannot currently access coral
- removed information from the `PrivateRoute` error toast (security liability). It is still visible in the video though, but removed it since haha

feat(coral): Add routes and domain for Add new clusters

---

core/src/main/java/io/aiven/klaw/controller/AclSyncController.java
core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
core/src/main/java/io/aiven/klaw/controller/KafkaConnectSyncController.java
core/src/main/java/io/aiven/klaw/controller/OperationalRequestsController.java
core/src/main/java/io/aiven/klaw/controller/SchemaRegistrySyncController.java
core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/controller/TopicSyncController.java
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/OperationalRequestsService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/test/java/io/aiven/klaw/UsersTeamsControllerIT.java

Update for Admin APIs to have rest endpoints protected with fine grain permission guards.
Resolves: #2276 
Currently checks are done on the FE to prevent access to these pages.
The Admin APIs have checks on them to prevent someone from using them without the correct permission being assigned to the user.

Admin API Guards

---

core/src/main/java/io/aiven/klaw/controller/AclController.java
core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java

Resolves: #2277 #2279  
The permission guards are not applied uniformly this PR adds the permission guards to the endpoints where modifications to the acls and schemas can be made.
Permission Guards are added to the endpoints where modification or creation of the resources can be made.

Add permission guards on ACLS and Schemas

---

coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
coral/src/app/features/configuration/clusters/components/ClustersTable.tsx
coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
coral/src/app/features/topics/details/overview/components/ClusterDetails.tsx
coral/src/domain/cluster/cluster-types.ts
coral/src/domain/cluster/index.ts
coral/src/services/formatter/cluster-type-formatter.ts
coral/src/services/formatter/kafka-flavor-formatter.ts

Resolves: #2308
The enum values are shown, e.g.:
Kafka flavor as well as Cluster type have a const that map the ENUM to a more readable string value. This is used where we show date in the UI.

fix(coral): New enums for kafkaFlavor and clusterType break existing UI

---

coral/src/app/components/Clipboard.test.tsx
coral/src/app/components/Clipboard.tsx
coral/src/app/components/Modal.tsx
coral/src/app/features/components/filters/SearchClusterParamFilter.test.tsx
coral/src/app/features/components/filters/SearchClusterParamFilter.tsx
coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
coral/src/app/features/configuration/clusters/Clusters.test.tsx
coral/src/app/features/configuration/clusters/Clusters.tsx
coral/src/app/features/configuration/clusters/components/ClusterConnectHelpModal.test.tsx
coral/src/app/features/configuration/clusters/components/ClusterConnectHelpModal.tsx
coral/src/app/features/configuration/clusters/components/ClustersTable.test.tsx
coral/src/app/features/configuration/clusters/components/ClustersTable.tsx

Resolves: #2295
After adding a new clusters, users need to edit application.properties to allow Klaw to connect to the cluster. This is documented, but it would be more accessible and pleasant to have the ui provide copy pasteable config to add to it.
This data should stay available easily.
- Add action column in the clusters table opening a modal with copy pasteable `application.properties` values
- Automatically open modal after redirecting to clusters table when adding a new cluster
- Only show for users with the right to act on clusters
- Hide for other users
https://github.com/Aiven-Open/klaw/assets/20607294/da2d22a4-9af5-493e-912f-0bcf19afee3a
https://github.com/Aiven-Open/klaw/assets/20607294/4622398d-66f2-4e87-bd26-cc576b8590f2
If a newly added cluster has exactly the same …

feat(coral): Add `application.properties` recap after adding a new cluster

---

core/src/main/resources/static/js/envs.js
core/src/main/resources/static/js/modifyEnvs.js
core/src/main/resources/templates/clusters.html
core/src/main/resources/templates/modifyCluster.html

Relates to #2307 
ENUMS are shown as is, e.g. 
We show a string value instead of ENUM.
I only could find actual usage of the ENUM as string in `clusters.html` (for users as well as admin) and `modifyCluster.html`.
I hope that is correct!

fix(angular-ui): New enums for kafkaFlavor and clusterType break existing UI 

---

coral/src/domain/cluster/cluster-api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/EnvsClustersTenantsController.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/resources/static/js/envs.js
openapi.yaml

Resolves to: #2314
While `getClustersPaginated`  has a parameter `typeOfCluster`, it uses:
`List<KwClustersModelResponse> kwClustersModelList = getClusters("all");` 
To enabed filtering by `clusterType` in coral later: 
- `getClustersPaginated` now expects `typeOfCluster` being oft type `KafkaClustersType` 
- 
`getClustersPaginated` does take a string (representing the enum of `KafkaClustersType`  `typeOfCluster` 
- it passes `String clusterTypeValue = typeOfCluster.value;` to `getClusters` (this way, there are no further changes needed related to `getClusters`
- it changes "all" to "ALL" for the call to `getClustersPaginated` in `env.js` in Angular (that's the only place I've found it used)
- changes "all" to "ALL" in the same call in coral 
_Additional changes, explanations of the …

feat: Add support for clusterType param in getClustersPaginated endpoint

---

core/src/main/resources/templates/browseAcls.html

The information message to select a version to promote is not displaying.
This message is now displayed correctly. 

Setting the default schema version on promote to be an information message

---

.github/workflows/workflow-check-openapi-changes.yaml

Since permissions etc settings are controlled by the organisation, our github workflow to autogenerate and commit the updated TS types file for openapi changes needs an explict permission to be able to work. 
This PR adds this permission. 
✅ I comitted an openapi change that causes an update for our ts file withoug breaking, and the commit went trough successfully: https://github.com/Aiven-Open/klaw/actions/runs/8165890825/job/22323766564

ci: Add explicit permission to gh workflow for openapi types

---

coral/src/app/features/components/ClusterTypeFilter.test.tsx
coral/src/app/features/components/filters/ClusterTypeFilter.tsx
coral/src/app/features/components/filters/useFiltersContext.test.tsx
coral/src/app/features/components/filters/useFiltersContext.tsx
coral/src/app/features/configuration/clusters/Clusters.test.tsx
coral/src/app/features/configuration/clusters/Clusters.tsx
coral/src/domain/cluster/cluster-api.ts
coral/src/services/formatter/cluster-type-formatter.ts

Resolves: #2316
User now can filter clusters based on cluster type.
https://github.com/Aiven-Open/klaw/assets/943800/e1bad025-d75b-4838-8c40-6c6197b37033

feat(coral): Add cluster type filter to Clusters table 

---

core/src/main/java/io/aiven/klaw/dao/RegisterUserInfo.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/db/changelog/changelog.yaml
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbcTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

Add a new primary key to the register users table and alter queries to allow previously declined usernames to be approved or declined repeatedly.
Resolves: #2364 
Currently once a username is declined it can never be used again in a future request.
Only if the username is already approved or in a pending or staging state will it not allow the creation of a new request.
Previously declined requests will be ignored.
Upgrade scripts tested on a MySQL and Postgres DB.
Both had a mix of existing requests and had the new primary key automatically generated on the update.

Alter Register Users table primary key

---

core/src/main/java/io/aiven/klaw/service/AclControllerService.java

Resolves: #2375 
The Claim ACL was providing the ACL Id instead of the topic owner id to the ACL Claim request meaning that the team would be unknown preventing the claim from being able to be approved.
The topic owner id is now provided so that it may be added to the multi approval.
N/A

Incorrect team identifier added for topic owner id on acl claim request

---

core/src/main/java/io/aiven/klaw/dao/Approval.java
core/src/main/java/io/aiven/klaw/helpers/ApprovalTypeConverter.java

To support mysql databases we need to manage the creation of enums as strings into the db and back out with converters
MySql requires that we make an enum a string before persisting it into the database.

Support Claim ACL request in MySql

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java

When claiming an ACL transfer the ownership of the service user to the new account.
If the existing team no longer has any acls with that service user remove it from their service user accounts.

Issue transfer ownership of service user

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java

Improve cross DB compatibility by using jpql
A native query is being used
The same functionality but we allow JPQL to create the native statements for us.

Improve cross DB compatibility by using jpql

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/BaseOverviewService.java
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java

Improves user experience, when an acl is claimed now it will no longer render the button to others who try to claim the ACL.
Improves user experience by removing the approval from your approvals table when you have approved it.
Currently the claim button is always available even though an existing claim request might be open.
Currently if two approvals are required from the same team it stays even though you are unable to apply the second approval
Claim button is removed after a claim is opened.
Approval Request is removed after you give your approval
NA

Improve Claim experience

---

coral/src/app/layout/header/HeaderNavigation.test.tsx
coral/src/app/layout/header/HeaderNavigation.tsx

Relates to #2307
- `superadmin` user are not allowed to create or approve a request for topics, schemas, acls, connectors. This PR removes the link buttons to those actions in the header navigation.
Note: Since without the feature flag a superadmin can not access coral this change does not need to be behind the feature flag. 
https://github.com/Aiven-Open/klaw/assets/943800/83e87d5e-ee94-40a3-b92d-966716673a87

feat(coral): Don't show request button and notification for superadmin

---

core/src/main/resources/static/js/envs.js

Resolves: #2508 
Strings are compared to each other for default and max paritions and replication
Strings are parsed to ints then compared to each other for default and max paritions and replication

Fix validation to parse partitions as ints first

---

core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java

This PR is ready to be merged, resolves a null pointer exception on SSO setup and the remainder of the issue was resolved through a config update and another docs update is underway to improve the documentation around that.
Resolves: #2533 

Possible null pointer exception is now being avoided

---

core/src/main/java/io/aiven/klaw/auth/KwAuthenticationSuccessHandler.java
core/src/main/java/io/aiven/klaw/controller/ResourceClientController.java
core/src/main/java/io/aiven/klaw/helpers/UtilMethods.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java
core/src/test/java/io/aiven/klaw/helpers/UtilMethodsTest.java

When klaw is configured with an sso provider for identity mgt, username is retrieved from the sso provider user attributes.
This can be preferred_username or email mostly.
Currently klaw handles only preferred_username, and if it's null, klaw cant handle the situation.
When klaw is configured with an sso provider for identity mgt, username is retrieved from the sso provider user attributes.
This can be preferred_username or email mostly.
Currently klaw handles only preferred_username, and if it's null, klaw cant handle the situation.
New situation : klaw handles both these attributes. Based on the configuration, user is authenticated and klaw applies the username attribute internally.

Fix username attributes for sso login

---

.github/dependabot.yml

- add `/coral/proxy` as well as `/e2e` to dependabot config

deps: Add proxy and e2e dir to dependabot

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
core/src/main/resources/templates/browseAcls.html
core/src/main/resources/templates/clusters.html
core/src/main/resources/templates/connectorOverview.html
core/src/main/resources/templates/envs.html

This PR:
- removes the preview banner link for topic overview (details to a topic) and connector overview for superadmins
- adds "tenants" as navigation link to coral, redirecting to Klaw

feat(coral): Adapt superadmin preview banner and add tenants link

---

core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/java/io/aiven/klaw/model/requests/BaseRequestModel.java
core/src/main/java/io/aiven/klaw/model/requests/KafkaConnectorRequestModel.java
core/src/main/java/io/aiven/klaw/model/requests/TopicRequestModel.java
core/src/main/java/io/aiven/klaw/validation/TopicRequestValidatorImpl.java
core/src/test/java/io/aiven/klaw/model/ValidationTest.java

Add extra validation for checking topic description is between 1 and 100 characters long
Resolves: #2683 
API does not check this before it tries to commit it to the database causing a generic error to be returned.
A 400 bad request with a helpful response is returned.

Add extra validation for checking topic description is between 1 and 100 characters long

---

coral/docs/development-with-local-klaw.md
core/pom.xml
core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/resources/application.properties
docker-scripts/docker-compose-klaw.yaml

Delete the default super admin pwd from application config.
User can configure on startup

Delete default superadmin pwd

---

coral/src/app/features/configuration/clusters/AddNewClusterForm.test.tsx
coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx
core/src/main/resources/static/js/envs.js

Resolves: https://aiven.atlassian.net/browse/GOV-981
Changes to the "Add new Cluster" form:
- adds `SSL` as default protocol 
- marks `PLAINTEXT` as not recommended
- if user chooses `PLAINTEXT`, shows warning
- if user wants to submit with `PLAINTEXT`, shows confirmation modal where user needs to confirm this choice to add a new Cluster
- updates the copy in Angular to be consistent
https://github.com/user-attachments/assets/98b6de38-d500-4d66-a121-b4c3010881b4

coral: Mark plaintext as insecure and let user confirm choice when adding new Cluster

---

core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

- Only user with superadmin access (role or permissions) should be able to add and update other super admin users.

Superadmin adding permissions

---

coral/src/app/components/Form.tsx
coral/src/app/features/user-information/change-password/ChangePasswordForm.test.tsx
coral/src/app/features/user-information/change-password/ChangePasswordForm.tsx
coral/src/app/features/user-information/change-password/PasswordStrengthMeter.test.tsx
coral/src/app/features/user-information/change-password/PasswordStrengthMeter.tsx
coral/src/app/features/user-information/change-password/changePasswordFormSchema.ts
coral/src/app/features/user-information/change-password/password-requirement.ts

Resolves: https://aiven.atlassian.net/browse/GOV-987
With BE change https://github.com/Aiven-Open/klaw/pull/2842 we now apply the same validation rules to passwords as we do in Coral when user changes their password. 
Our form to change the password is not very helpful though - while it does show the correct errors, the user should get help _before_ filling out the form how to do so. 
- adds a copy in the page informing users about the rules for password
- adds a "password strength meter" that shows which rules is fullfilled
- adds (visually hidden) an alert with a small timeout to make this information available for e.g. screenreaders in a timely manner
(the little grey box at the bottom of the video shows the screen reader output) …

coral: Update password form for more support and accessibility

---

core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java
core/src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
core/src/test/java/io/aiven/klaw/RolesPermissionsControllerIT.java
core/src/test/java/io/aiven/klaw/SecurityConfigNoSSOIT.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/UsersTeamsControllerIT.java

With this csrf enabling with csrf token (https://docs.spring.io/spring-security/reference/servlet/exploits/csrf.html#csrf-token-repository-httpsession) is stored in http session.
- Enable csrf and ignore logout.
- If we don't ignore logout in csrf, JSESSIONID cookie still exists, and user can access klaw without login, as csrf http token is now being created. So logout functionality would become redundant.
- Alternatively, on logout, we can delete the token from session in FE. But I preferred to do it in backend.
_Additional changes, explanations of the …

Enabling csrf

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java
core/src/main/java/io/aiven/klaw/dao/migration/MigrateData2x10x0.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/model/requests/RegisterUserInfoModel.java
core/src/main/java/io/aiven/klaw/model/requests/UserInfoModel.java
core/src/main/java/io/aiven/klaw/service/DefaultDataService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java
core/src/main/java/io/aiven/klaw/service/PasswordService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/java/io/aiven/klaw/validation/PasswordValidator.java
core/src/main/java/io/aiven/klaw/validation/PasswordValidatorImpl.java
core/src/test/java/io/aiven/klaw/SsoActiveDirectoryAuthenticationIT.java
core/src/test/java/io/aiven/klaw/config/MigrationUtilityTest.java
core/src/test/java/io/aiven/klaw/dao/migration/MigrateData2x10x0Test.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java
openapi.yaml

Upgrading encryption to BCrypt for password storage, also no longer sends plain text passwords to users on initial creation
Also changes emails for new user registration so that they do not get sent a plaintext password in their email.

Upgrading database encryption

---

coral/src/app/features/configuration/clusters/AddNewClusterForm.tsx

Updates link to different page in docs like assumed first

fix(coral): Update link in warning for plaintext

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/SchemaRegistryController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/ClusterSchemaCacheResetRequest.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java

Resolve an issue with the schema registry cache refresh due to not knowing the schemaType. Also addresses an issue for synced schemas.

Schema Registry cache refresh validation error

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/model/requests/UserUpdateInfoModel.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/java/io/aiven/klaw/validation/PasswordUpdateValidator.java
core/src/main/java/io/aiven/klaw/validation/PasswordUpdateValidatorImpl.java
core/src/main/resources/static/js/modifyUser.js
core/src/main/resources/templates/modifyUser.html
core/src/test/java/io/aiven/klaw/UsersTeamsControllerIT.java
core/src/test/java/io/aiven/klaw/controller/UserTeamsControllerTest.java
openapi.yaml

When altering a users information this change allows them not to be required to also update the password.
This bug was introduced when checks were added on the UserInfoModel to ensure passwords always met minimum standards but when updating a user, the password isn't always updated so the masked password is required to be allowed here.

Update user no longer requires password change

---

core/src/main/resources/static/lib/jquery-1.10.2.js

https://github.com/Aiven-Open/klaw/blob/041f8e63809f96322fe4078dec19ca70c8afa320/core/src/main/resources/static/lib/jquery-1.10.2.js#L6569-L6569
Fix the issue need to ensure that the expansion of self-closing tags does not invalidate prior sanitization. Instead of using a regular expression to perform the transformation, we should use a safer approach, such as parsing the HTML string into a DOM structure and manipulating it programmatically. This avoids the pitfalls of regular expressions and ensures that the resulting HTML is well-formed.
The specific change involves replacing the unsafe `elem.replace(rxhtmlTag, "<$1></$2>")` with a safer alternative. We can use a DOM parser to handle the transformation securely. This approach ensures that the input is treated as HTML and avoids …

fix(core): unsafe expansion of self-closing html tag
