Aiven-Open/klaw

pom.xml
src/main/java/io/aiven/klaw/auth/KwRequestFilter.java
src/main/java/io/aiven/klaw/config/ManageDatabase.java
src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java
src/main/resources/application.properties
src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java
src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
src/test/java/io/aiven/klaw/service/UiConfigControllerServiceTest.java

After migrating to latest spring version, noticed a problem with circular dependency
Resolves: Circular dependency problem
Why this way : Main changes to SecurityConfigNoSSO and ManageDatabase had to be fixed for auto wiring and creating beans properly
Related to issue : https://github.com/aiven/klaw/issues/6

Fix Circular dependencies

---

src/main/java/io/aiven/klaw/service/AclControllerService.java
src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
src/main/java/io/aiven/klaw/service/ClusterApiService.java
src/main/java/io/aiven/klaw/service/EnvControllerService.java
src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
src/main/java/io/aiven/klaw/service/TopicControllerService.java
src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
src/main/resources/static/js/envs.js
src/main/resources/templates/clusters.html
src/test/java/io/aiven/klaw/TopicAclControllerIT.java
src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
src/test/java/io/aiven/klaw/service/ClusterApiServiceTest.java

Configure Klaw to handle multiple clusters with different SSL configurations
Resolves: [issue82](https://github.com/aiven/klaw/issues/82)
Why this way : clustername and clusterid are unique across klaw installation.

Multiple ssl config to connect to multiple clusters with ssl protocols

---

src/coral/docs/frontend-testing.md

adds `frontend-testing.md` listing our planned setup and tech stack related to frontend testing
Solves #97

📝 Add doc for frontend testing for coral.

---

src/coral/docs/documentation.md

- adds a new directory `coral/docs` to gather documentation related to the 🪸 ui-rewrite
- adds `documentation.md` capturing our current plan and approach to documentation
Solves #96

📝 Add doc for documentation for coral.

---

src/main/java/io/aiven/klaw/config/ManageDatabase.java
src/main/java/io/aiven/klaw/service/CommonUtilsService.java

The idea is to push down filter by tenantId on jdbc level instead of retrieval data into memory and filter in memory

Use getTenantById rather than getAll

---

SECURITY.md

Adds security policy for the project.
Resolves: #103
Signed-off-by: Josep Prat <josep.prat@aiven.io>

[Docs] Add SECURITY.md file

---

.github/workflows/add_comments.yml
.github/workflows/close-ticket.yml
.github/workflows/create-ticket.yml
.github/workflows/fix_githubname.py
.github/workflows/jira_login.py
.github/workflows/ticket_number.py
.github/workflows/transition-ticket.yml

This PR has all the needed files to enable the repo to sync issues with the Jira board

Adding workflow files for Jira sync

---

.github/workflows/transition-ticket.yml

This PR add the review state to the jira sync workflow

Add review state to Jira sync workflow

---

coral/index.html
coral/package.json
coral/pnpm-lock.yaml
coral/src/App.test.tsx
coral/src/App.tsx
coral/src/main.tsx
coral/vite.config.ts

Adds  and enables the aiven design system component library for coral. 
Relates to: #113

Add aiven design system component library to klaw

---

README.md

Adds information about the work in progress for the UI rewrite. 
Resolves: #145

docs: Update README with info about coral.

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/config/SslContextConfig.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/KafkaConnectController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/TopicContentsController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaAclService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaTopicService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/KafkaConnectService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/MonitoringService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/TopicContentsService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/AuthenticationIntegrationTest.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/KafkaConnectServiceTest.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceTest.java

This PR applies a set of "minor" refactorings:
- remove unused assignments
- avoid casting when using generic types with Spring RestTemplate
- use log.err(String, Throwable) instead of log.error(String, e.toString());
- Files.newInputStream instead of FileInputStream
I hope this provides some value.

Minor refactorings

---

openapi.yaml

This will enable us to generate types for Coral HTTP client.
Resolves: #192

misc: Add OpenAPI specification to /getTopics endpoint

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

The PR makes loading of user info in `io.aiven.klaw.helpers.db.rdbms.SelectDataJdbc#selectActivityLog` only if it is required by movement its loading in corresponding `if`/`else` branch
Also it makes use of `DateTimeFormatter` instead of `SimpleDateFormat` which does not have multithreading issue

Use date time formatter, do not select for user info if not needed

---

coral/src/app/features/topics/BrowseTopics.test.tsx
coral/src/app/features/topics/BrowseTopics.tsx
coral/src/app/features/topics/components/select-env/SelectEnv.test.tsx
coral/src/app/features/topics/components/select-env/SelectEnv.tsx
coral/src/app/features/topics/components/select-team/SelectTeam.test.tsx
coral/src/app/features/topics/components/select-team/SelectTeam.tsx
coral/src/services/test-utils/render-with-query-client.tsx

Use a hard coded string value to represent ALL selection. UUID should not collide with customers team name.

feat(coral): Reflect topic list filter to query params

---

openapi.yaml

feat: include teamNamesGet operation to OpenAPI specification

---

coral/.eslintrc.cjs
coral/jest.config.ts
coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/Form.tsx
coral/src/app/components/Pagination.test.tsx
coral/src/app/features/login/LoginForm.tsx
coral/src/app/features/login/useLoginUser.tsx
coral/src/app/main.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/app/pages/topics/index.tsx
coral/src/config.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/topic/topic-types.ts
coral/src/services/api-client/index.test.ts
coral/src/services/api-client/index.ts
coral/src/types/global.d.ts

adds additional eslint rules to keep imports and exports consistent and avoid future complications

Add eslint rules imports

---

openapi.yaml

feat: include environmentsGet operation to OpenAPI specification

---

core/src/main/java/io/aiven/klaw/service/AclControllerService.java

There is a number of cases where `List` is used only for `contains` operation. In case of list it's O(n) while in case of set it's O(1). So it's better to use set for this

Use set to speed up contains operation

---

coral/src/app/features/browse-topics/hooks/environment/useGetEnvironments.tsx
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-test-helper.test.ts
coral/src/domain/environment/environment-test-helper.ts
coral/src/domain/environment/environment-transformer.test.ts
coral/src/domain/environment/environment-transformer.ts
coral/src/domain/environment/environment-types.ts
coral/types/api.d.ts
openapi.yaml

Refers: https://github.com/aiven/klaw/issues/196

feat(coral): Connect environments API to real backend instead of mocked one

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/components/select-team/SelectTeam.test.tsx
coral/src/app/features/browse-topics/hooks/teams/useGetTeams.test.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/domain/team/team-api.msw.ts

Prefer passing the mocked value as argument.
Refers: #221

refactor(coral): remove scenarios from team api mocks

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/hooks/environment/useGetEnvironments.test.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/domain/environment/environment-api.msw.ts

refactor(coral): remove scenarios from environment api mocks

---

core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

Unit tests for UserTeamsService
Why this way

Add unit tests for UsersTeamsService

---

CONTRIBUTING.md

Update contribution guide with DCO guidelines including how to fix unsigned off commits.

docs: Update contribution guide with DCO guidelines

---

core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/templates/browseTopics.html

Merge only after introducing the `klaw.coral.enabled` application property to AngularJS application. The banner should only be shown when `klaw.coral.enabled` is `true`.
Resolves: #258

feat: Add banner to advertise browse topics rewrite

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx

Following this comment by @SmuliS : https://github.com/aiven/klaw/pull/310#discussion_r1045962130
In tests mocking the API rely exclusively on the quality of our mocks. Implementing `spyOn`  assertions also allows us to ensure we are sending a request to the right URL.
Resolves: #313

refactor(coral) Add spyOn assertions for BrowseTopics tests

---

coral/src/app/components/PreviewBanner.test.tsx
coral/src/app/components/PreviewBanner.tsx
coral/src/app/pages/topics/index.tsx

- Feedback link opens new tab to create new issue to Klaw repository 
Resolves: #326

feat(coral): Add preview disclamer to browse topics view

---

cluster-api/pom.xml
core/pom.xml
core/src/main/resources/application.properties
pom.xml

Increment the version of artifacts to 1.2.0
- klaw-1.2.0
- cluster-api-1.2.0
Signed-off-by: muralibasani <muralidhar.basani@aiven.io>

New release 1.2.0

---

coral/src/app/features/browse-topics/BrowseTopics.test.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.test.tsx
coral/src/app/features/browse-topics/components/select-environment/SelectEnvironment.tsx
coral/src/app/features/browse-topics/components/select-team/SelectTeam.test.tsx
coral/src/app/features/browse-topics/components/select-team/SelectTeam.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/topics/index.test.tsx
coral/src/app/pages/topics/index.tsx

- updates copies and tests related to that
Resolves: #325 
aligns fiter/search elements width props with page header button 
(we may do that after feedback from design, still pending)
**Current layout** 
[screenshot](https://user-images.githubusercontent.com/943800/207573322-b06bc13a-0619-4aa7-9da6-d556e183ff89.png)
**aligning would look like**
[screenshot](https://user-images.githubusercontent.com/943800/207573363-d240eede-4d6d-40e7-be27-ac541a4d2188.png)

refactor(coral): Small design adjustments for browse topics view

---

coral/src/app/components/AuthenticationRequiredBoundary.tsx
coral/src/app/components/Pagination.tsx
coral/src/app/components/PreviewBanner.tsx
coral/src/app/features/browse-topics/BrowseTopics.tsx
coral/src/app/features/browse-topics/components/topic-table/TopicTable.tsx
coral/src/app/features/login/components/LoginForm.tsx
coral/src/app/layout/Layout.tsx
coral/src/app/layout/header/Header.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.tsx
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.test.tsx
coral/src/app/layout/main-navigation/MainNavigationSubmenuList.tsx

- uses `<Divider />` instead of our own implementation as it now works
- replaces `Flexbox` with `Box` as this is the recommendation from DS and Flexbox will be deprecated

refactor(coral): Update usage ds components

---

coral/README.md
coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/topics/browse/BrowseTopics.tsx

- 🐠 updates Aquarium to `1.1.0` 
- 🔄 replaces `FlexboxItem` with `Box` (Flexbox/FlexboxItem are going to be deprecated)
-📙  adds link to new website section about Aquarium in docs

refactor(coral): Bump up design system version and remove FlexboxItem

---

coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/hooks/topic-list/useGetTopics.test.tsx
coral/src/domain/topic/topic-api.msw.ts

refactor(coral): Remove logic unitest from topic API mock

---

openapi.yaml

Applies the formatting required by https://github.com/aiven/klaw/pull/375

refactor(coral): format openapi.yaml with prettier

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx

feat(coral): Extend <Form /> with <NumberInput />

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap

feat(coral): Extend <Form /> with <Textarea />

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap

feat(coral): Extend <Form /> with <NativeSelect />

---

coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-types.ts
coral/types/api.d.ts
openapi.yaml

Includes
- `getSchemaRegEnvs`
- `uploadSchema`
in OpenAPI spec
Resolves: #367

feat(coral): Include "Request new schema" operations to OpenAPI specification

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx

Add `RadioButton` and `RadioButtonGroup` to `Form`

feat(coral): Extend <Form /> with <RadioButton />, <RadioButtonGroup />

---

coral/package.json
coral/pnpm-lock.yaml

chore(coral): Update Aquarium ^1.1.0 -> ^1.2.1

---

coral/tsconfig.json

Removes truncation of type popover (nor only in errors, also on valid code).
https://user-images.githubusercontent.com/20607294/211309432-94de235a-1420-4476-bc7f-4e4927d67e9c.mov

chore(coral): Add "noErrorTruncation": true to tsconfig

---

core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java

- Looks for mandatory parameters topics or topics.regex
- Add unit tests for create connector
Resolves: #311 
Why this way
to create a connector, one of these are mandatory attributes

Fix connector issue, add unit test

---

coral/src/app/components/ComplexNativeSelect.tsx

refactor(coral): optimize lodash import

---

coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx

I did a small demo for @muralibasani as a quick acceptance test session.
Closes: #356

coral: remove API mocks from coral topic request

---

core/src/main/resources/templates/requestSchema.html

This change invokes the javascript request to get the topics to make it available for the UI to render in a drop down.
Why this way
This is a simple, clean solution that resolves the issue.

Resolves issue #424 by populating the topic dropdown

---

core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/resources/static/js/requestAcls.js
core/src/main/resources/swagger_spec.json
core/src/test/java/io/aiven/klaw/controller/TopicControllerTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java

In acl request, show topics of that environment when an environment is selected
Resolves: #463
Why this way

Acl request  - show topics of selected env

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.test.tsx
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
coral/src/app/features/topics/acl-request/fields/EnvironmentField.tsx
coral/src/app/features/topics/acl-request/fields/IpOrPrincipalField.test.tsx
coral/src/app/features/topics/acl-request/fields/IpOrPrincipalField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

- Use "Service Account" terminology when environment selected is an Aiven cluster
- Use consistent sentence casing

fix(coral): Update copy in ACL Request form

---

core/pom.xml

Update mail dependency, spring wrapper over jakarta-mail
Why this way

Mail depndncy

---

coral/src/app/pages/topics/index.tsx
coral/vite.config.ts

feat(coral): remove topic request feature flag

---

coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

As we are navigating the user back to Angular application, we can not use React Router for the operation.

fix(coral): fix redirect after topic schema request

---

Makefile
README.md
cluster-api/pom.xml
core/pom.xml
core/src/main/resources/application.properties
core/src/main/resources/swagger_spec.json
core/src/test/resources/test-application-rdbms-ad-authorization.properties
core/src/test/resources/test-application-rdbms-sso-ad.properties
core/src/test/resources/test-application-rdbms-windows-ad.properties
core/src/test/resources/test-application-rdbms.properties
core/src/test/resources/test-application-rdbms1.properties
pom.xml

Bump klaw release version to 2.0.0
Why this way

Release Version change for 2.0.0

---

coral/src/app/features/topics/acl-request/TopicAclRequest.tsx

Topic team is currently always fetched wityh the value picked from the URL params. 
Fix:
- pick `selectedTopicName` from form
- send request with that value
- only enable query when `selectedTopicName` is not `undefined`

fix(coral): Fetch topicTeam correctly according to selected Topic

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

- Update `aquarium` library to 1.4.1
- Fix use of deprecated `description` prop on the `Alert` component

chore(coral): Update Aquarium ->  1.4.1

---

coral/src/app/pages/approvals/index.tsx

feat(coral): add authentication boundary to approvals page

---

coral/package.json
coral/pnpm-lock.yaml

Update `@aivenio/aquarium` (bug fixes)

chore(coral): Update @aivenio/aquarium -> 1.5.0

---

coral/src/domain/acl/acl-api.ts
coral/types/api.d.ts
openapi.yaml

- add `openapi` documentation
- add `acl-api` function
Resolves: #562

feat(coral): add `/execAclRequestDecline` endpoint

---

coral/src/app/accessibility.module.css

- adds general styles and a globally available class for data-tables to improve accessibility. 
-> adds better contrast
-> adds better visual support for keyboard users

style(coral): Add a11y improvements for tables.

---

core/src/main/resources/static/js/requestTopics.js

For new topic requests, topictype should be Create
Why this way

Fix new topic request

---

coral/src/domain/requests.ts
coral/types/api.d.ts
openapi.yaml

Updates api definition and types based on #623 
Resolves: #634

feat(coral): Add api definition and types for unified approve and decline

---

coral/src/app/features/approvals/acls/AclApprovals.tsx

- Add `status` column in ACL Approvals table
https://user-images.githubusercontent.com/20607294/220332580-97ac1c96-9931-468a-abb1-452a85e85c8f.mov
Resolves: #659

feat(coral): ACL approvals table: add status column

---

coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.tsx

- connects the SchemaApprovals table to endpoint
- adds pagination
Resolves: #653

feat(coral): Connect schema approval table to endpoint

---

coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

- connects the TopicApprovals table to endpoint
- adds pagination 
Resolves: #643

feat(coral): Connect topics approval table to endpoint 

---

coral/package.json
coral/pnpm-lock.yaml

- Update `aquarium` to version 1.8.0
- No impact on current code

chore(coral): Bump aquarium version -> 1.8.0

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/AclApprovals.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

This patch release adds an accessibility improvement for our `DataTable`s

chore(coral): Update DS to 1.8.1 

---

coral/src/app/hooks/useFeatureFlag.ts
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/approvals/index.tsx
coral/vite.config.ts

- remove`FEATURE_FLAG_APPROVALS` feature flag
- fix copy in `MainNavigation` to fit sentence case rule
- fix typo ("Approvals requests")
- remove "fake breadcrumb" above "Approve requests" header

feat(coral): Approvals: Fix copy, remove feature flag

---

coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx
coral/src/domain/requests/requests-types.ts

-> updates the redirect urls to UPPERCASES
Resolves: #748

fix(coral): Change redirect url create workflows.

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/hooks/useTableFilters.tsx
coral/src/app/features/approvals/schemas/SchemaApprovals.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.test.tsx
coral/src/app/features/approvals/schemas/components/SelectSchemaRegEnvironment.tsx
coral/src/app/features/approvals/schemas/hooks/useTableFilters.tsx
coral/src/app/features/approvals/topics/TopicApprovals.test.tsx
coral/src/app/features/approvals/topics/hooks/useTableFilters.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.test.tsx
coral/src/app/features/topics/browse/components/select-environment/SelectEnvironment.tsx
coral/src/app/features/topics/browse/components/topic-table/TopicTable.test.tsx
coral/src/app/features/topics/browse/hooks/environment/useGetEnvironments.test.tsx
coral/src/app/features/topics/browse/hooks/topic-list/useGetTopics.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/hooks/useFeatureFlag.test.ts
coral/src/app/pages/topics/index.test.tsx

A few smaller changes to make our copy more consistent: 
- ✍️ Replaces `environment` with `Environments` in placeholder to be consistent -> "Environment" is a Klaw concept and should also start with an uppercase!
- 🔎 adds more accurate description for assistive technology to search element in approvals table
- 📆 replaces "Date requested" with "Requested on" so all tables and details are consistent

fix(coral): More consistent copy

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java

Simplification of `if` condition in same way as done at https://github.com/aiven/klaw/pull/730#discussion_r1121424706

Simplify if condition with switch for request operation type

---

coral/src/domain/acl/acl-api.ts
coral/types/api.d.ts
openapi.yaml

- Update `openapi` specs and generate types
- Add `getAclRequests` to `acl-api.ts`
Resolves: #798

feat(coral): add API definition and types for `/getAclRequests`

---

coral/test-setup/setup-files-after-env.ts

fix(coral/ci): Remove api calls from frontend jest tests

---

coral/src/app/features/requests/components/acls/AclRequests.test.tsx
coral/src/app/features/requests/components/acls/AclRequests.tsx

- Add pagination to Acl request table
https://user-images.githubusercontent.com/20607294/225248375-e5a70328-cced-4792-8fcc-bf58a6f9cdea.mov
Resolves: #800

feat(coral): Acl Requests: Add pagination to AclRequests

---

coral/src/app/features/requests/components/acls/AclRequests.test.tsx
coral/src/app/features/requests/components/acls/AclRequests.tsx

- Add `TopicFilter` and sync with url search param
- Add tests
Resolves: #801

feat(coral): Acl Requests: add search functionality 

---

coral/src/app/features/components/table-filters/MyRequestFilter.test.tsx
coral/src/app/features/components/table-filters/MyRequestFilter.tsx
coral/src/app/features/requests/components/topics/TopicRequests.test.tsx
coral/src/app/features/requests/components/topics/TopicRequests.tsx
coral/src/domain/topic/topic-api.ts

Makes it possible to view only the requests made by the current user
Resolves: #777

feat(coral): Topic Requests: add Toggle for "My requests" #777

---

coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx

1. adds the `TopicSearch`
2. adds tests
3. Profit 💸
Resolves: #810
https://user-images.githubusercontent.com/943800/225617614-6c7131cb-d757-4761-b149-d6daf7c56079.mov

coral(feat): My Schema Requests - add search functionality

---

coral/src/app/features/requests/components/schemas/SchemaRequests.test.tsx
coral/src/app/features/requests/components/schemas/SchemaRequests.tsx
coral/src/app/features/requests/components/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/requests/components/schemas/utils/mocked-api-responses.ts
coral/src/app/pages/requests/schemas/index.test.tsx

- adds the EnvironmentFilter 
- adds the StatusFilter
(type filter is not yet possible, there is a follow up issue #847 )
Resolves: #811
https://user-images.githubusercontent.com/943800/225675035-e24c8ab7-8676-4fae-9230-85fb840c440b.mov

coral(feat): My Schema Requests - add filter functionality for environment and status

---

core/src/main/resources/templates/requestAcls.html

Acl request page has a problem after refactoring for open api spec. aivenCluster attribute is now a boolean.
Why this way

Fix acl request page

---

coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx

Enable user to filter topic requests by environment and status
Resolves: #840
Resolves: #841

feat(coral): Topic Requests: Add Environment & Status filter #840 #841

---

core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
openapi.yaml

This change corrects a REST API definition
Why this way
This was an incorrect definition for operationType.

Fix defect where default was added instead of required = false

---

coral/src/app/features/components/table-filters/AclTypeFilter.test.tsx
coral/src/app/features/components/table-filters/OperationTypeFilter.test.tsx
coral/src/app/features/components/table-filters/OperationTypeFilter.tsx
coral/src/app/features/components/table-filters/StatusFilter.test.tsx
coral/src/app/features/components/table-filters/TopicFilter.test.tsx

- add `OperationTypeFilter` to be used in tables
Resolves: #887

feat(coral): Add OperationTypeFilter

---

coral/src/app/features/approvals/topics/TopicApprovals.tsx
coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.test.tsx
coral/src/app/features/requests/topics/components/TopicRequestsTable.tsx
coral/src/domain/topic/topic-api.ts

Enables user to delete a topic request
Resolves: #779

feat(coral): Topic Requests: add Delete flow #779

---

coral/src/app/features/requests/topics/TopicRequests.test.tsx
coral/src/app/features/requests/topics/TopicRequests.tsx
coral/src/domain/topic/topic-api.ts

Enables user to filter topic requests by operation type
Resolves: #842

feat(coral): Topic Requests: Add Type Filter #842

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/accessibility.module.css
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
coral/src/app/features/topics/acl-request/fields/AclTypeField.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx

We lag a little bit behind `aquarium` releases, so these are the notable changes that affect us most:
- there was a font weight fix which kind of messed our overrides (more about that in the "additional changes" section)
- there is a `Spacing` component now! We can space things!
- `DataTable` now has sticky columns and sorting functionalities, which I'm sure will come in handy
- [`onChange` bug in `Pagination`](https://github.com/aiven/design-system/issues/946) is fixed! Only a11y prevents us from using the component now.
We have some styles overrides in `accessibility.module.css` for labels. I think the color rules are great, but I am not convinced by the font weight and font size ones.
- too heavy of a font weight is a hindrance to legibility, I think
- too small of a font size is also …

chore(coral) Update aquarium 1.14

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
openapi.yaml

Fixes a bug with users retrieving
Why this way

Fix for user list

---

coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/connector-transformer.ts
coral/src/domain/connector/connector-types.ts
coral/src/domain/connector/index.ts

Add functions to interact with connector request apis
Resolves: #961

Add functions to interact with connector request apis

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

Add Pagination controls to ConnectorRequests and sync it with the ConnectorRequestsTable
Resolves:  #965

feat(coral): My Connector Requests: Add Pagination to the ConnectorRequests

---

coral/src/app/features/connectors/browse/BrowseConnectors.test.tsx
coral/src/app/features/connectors/browse/BrowseConnectors.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.test.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/features/requests/RequestsResourceTabs.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx
coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.test.tsx
coral/src/app/features/requests/connectors/components/ConnectorRequestsTable.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/connectors/index.tsx
coral/src/app/pages/requests/connectors/index.test.tsx
coral/src/app/pages/requests/connectors/index.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts
coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/connector-transformer.ts
coral/src/domain/connector/connector-types.ts
coral/src/domain/connector/index.ts
coral/src/domain/environment/environment-api.msw.ts
coral/src/domain/environment/environment-api.ts
coral/src/domain/environment/environment-types.ts
coral/src/domain/environment/index.ts

2.2 was released. Let's merge the already reviewed stuff to main!

Changes to be merged to main after 2.2 release

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

User is able to filter teams connector requests by environment
Resolves: #970

feat(coral): My Connector Requests: Add Environment filter #970

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

User is able to view only own requests in my teams connector requests view.
Resolves: #967

feat(coral): My Connector Requests: Add Toggle to myRequests #967

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

User is able to filter my teams connector requests by operation type'
Resolves: #972

feat(coral): My Connector Requests: Add Type filter #972

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

User is able to delete my teams connector requests.
Resolves: #969

feat(coral): My Connector Requests: Add Delete flow #969

---

coral/src/app/features/requests/connectors/ConnectorRequests.test.tsx
coral/src/app/features/requests/connectors/ConnectorRequests.tsx

User is able to view request details in my teams connector requests view.
Resolves: #968

feat(coral): My Connector Requests: Add Show details flow #968

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/resources/templates/browseAcls.html
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java

- Topic claim request bug fix
- Connector documentation saving bug fix
Resolves: #755 
Why this way

Fix topic claim, connector documentation req

---

coral/src/app/pages/approvals/connectors/index.tsx
coral/src/app/pages/connectors/index.tsx
core/src/main/resources/templates/execConnectors.html
core/src/main/resources/templates/kafkaConnectors.html
core/src/main/resources/templates/myConnectorRequests.html

Add preview banners with correct links for new Connectors UI.
https://user-images.githubusercontent.com/20607294/233009909-f05b9130-2cd4-4655-8a55-93d6bac0b725.mov
Resolves: #984

feat(coral): Add preview banners for connectors

---

coral/src/app/features/connectors/request/ConnectorRequest.tsx
coral/src/app/pages/connectors/index.tsx
coral/src/app/pages/connectors/request.tsx
coral/src/app/router.tsx
coral/src/app/router_utils.ts

- Add `Routes.CONNECTOR_REQUEST`
- Redirect to correct route when clicking Request new connector
- Add stub component for Connector request
Resolves: #1054

feat(coral): Add `connectors/request` route and stub component

---

coral/src/app/components/Form.test.tsx
coral/src/app/components/Form.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/login/components/LoginForm.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest.tsx
coral/src/app/features/topics/acl-request/fields/AclIpPrincipleTypeField.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.tsx
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-producer.ts
coral/src/app/features/topics/acl-request/schemas/topic-acl-request-shared-fields.ts
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx

Implements new validation behaviour for forms:
- `SubmitButton` is now always enabled, allowing to attempt submit incomplete / incorrect form values
- validation happens `onTouched` rather than `onBlur`
https://user-images.githubusercontent.com/20607294/232783144-a17f42e7-23fc-429d-beb8-e0d8bc64145b.mov
https://user-images.githubusercontent.com/20607294/232783269-c312febd-8ee9-4705-ae2c-e5c0944d789d.mov
Resolves: #676

refactor(coral): Update `Form` and its implementations

---

core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/test/java/io/aiven/klaw/EnvsClustersTenantsControllerIT.java
core/src/test/java/io/aiven/klaw/RolesPermissionsControllerIT.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/UsersTeamsControllerIT.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java

Sync topics was resulting in failure, even after success. Bug fix.
Why this way

Fix Sync UI issue

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/ApacheKafkaTopicService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/resources/static/js/registerUsers.js
core/src/main/resources/templates/register.html

- On user signup, removing tenant
- topic deletion, when schema association is involved, it fails
- on sync topics, reset cache
Why this way

Topic deletion fix

---

coral/src/domain/connector/connector-api.ts

- removes hard coded param after #974 is finished
https://user-images.githubusercontent.com/943800/234569035-a4c5ddfd-8e52-40fc-8f04-c9e46761528a.mov
Resolves: #987

feat(coral): Enable isMyRequest in "My team's Connector requests"

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/approvals/topics/TopicApprovals.tsx

bump major version to 5
Resolves: #1090

coral: Update typescript to next major version #1090

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/KafkaConnectController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/KafkaConnectService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/controller/KafkaConnectControllerTest.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java

Deleting a connector was not working which is fixed now
Why this way

Fix connector deletion

---

coral/src/app/features/approvals/components/ApprovalResourceTabs.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.test.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/pages/connectors/index.tsx
core/src/main/resources/templates/kafkaConnectors.html
core/src/main/resources/templates/synchronizeConnectors.html

Changes "Kafka connectors" -> "Connectors"
Resolves: #1046
Ref: https://app.slack.com/client/T0CK0GQ05/C040JF3VDJR/thread/C040JF3VDJR-1682623001.112989

chore(coral): Copy consistency for Connectors UI #1046

---

core/src/main/java/io/aiven/klaw/config/EmailConfig.java

Smtp authentication configuration based on flag
Why this way

Smtp auth fix

---

README.md
cluster-api/pom.xml
core/pom.xml
pom.xml

Update readme
Increment version to 2.3.0
Why this way

Increment ver 2.3.0

---

coral/src/domain/topic/topic-api.ts

The topic overview feature will need this endpoint to render the proper UI. This PR adds it to the relevant `domain`

feat(coral): Add `getTopicOverview` to `topic` `domain`

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/model/TopicHistory.java
core/src/main/java/io/aiven/klaw/model/TopicOverviewInfo.java
core/src/main/java/io/aiven/klaw/model/response/AclOverviewInfo.java
core/src/main/java/io/aiven/klaw/model/response/EnvIdInfo.java
core/src/main/java/io/aiven/klaw/model/response/PromotionStatus.java
core/src/main/java/io/aiven/klaw/model/response/ResourceOverviewAttributes.java
core/src/main/java/io/aiven/klaw/model/response/TopicOverview.java
core/src/main/java/io/aiven/klaw/service/BaseOverviewService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/TopicOverviewServiceTest.java
openapi.yaml

Updates mandatory fields for getTopicOverview api call
Why this way

Update TopicOverview mandatory flds

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/static/js/connectorOverview.js
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/AclRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/KafkaConnectorsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SchemaRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbcTest.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java

This change returns all the requests for approval within a tenant if the correct permission is associated with your user.
Why this way

Issue approve all requests permission

---

core/src/main/resources/templates/execConnectors.html
core/src/main/resources/templates/myConnectorRequests.html

Request Operation Type was missing for my teams requests and for approvals in angular ui
Why this way

Fix defect where Request Type isnt shown on promotion

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/SchemaRegistryController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/models/RegisterSchemaCustomResponse.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/SchemaService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/SchemaServiceRegisterSchemaTest.java
coral/src/services/api.ts
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/SchemaRegistrySyncController.java
core/src/main/java/io/aiven/klaw/dao/MessageSchema.java
core/src/main/java/io/aiven/klaw/dao/SchemaRequest.java
core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/model/SchemaResetCache.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistrySyncControllerService.java
core/src/main/resources/db/changelog/changelog.yaml
core/src/main/resources/static/js/synchronizeSchemas.js
core/src/main/resources/templates/synchronizeSchemas.html
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistrySyncControllerServiceTest.java
openapi.yaml

Get schema details from metadata if available
Resolves: #1291
Why this way
If metadata is available locally, rest api calls are not required.

Fetch schemas from metadata if there

---

coral/src/app/features/topics/details/TopicDetails.test.tsx
coral/src/app/features/topics/details/TopicDetails.tsx
coral/src/app/features/topics/details/components/TopicDetailsResourceTabs.tsx
coral/src/app/features/topics/details/history/TopicHistory.test.tsx
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/SchemaRegistryController.java
core/src/main/java/io/aiven/klaw/controller/TopicController.java
core/src/main/java/io/aiven/klaw/model/requests/TopicClaimRequestModel.java
core/src/main/java/io/aiven/klaw/model/requests/TopicDeleteRequestModel.java
core/src/main/java/io/aiven/klaw/model/requests/TopicRequestModelOtherTypes.java
core/src/main/java/io/aiven/klaw/model/response/SchemaOverview.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/SchemaOverviewService.java
core/src/main/resources/static/js/browseAcls.js
core/src/main/resources/templates/browseAcls.html
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java
core/src/test/java/io/aiven/klaw/service/SchemaOverviewServiceTest.java
openapi.yaml

- From acl sync process, principal type is being updated.
- topic delete and claim apis change to requestbody
- schemaoverview change from list item to single object
Why this way
cluster api requires this

Fix acl principal type check

---

.github/ISSUE_TEMPLATE/01_question.md
README.md

Changes issue templates for questions.
Why this way
We are hoping to improve the question and answer usability and lower the barrier to asking questions.

Add links to appropriate question and answer forums and discussion areas

---

.github/ISSUE_TEMPLATE/config.yml

Uses the yaml file to create links to questions and answers
Why this way

Add these templates as links.

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/topics/details/components/StatsDisplay.test.tsx
coral/src/app/features/topics/details/components/StatsDisplay.tsx
coral/src/app/features/topics/details/history/TopicHistory.tsx
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.tsx
coral/src/app/features/topics/details/schema/components/SchemaStats.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaStats.tsx
coral/src/app/images/topic-details-schema-Illustration.svg
coral/src/app/pages/topics/details/schema/index.tsx
coral/src/app/router.tsx
coral/vite.config.ts

- Adds the topic details schema with mocked data and without functionality.
Closes #1318

feat(coral): Topic details schema - add view with mocked data

---

core/src/main/java/io/aiven/klaw/service/UtilControllerService.java
core/src/main/resources/application.properties

Checks if the auto generated coral index.html exists
Resolves: #1216 
Why this way
simple change that only has to be updated in one place.

Check if you coral is enabled

---

core/src/main/java/io/aiven/klaw/model/TopicOverviewInfo.java
core/src/main/java/io/aiven/klaw/service/EmailService.java
core/src/main/java/io/aiven/klaw/service/TopicOverviewService.java

Makes it possible to return a boolean to tell the UI that there are open requests.
Why this way

Add additional boolean for clarity

---

coral/src/app/accessibility.module.css
coral/src/app/components/AuthenticationRequiredAlert.tsx
coral/src/app/components/Modal.module.css
coral/src/app/components/Modal.tsx
coral/src/app/layout/main-navigation/MainNavigationLink.module.css
coral/src/app/main.module.css
coral/src/app/pages/not-found/index.tsx

- Adds custom klaw theme with DS variables (recommended way)
Resolves: #1312
I tried to make screenshots from all views.
trie

style(coral): Add custom theme

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/DeleteDataJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbcTest.java

during delete team, check if schemas are deleted too
Why this way

team delete fix

---

Makefile
README.md
openapi.yaml
pom.xml

Release 240

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/resources/templates/registrationReview.html
core/src/main/resources/templates/registrationReviewSaas.html

Improves emails to be more descriptive as to the purpose of the email and not as generic so that they do not get confused with other types of emails.
Why this way
Improves user experience.

Update default emails to improve messaging based on user feedback

---

coral/src/__mocks__/react-markdown.tsx
coral/src/app/components/FileInput.tsx
coral/src/app/components/Form.tsx
coral/src/app/context-provider/AuthProvider.tsx
coral/src/app/features/requests/components/DeleteRequestDialog.tsx
coral/src/app/features/requests/schemas/components/SchemaRequestTable.test.tsx
coral/src/app/features/topics/browse/BrowseTopics.test.tsx
coral/src/app/main.module.css
coral/src/app/pages/topics/schema-request.tsx
coral/src/domain/environment/environment-api.ts
coral/src/domain/topic/topic-transformer.ts

- removes unneeded comments 
- uses JSDOC format for comments where it's useful (to provide better devex for different IDEs)

refactor(coral): Update comments 🧹

---

coral/src/app/features/connectors/details/history/ConnectorHistory.test.tsx
coral/src/app/features/connectors/details/history/ConnectorHistory.tsx
coral/src/app/router.tsx

Add History tab for connector details:
https://github.com/aiven/klaw/assets/20607294/dc8c0888-0ec9-40c8-aad2-ce807805eddb
Resolves: #1466

feat(coral) - Connector details : Add connector history tab

---

core/src/main/java/io/aiven/klaw/constants/MapConstants.java
core/src/main/java/io/aiven/klaw/constants/UriConstants.java
core/src/main/java/io/aiven/klaw/controller/TemplateMapController.java
core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java
core/src/main/java/io/aiven/klaw/service/UiControllerLoginService.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/constants/TestConstants.java
core/src/test/java/io/aiven/klaw/service/AnalyticsControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/EnvControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/UiControllerLoginServiceTest.java
core/src/test/java/io/aiven/klaw/service/ValidateCaptchaServiceTest.java

unit test and minor refactor: 
- Added unit tests for core package service classes
- Added constant classes for loose coupling.
Do not merge.

unit test and minor refactor

---

core/src/main/java/io/aiven/klaw/service/EnvControllerService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

Adds the Cluster Status to the cluster object as well s the env object
Why this way

Add Cluster Status to the cluster response model

---

coral/src/domain/topic/index.ts
coral/src/domain/topic/topic-api.ts

Add `claimTopic` to topic `domain`
Resolves: #1486

feat(coral): Add createClaimTopicRequest domain

---

coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.tsx

Some `Box` components were using `element` instead of `component`.

fix(coral): Use correct `component` prop for `Box`

---

coral/src/app/features/connectors/details/ConnectorDetails.tsx
coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorEditRequest.tsx
coral/src/app/pages/connectors/edit-request.tsx
coral/src/domain/connector/connector-api.ts
coral/src/domain/connector/connector-types.ts
coral/src/domain/connector/index.ts

Add Edit Connector feature
https://github.com/aiven/klaw/assets/20607294/98a9638c-2248-4136-b38f-b2bd02c780cb
This PR shed light on an inaccuracy with `getConnectorDetailsPerEnv` documentation which will be addresed by this issue: https://github.com/aiven/klaw/issues/1522

feat(coral): Connector details: Edit connector

---

coral/src/app/features/components/ConnectorDetailsModalContent.test.tsx
coral/src/app/features/components/ConnectorDetailsModalContent.tsx
coral/src/app/features/components/TopicDetailsModalContent.test.tsx
coral/src/app/features/components/TopicDetailsModalContent.tsx
coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.tsx

refactor(coral): Add [entity] to 'Description' to be more precise

---

coral/src/app/components/InternalLinkButton.test.tsx
coral/src/app/components/InternalLinkButton.tsx
coral/src/app/components/__snapshots__/InternalLinkButton.test.tsx.snap
coral/src/app/features/components/EntityDetailsHeader.test.tsx
coral/src/app/features/components/EntityDetailsHeader.tsx
coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.test.tsx
coral/src/app/features/topics/details/overview/components/TopicPromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionBanner.test.tsx

Replaces use of buttons with `navigate` with new component. 
Resolves: #1535

refactor(coral): Use correct button link component for internal links

---

coral/package.json
coral/pnpm-lock.yaml

This upgrade `vite` to address a security concern with `vite` in version < 4.3.9

fix(coral): Update vite dep -> 4.4.8

---

.mvn/wrapper/maven-wrapper.properties

The PR Updates mvn in `.mvn` to 3.9.4 and maven-wrapper to 3.2.0

Bump maven to 3.9.4 and maven-wrapper to 3.2.0

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwPropertiesRepo.java

The idea is to load into memory only one record to update it.Moving this to SQL allows to eliminate iit from java code and allows to minimize amount of data transferring between the app and db

Load only first kw property instead of all

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java
core/src/main/java/io/aiven/klaw/repository/AclRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRepo.java
core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/repository/SchemaRequestRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java

The idea is to check for existence instead cound or all records to minimize amount of data transferring between the app and db

Check for existence rather than count

---

core/src/main/java/io/aiven/klaw/config/ConfigUtils.java
core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java
pom.xml

Upgrades spring starter to 3.1.2
Resolves PR #1497 
Why this way

Spring upgrade to 3.1.2

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/ActivityLogRepo.java

Currently it selects everything from DB and then cuts on java side if result is too large
Frankly speaking it could be done on DB side, then less efforts in data transferring and filtering

Use limit in sql instead of java for activity related queries

---

coral/proxy/README.md
coral/types/api.d.ts

style(coral): Update types and format

---

coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.test.tsx
coral/src/app/features/topics/details/messages/components/TopicMessageOffsetFilter.tsx

- adds description to radio button group 
Resolves: #1590

refactor(coral): Add description to message offset field

---

core/src/main/java/io/aiven/klaw/controller/KafkaConnectController.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java

When a connector has to be updated, with password fields, double encryption occurs, which is fixed in this.
Resolves: #1621 
Why this way

Update connector bug fix

---

README.md

adds status badges (the easy ones first)

✨ Add status badges to README

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/RegisterInfoRepo.java

The idea is pretty straightforward: do not use find all where it is not required

Use find first instead of find all

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

There could be used `Stream.of()....anyMatch();` instead of for loop

Make code for exist methods more concise

---

coral/src/app/features/components/ClaimBanner.test.tsx
coral/src/app/features/components/ClaimBanner.tsx
coral/src/app/features/components/EntityDetailsHeader.test.tsx
coral/src/app/features/components/EntityDetailsHeader.tsx
coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.test.tsx
coral/src/app/features/topics/details/components/PromotionBanner.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/components/NoSchemaBanner.test.tsx
coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.test.tsx
coral/src/app/features/topics/details/schema/components/OpenSchemaRequestAlert.tsx
coral/src/app/features/topics/details/settings/TopicSettings.test.tsx

Update copy when action is blocked to be more explicit. 
Commits are done for every action, hope that helps with review! 
Resolves: #1666

refactor(coral): Update text for blocked actions

---

Makefile
README.md
openapi.yaml
pom.xml

This PR updates version numbers in the pom, openapi and make files.
It also adds some important information into the README.md
Why this way

Release 2.5.0 version updates and readme updates.

---

.github/workflows/jobs-maven.yaml

Enable jdk20 in ci

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/MessageSchemaRepo.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistrySyncControllerService.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistrySyncControllerServiceTest.java

Just use find first to minimize amount of data passing between the App and db

Use find first schema instead find all

---

core/src/main/java/io/aiven/klaw/helpers/Pager.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/AclSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/OperationalRequestsService.java
core/src/main/java/io/aiven/klaw/service/Pager.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistrySyncControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/main/java/io/aiven/klaw/service/UiConfigControllerService.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/helpers/PagerTest.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/AclSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/KafkaConnectSyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistrySyncControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/TopicSyncControllerServiceTest.java

The PR introduces reusable pager and replaces duplicated code
it fixes one of the points mentioned at https://github.com/Aiven-Open/klaw/issues/1690

Introduce reusable pager

---

core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/MailUtils.java

It seems for some cases there is a useless call to db in this method while there is no need for such

Optimize AclControllerService#verifyIfTopicExists

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/java/io/aiven/klaw/service/ExportImportDataService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

`DateTimeFormatter` could be reused, so no need to create a new object every time

Use DateTimeFormatter instead of SimpleDateFormat

---

core/src/main/java/io/aiven/klaw/helpers/Pager.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java

Fixes pagination that was not being correctly calculated for the old angular model.
Why this way

Update code to paginate properly with > and >> and < and << use

---

core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

A Second loop was being executed to add booleans, this loop was (inefficient) also not being invoked when needed for other teams to determine if they could claim the topic
Resolves: #1716 
Why this way

Claim and open request booleans not invoked for teams looking to claim topic.

---

.github/dependabot.yml

ci/cd(coral): Add pnpm to dependabot

---

Makefile
openapi.yaml
pom.xml

Update the branch release-251 with the correct versions
Why this way

Update pom for release

---

core/src/main/java/io/aiven/klaw/service/EmailService.java
core/src/main/java/io/aiven/klaw/service/OnStartupService.java
core/src/main/resources/application.properties

- This change allows you to configure your own logo in mail notification header
- Configurable display text for no reply
Resolves: https://github.com/Aiven-Open/klaw/issues/1766
Why this way

Configurable logo in email notifications header

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java

Minimize amount of requests to database

Extract userinfo into one var for InsertDataJdbc#insertIntoRequestAcl

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/UserInfoRepo.java

The problem is that there is no limitation by username in query
At the same time this limitation is applied on every cycle iteration
the PR moves this limitation to query level from java

Add limitation by username to reduce amount of data transferring from db

---

CONTRIBUTING.md

Resolves: #1817
Contains minor condescending language
Fixed
Ran the alexjs linter and manually verified all warnings

docs: Fix condescending language

---

pom.xml

The problem with snake-yaml is that there are several CVEs e.g. https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-1471

Upgrade snake yaml to 2.2

---

coral/src/app/layout/header/ProfileDropdown.test.tsx
coral/src/app/layout/header/ProfileDropdown.tsx

- [ x ] Bug fix
User and team name are not shown in the ProfileDropdown, but placeholder. 
Correct data is shown.

fix(coral): Add user and team name to profile dropdown.

---

.mvn/wrapper/maven-wrapper.properties

Update mvn version to 3.9.5

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

The idea of the PR is pretty straightforward: instead creation a new list each time just return same constant empty  list in case of no data

Return same empty array list instead of creation a new one in case of no data

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/JwtTokenUtilService.java
core/pom.xml
core/src/main/java/io/aiven/klaw/service/JwtTokenUtilService.java
pom.xml

Dependencies upgrade for 
- swagger
- jwt
- shedlock
- guava

Upgrade dependencies

---

core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/AnalyticsControllerService.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/MetricsControllerService.java
core/src/test/java/io/aiven/klaw/constants/TestConstants.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicIntegrationTest.java
core/src/test/java/io/aiven/klaw/service/AnalyticsControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/CommonUtilsServiceTest.java

The PR introduces `ChartOverviewItem` which allows to avoid lots of not needed maps creation and minimize parsing of int from strings

Introduce chartoverview item

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

The PR is going to fix `umberFormatException` issue for "Analytics" Dashboard

Filter out values of date column since they are not used

---

Makefile
README.md
bin/run-klaw.sh
coral/types/api.d.ts
openapi.yaml
pom.xml

For release 260

---

cluster-api/src/test/java/io/aiven/klaw/clusterapi/AuthenticationIntegrationIT.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiConfluentCloudControllerIT.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ConnectControllerIT.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/JwtTokenUtilServiceTest.java
core/src/main/java/io/aiven/klaw/service/ClusterApiService.java
core/src/main/java/io/aiven/klaw/service/HARestMessagingService.java
core/src/test/java/io/aiven/klaw/config/CustomJwtDecoderTest.java

Replace deprecated Jwts methods with non-deprecated alternatives

---

core/src/main/java/io/aiven/klaw/helpers/KwConstants.java
core/src/main/resources/application.properties

By default sending notifications is enabled, and errors are thrown constantly when requests are created without configuring notifications
Sending notifications is disabled by default

Update notifications flag

---

core/pom.xml
pom.xml

Updates dependencies
- failsafe, surefire
- commons
- swagger
- adding spring admin jvm argument for openapi spec generation

Update deps, spring admin

---

coral/src/app/features/approvals/acls/AclApprovals.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/components/AclDetailsModalContent.test.tsx
coral/src/app/features/components/AclDetailsModalContent.tsx
coral/src/app/features/components/filters/AclTypeFilter.test.tsx
coral/src/app/features/components/filters/AclTypeFilter.tsx
coral/src/app/features/requests/acls/AclRequests.test.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.test.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
coral/src/app/features/topics/details/overview/components/ClusterDetails.test.tsx
coral/src/app/features/topics/details/overview/components/ClusterDetails.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaStats.test.tsx
coral/src/app/features/topics/details/schema/components/SchemaStats.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx

We're using  ALLCAPS in some labels where we shouldn't. See screenshots in issue.
No ALLCAPS.

refactor(coral): remove allcaps from labels

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java

The issue is that in  `selectAllTopicsForTeamGroupByEnv`on every iteration it calls to db because of `getEnv`
The idea of the PR is to have just one call to DB for all envs and then use the result of it instead of a call per loop iteration

Use bulk getEnv to minimize amount of calls to db

---

core/src/main/java/io/aiven/klaw/config/ManageDatabase.java
core/src/main/java/io/aiven/klaw/helpers/HandleDbRequests.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/HandleDbRequestsJdbc.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwEntitySequenceRepo.java
core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/test/java/io/aiven/klaw/config/ManageDatabaseTest.java

Entity sequence is not updated in certain situations.
This makes sure they are updated during start of the app.
- [ X] Bug fix

Bug fix for entity sequence

---

core/src/main/java/io/aiven/klaw/dao/Topic.java
core/src/main/java/io/aiven/klaw/helpers/KlawResourceUtils.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/service/CommonUtilsService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicSyncControllerService.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/TopicControllerServiceTest.java

There is `Topic#environmentList` which is used to check `contains`
in fact for lists contains is an expensive operation, probably it is better to replace it with set and th PR does it

Use set for envs since it requires contains operation

---

core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java
core/src/main/java/io/aiven/klaw/service/OperationalRequestsService.java
core/src/main/java/io/aiven/klaw/service/RolesPermissionsControllerService.java
core/src/main/java/io/aiven/klaw/service/SchemaRegistryControllerService.java
core/src/main/java/io/aiven/klaw/service/TopicControllerService.java
core/src/test/java/io/aiven/klaw/service/AclControllerServiceTest.java
core/src/test/java/io/aiven/klaw/service/SchemaRegistryControllerServiceTest.java

The PR is aming to use set for approver roles to speed up contains operations and the fact that set contains distinct values

Use set for approver roles

---

coral/src/app/features/approvals/acls/components/AclApprovalsTable.test.tsx
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.test.tsx
coral/src/app/features/approvals/connectors/components/ConnectorApprovalsTable.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.test.tsx
coral/src/app/features/approvals/schemas/components/SchemaApprovalsTable.tsx
coral/src/app/features/approvals/topics/components/TopicApprovalsTable.tsx

feat(coral) - Approve requests: Add Team column in Schemas and Connectors tables

---

core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java
core/src/main/resources/application.properties
core/src/test/java/io/aiven/klaw/service/EnvsClustersTenantsControllerServiceTest.java

If the klaw.uiapi.servers are setup to use https but the correct https setting have not been setup they cause an issue with configuring the environments.
The default behaviour will be http and then when deleting in the future the null pointer caused by the missing data will not cause the deletion of the environment to fail.

Defect env id null pointer

---

Makefile
README.md
openapi.yaml
pom.xml

Update POM and versions for release 2.5.2

Version update to release 2.5.2

---

Makefile
bin/run-klaw.sh
openapi.yaml
pom.xml

Update Release version 2.6.1

---

core/src/main/java/io/aiven/klaw/service/KafkaConnectControllerService.java

There is no need for creation an extra array and then checking for contains.
The original string could be used for that

Check for contains by String rather than creating extra array

---

bin/run-klaw.bat
cluster-api/pom.xml
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java
coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/model/requests/MyProfileModel.java
core/src/main/java/io/aiven/klaw/model/requests/ProfileModel.java
core/src/main/java/io/aiven/klaw/model/requests/RegisterUserInfoModel.java
core/src/main/java/io/aiven/klaw/model/requests/UserInfoModel.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/UtilMethods.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java
openapi.yaml

- [ X] Bug fix
- [ X] New feature
- Cluster api logging : Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
- Update profile throwing error because of other mandatory flds
- Run klaw script for windows was not available
- Added exclusion for commons-logging in mock-server dependency
- Introduced another UserModel for profile
- Added run-klaw-bat in bin dir

Update profile, fix dependency, add run klaw script

---

pom.xml

Spring boot 3.2.0 is available

Upgrade springboot to 3.2.0

---

coral/types/api.d.ts
core/src/main/java/io/aiven/klaw/controller/UsersTeamsController.java
core/src/main/java/io/aiven/klaw/error/KlawErrorMessages.java
core/src/main/java/io/aiven/klaw/model/requests/ChangePasswordRequestModel.java
core/src/main/java/io/aiven/klaw/model/requests/UserInfoModel.java
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/main/resources/static/js/manageUsers.js
core/src/main/resources/templates/changePwd.html
core/src/test/java/io/aiven/klaw/MockMethods.java
core/src/test/java/io/aiven/klaw/controller/UiConfigControllerTest.java
core/src/test/java/io/aiven/klaw/model/UserInfoModelTest.java
openapi.yaml

Currently chPwd endpoint takes request parameters as input which is not a standard
chPwd api is now updated to take a requestbody as input

Update changePassword api with input request body

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/Form.test.tsx
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/approvals/acls/components/AclApprovalsTable.tsx
coral/src/app/features/configuration/environments/Kafka/components/KafkaEnvironmentsTable.tsx
coral/src/app/features/connectors/browse/components/ConnectorTable.tsx
coral/src/app/features/requests/acls/components/AclRequestsTable.tsx
coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
coral/src/app/features/topics/browse/components/TopicTable.tsx
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/src/app/features/topics/details/subscriptions/TopicSubscriptionsTable.tsx
coral/src/app/layout/header/HeaderNavigation.tsx
coral/src/app/layout/header/ProfileDropdown.tsx

We are ehind on `aquarium` versions
Update to latest version
- The tests for `SwitchTeamsDropdown` were failing because the `menu` doesn't have a `name`. But I am not sure where this `name` came from in the first place. Maybe you know @programmiri , and maybe my fix to the test is not the correct one.

housekeeping(coral): Update `aquarium` ->  `1.47.0`

---

cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java

- [ X] Bug fix
Few tests like resetOffsets and getting topicContents fail to run on Windows consistently
This is a known issue for Kafka on Windows. Hence ignore the tests on windows temporarily.

Ignore few cluster api tests for Windows

---

cluster-api/pom.xml
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java

Upgrade spring kafka test dependency to 3.1.0
Existing code does not work
Had to refactor few classes like kraft=false property to be set

Upgrade spring kafka test dep

---

.github/dependabot.yml
cluster-api/src/test/java/io/aiven/klaw/clusterapi/ClusterApiControllerIT.java

Checks maven dependencies once in a month
Currently it is weekly
Changing the maven dependencies check to monthly

Update maven dependencies once in a month

---

coral/src/app/layout/Layout.test.tsx
coral/src/app/layout/LayoutWithoutNav.test.tsx
coral/src/app/layout/header/RequestsDropdown.tsx
coral/src/app/layout/main-navigation/MainNavigation.test.tsx

- Due to missing mocks in tests for some components that are using the statictics hook, there are multiple api calls in tests that are failing and slowing everything done (49 x `Network request failed`)
- The way the text for DropdownMenu item is generated causes an accessibility warning in Aquarium

refactor(coral): Small cleanup - fix test with api calls and remove warning for Aquarium component

---

core/src/main/java/io/aiven/klaw/repository/KwKafkaConnectorRequestsRepo.java
core/src/main/java/io/aiven/klaw/repository/TopicRequestsRepo.java
core/src/test/java/io/aiven/klaw/helpers/db/rdbms/TopicRequestsIntegrationTest.java

Fix claim requests for topics and connectors

---

core/src/main/java/io/aiven/klaw/service/HARestMessagingService.java

Since `requestFactory` is static it should be volatile and there should be check with sync as several requests in parallel could come
also in case of failure it would make sense to have more human friendly exception message rather than just NPE

Make requestFactory volatile

---

.mvn/wrapper/maven-wrapper.properties

Bump maven version together with its sha256 checksum

Update maven in maven wrapper to 3.9.6

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/InsertDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/KwEntitySequenceRepo.java

The idea is to use exists queries instead of count queries to minimize overhead on db side

Use exists instead of count in queries

---

core/src/main/java/io/aiven/klaw/service/EnvsClustersTenantsControllerService.java

Filteres in `EnvsClustersTenantsControllerService#getClustersPaginated`  could be merged and be more concise

Simplify EnvsClustersTenantsControllerService#getClustersPaginated

---

Makefile
bin/run-klaw.bat
bin/run-klaw.sh
coral/types/api.d.ts
openapi.yaml
pom.xml

Release 2.7.0

---

coral/src/app/components/PreviewBanner.test.tsx
coral/src/app/components/PreviewBanner.tsx
coral/src/app/features/components/SchemaRequestDetails.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotableOnlyAlert.tsx
coral/src/app/features/topics/details/schema/components/SchemaPromotionModal.tsx
coral/src/app/features/topics/request/components/AdvancedConfiguration.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.tsx

Removes target=_blank from links to improve potential security risks, accessibility and usability. 
Based on discussion/agreement we had: (internal slack link: https://aiven-io.slack.com/archives/C040JF3VDJR/p1698651729417509?thread_ts=1698219887.106169&cid=C040JF3VDJR)

refactor(coral): Remove target=_blank from links

---

coral/package.json
coral/pnpm-lock.yaml
coral/vite.config.ts

Resolves: #2136 
- updates vite to version 5.0
- update vite config with (typing)
- add manual code splitting for monaco editor and aquarium (two of the biggest deps) for smaller chunkgs

deps(coral):  Update vite to next major version and add chunk splitting

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap

Outdated `aquarium` dependency
Latest `aquarium` version

housekeeping(coral): update `aquarium` -> v 1.50.0

---

coral/src/app/features/connectors/details/documentation/ConnectorDocumentation.test.tsx
coral/src/app/features/connectors/details/settings/ConnectorSettings.test.tsx
coral/src/app/features/connectors/request/ConnectorEditRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorPromotionRequest.test.tsx
coral/src/app/features/connectors/request/ConnectorRequest.test.tsx
coral/src/app/features/team-info/SwitchTeamsDropdown.test.tsx
coral/src/app/features/team-info/TeamInfo.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest_consumer.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest_producer.test.tsx
coral/src/app/features/topics/acl-request/TopicAclRequest_shared.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicConsumerForm.test.tsx
coral/src/app/features/topics/acl-request/forms/TopicProducerForm.test.tsx
coral/src/app/features/topics/details/TopicDetails.test.tsx
coral/src/app/features/topics/details/documentation/TopicDocumentation.test.tsx
coral/src/app/features/topics/details/schema/TopicDetailsSchema.test.tsx
coral/src/app/features/topics/details/settings/TopicSettings.test.tsx
coral/src/app/features/topics/details/subscriptions/TopicSubscriptions.test.tsx
coral/src/app/features/topics/request/TopicEditRequest.test.tsx
coral/src/app/features/topics/request/TopicPromotionRequest.test.tsx
coral/src/app/features/topics/request/TopicRequest.test.tsx
coral/src/app/features/topics/schema-request/TopicSchemaRequest.test.tsx
coral/src/app/features/user-information/change-password/ChangePasswordForm.test.tsx
coral/src/app/pages/topics/details/index.test.tsx
coral/src/services/test-utils/render-with-wrappers.tsx
coral/types/utils.d.ts

Resolves: #1536
- updates `customRender` to be more easily to extend
- add `aquariumContext` as render option to `customRender`
- replace usage of using `<AquariumContext>` in tests in favour of configuring the `customRender` option

refactor(coral): Add aquarium context to custom render

---

coral/src/app/features/dashboard/Dasboard.test.tsx
coral/src/app/features/dashboard/Dashboard.tsx
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/dashboard/hooks/useDashboardData.ts

To fetch data for rendering on the dashboard, we use:
-  `usePendingRequests` which is lacking in the loading state and error handling department
- `useAuthContext` whihc returns static values, only updated when user does a full page reload
This leads to a suboptimal experiences regarding the data displayed on the Dashboard (stale data, inconsistent loading state)
- Aggregate all necessary API calls in a single `useDashboardData`
- Add toast notification in case of error

feat(coral): Add `useDashboardData` hook

---

coral/src/app/components/AsyncNativeSelectWrapper.tsx

✅  checked on dev server as well as in built
Component only shows `invalid child` error in DEV mode.

refactor(coral): Remove error in `AsyncNativeSelectWrapper` for production mode.

---

core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/main/java/io/aiven/klaw/repository/AclRepo.java

This will reduce amount of data transferring between db and app

Use countDistinctTopicNameByAclTypeAndTeamIdAndTenantId rather than select all

---

core/src/main/java/io/aiven/klaw/service/MailUtils.java

This is a follow up for https://github.com/Aiven-Open/klaw/pull/2204
to make it using new approach

Use MailType for notifySubscribersOnSchemaChange

---

core/src/main/java/io/aiven/klaw/controller/AnalyticsController.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/SelectDataJdbc.java
core/src/test/java/io/aiven/klaw/controller/AnalyticsControllerTest.java

For every day with a value a zero value is also added so some dates appear twice in the graph.
Each date only appears once.

Fix two small issues for analytics endpoint

---

coral/src/app/layout/main-navigation/MainNavigation.test.tsx
coral/src/app/layout/main-navigation/MainNavigation.tsx
coral/src/app/router.tsx
coral/src/services/feature-flags/types.ts
coral/vite.config.ts
core/src/main/java/io/aiven/klaw/auth/KwAuthenticationSuccessHandler.java
e2e/tests/basic-health-check.spec.ts

Resolves: #2202 
- removes feature flag for dashboard
- changes redirect after login to dashboard instead of browse-topics

feat(coral): remove feature flag dashboard

---

coral/src/app/components/PermissionCheck.test.tsx

A comment made it past review 🙈

fix(coral): Remove forgotten comment

---

coral/src/app/features/dashboard/Dashboard.tsx
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap

There are some errors flagged when loading Dashboard in dev env (not in prod build). Additionally, the support for `vertical` layout of bar charts is now there, and should be implemented, as per designs
https://github.com/Aiven-Open/klaw/assets/20607294/474bc984-da9c-42f0-bb61-5ad42e363d9b
- Fix small mistakes and oversights resulting in errors
- Implement vertical layout for bar chart
https://github.com/Aiven-Open/klaw/assets/20607294/7cce8e6f-ad7d-4514-906d-fc06e8346446

fix(coral): Dashboard: Fix console errors, make bar chart vertical

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap

Aquarium v 1.52.2
Aquarium v 1.53.0

housekeeping(coral): Update aquarium -> 1.53.0

---

core/src/main/resources/templates/activityLog.html
core/src/main/resources/templates/changePwd.html
core/src/main/resources/templates/clusters.html
core/src/main/resources/templates/index.html
core/src/main/resources/templates/myProfile.html
core/src/main/resources/templates/showTeams.html
core/src/main/resources/templates/showUsers.html
core/src/main/resources/templates/tenantInfo.html

Add banners in angular to views that now have coral equivelants so they can switch over and use them.

Add banners to coral on new views

---

Makefile
bin/run-klaw.bat
bin/run-klaw.sh
core/src/test/java/io/aiven/klaw/service/ExportImportDataServiceTest.java
openapi.yaml
pom.xml

Klaw is set as 2.7.0
Klaw release to 2.8.0
N/A

Update to release Klaw 2.8.0

---

core/src/main/java/io/aiven/klaw/service/utils/CacheService.java

there is a better instead of checking agaist contains first and then returning a avlue

Use computeIfAbsent

---

core/src/main/java/io/aiven/klaw/controller/RolesPermissionsController.java
core/src/main/java/io/aiven/klaw/controller/ServerConfigController.java
core/src/main/java/io/aiven/klaw/controller/UiConfigController.java
core/src/main/java/io/aiven/klaw/controller/UtilController.java

Add guards for a few additional endpoints and make sure that they are appropriately secure
A few missed admin apis and also the roles api endpoints are not secure.
They are now secured.

Admin Guards for roles

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap

Updates aquarium to version 1.57.1 as update to newest version 1.58.0 currently doesn't work: https://github.com/Aiven-Open/klaw/pull/2320

build(deps): Update aquarium to 1.57.1

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/accessibility.module.css
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/team-info/TeamInfo.tsx

Updates aquarium to newest version, this includes a change we need to be able to merge https://github.com/Aiven-Open/klaw/pull/2350
Note
-> since after (a previous) update, the table header got a bolder font, so I changes the color from #000 to grey-70 so it's aligned with e.g. labels. I applied the same color to the "switch team" label since it looked off.

build(deps): Update aquarium 1.60.1

---

Makefile
bin/run-klaw.bat
bin/run-klaw.sh
core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
openapi.yaml
pom.xml

When creating a user with email id as username, it fails, as pattern doesnt allow it
This caused due to refactoring in last sprint.
Adding the pattern back. Allowing email as username.

Bug fix: when creating new users with username being a email id as pattern

---

core/src/main/java/io/aiven/klaw/service/UsersTeamsControllerService.java
core/src/test/java/io/aiven/klaw/service/UsersTeamsControllerServiceTest.java

Fixes username with email pattern, when adding a new user
Resolves: 
- [ X] Bug fix

Fixes username with email pattern, when adding a new user

---

cluster-api/src/main/java/io/aiven/klaw/clusterapi/controller/ClusterApiController.java
cluster-api/src/main/java/io/aiven/klaw/clusterapi/services/AivenApiService.java
cluster-api/src/test/java/io/aiven/klaw/clusterapi/services/AivenApiServiceTest.java
core/src/main/java/io/aiven/klaw/helpers/db/rdbms/UpdateDataJdbc.java
core/src/main/java/io/aiven/klaw/service/AclControllerService.java
core/src/test/java/io/aiven/klaw/TopicAclControllerIT.java

- [ X] Bug fix
When deleting Aiven acl, the service account associated with the team is not being removed
When deleting Aiven acl, the service account associated with the team is now removed

Fix for delete service account

---

Makefile
README.md
bin/run-klaw.bat
bin/run-klaw.sh
coral/types/api.d.ts
openapi.yaml
pom.xml

Release 2.9.0 https://github.com/Aiven-Open/klaw/releases/edit/untagged-8ed6f64fce57227ead23

Release 2.9.0

---

.github/workflows/workflow-merge-to-main.yaml

Test commit

---

.github/workflows/workflow-merge-to-main.yaml

Test merge branch to main

---

.github/workflows/workflow-merge-to-main.yaml

Test PR please ignore this again.

Another test

---

.github/workflows/workflow-merge-to-main.yaml

Test branch the third

---

coral/docs/development-with-remote-api.md

Resolves: #2526 
Broken link with extra whitespace. 
Correct link which redirects.

docs: fixes broken markdown link 

---

docker-scripts/klaw-docker.sh

deps: Update docker compose to V2

---

README.md
coral/.nvmrc
coral/README.md
coral/docs/development-with-local-klaw.md
coral/docs/development-witout-api.md
coral/package.json
coral/pnpm-lock.yaml
coral/proxy/package.json
coral/proxy/pnpm-lock.yaml
e2e/package.json

Update Node and pnpm to latest stable major versions.

deps,infra: Update pnpm and node versions

---

.github/ISSUE_TEMPLATE/01_question.md
README.md

Update mention / links to community forum - specific link to ask a question (prefilled category and tag) to make sure the post is seen.

docs: Update community forum link

---

coral/package.json
coral/pnpm-lock.yaml
coral/src/app/components/__snapshots__/Form.test.tsx.snap
coral/src/app/components/__snapshots__/InternalLinkButton.test.tsx.snap
coral/src/app/features/components/filters/SearchFilter.tsx
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/src/app/layout/main-navigation/MainNavigationLink.tsx

Updates design system and related needed changes. 
- [ x] Deps update

deps(coral): Update design-system

---

coral/src/app/features/topics/request/utils.ts

Resolves: #2562 
same env as in bug report with updated FE

fix(coral): Update topic name description generation for topic request form

---

coral/src/app/features/topics/request/form-schemas/topic-request-form.ts

This PR fixes some smaller issues:
- Update error message for request topic name patterns

fix(coral): Fix error validation message for topic name pattern

---

coral/jest.config.ts
coral/package.json
coral/pnpm-lock.yaml
coral/src/__mocks__/svg.ts
coral/src/app/components/Form.tsx
coral/src/app/features/dashboard/__snapshots__/Dasboard.test.tsx.snap
coral/src/app/features/topics/details/overview/__snapshots__/TopicOverview.test.tsx.snap
coral/tsconfig.jest.json

Updates design-system to new major version 🎉 
- fix some typing in `Form.tsx` related to that change
- update jest.config.ts to be able to handle es module (also needed specific mock for svgs)
- update snapshots

deps: Bump aquarium new major version

---

core/src/main/java/io/aiven/klaw/config/SecurityConfigNoSSO.java

Remove the password from the log

---

Makefile
bin/run-klaw.bat
bin/run-klaw.sh
openapi.yaml
pom.xml

Minor release for improvement on SSO user onboarding flows

Minor release for sso flows
